### ISSUE TITLE
Error and warn in console

### ISSUE THREAD

**Issue by flantertw** [plan-player-analytics/Plan#1039]
### Server information

This server is running CraftBukkit version git-Spigot-1eece4f-7d29eb5 (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)

> Player AnalyticsVersion: 4.8.2
Update Available: No
 Active Database: H2 (OPEN)
 Connected to Bungee: No

### Exceptions & Other Logs

Error - server console
```
[18:06:49] [Plan WebServer Thread-0/ERROR]: [Plan] Error was caught by com.djrapitops.plan.system.webserver.ResponseHandler
com.djrapitops.plan.api.exceptions.database.DBOpException: SQL Failed: SELECT v1.uuid as uuid,v1.double_value as double_value,v1.long_value as long_value,v1.string_value as string_value,p1.name as provider_name,p1.text as text,p1.format_type as format_type,p1.player_name as is_player_name,i1.name as provider_icon_name,i1.family as provider_icon_family FROM plan_extension_user_values v1 INNER JOIN (SELECT plan_sessions.uuid,MAX(session_end) as last_seen FROM plan_sessions GROUP BY uuid ORDER BY session_end DESC LIMIT ?) as last_seen_q on last_seen_q.uuid=v1.uuid INNER JOIN plan_extension_providers p1 on p1.id=v1.provider_id INNER JOIN plan_extension_plugins e1 on e1.id=p1.plugin_id LEFT JOIN plan_extension_icons i1 on i1.id=p1.icon_id WHERE e1.server_uuid=? AND  v1.boolean_value IS NULL AND  v1.percentage_value IS NULL AND  p1.player_name=?; (Message 90016 not found); SQL statement:
SELECT v1.uuid as uuid,v1.double_value as double_value,v1.long_value as long_value,v1.string_value as string_value,p1.name as provider_name,p1.text as text,p1.format_type as format_type,p1.player_name as is_player_name,i1.name as provider_icon_name,i1.family as provider_icon_family FROM plan_extension_user_values v1 INNER JOIN (SELECT plan_sessions.uuid,MAX(session_end) as last_seen FROM plan_sessions GROUP BY uuid ORDER BY session_end DESC LIMIT ?) as last_seen_q on last_seen_q.uuid=v1.uuid INNER JOIN plan_extension_providers p1 on p1.id=v1.provider_id INNER JOIN plan_extension_plugins e1 on e1.id=p1.plugin_id LEFT JOIN plan_extension_icons i1 on i1.id=p1.icon_id WHERE e1.server_uuid=? AND  v1.boolean_value IS NULL AND  v1.percentage_value IS NULL AND  p1.player_name=? [90016-199]
	at com.djrapitops.plan.api.exceptions.database.DBOpException.forCause(DBOpException.java:37) ~[Plan-4.8.2.jar:?]
	at com.djrapitops.plan.db.access.QueryStatement.executeQuery(QueryStatement.java:55) ~[Plan-4.8.2.jar:?]
	at com.djrapitops.plan.db.SQLDB.query(SQLDB.java:214) ~[Plan-4.8.2.jar:?]
	at com.djrapitops.plan.extension.implementation.storage.queries.ExtensionServerPlayerDataTableQuery.executeQuery(ExtensionServerPlayerDataTableQuery.java:58) ~[Plan-4.8.2.jar:?]
	at com.djrapitops.plan.extension.implementation.storage.queries.ExtensionServerPlayerDataTableQuery.executeQuery(ExtensionServerPlayerDataTableQuery.java:46) ~[Plan-4.8.2.jar:?]
	at com.djrapitops.plan.db.SQLDB.query(SQLDB.java:214) ~[Plan-4.8.2.jar:?]
	at com.djrapitops.plan.system.webserver.pages.json.JSONFactory.serverPlayersTableJSON(JSONFactory.java:66) ~[Plan-4.8.2.jar:?]
	at com.djrapitops.plan.system.webserver.pages.json.PlayersTableJSONHandler.getResponse(PlayersTableJSONHandler.java:61) ~[Plan-4.8.2.jar:?]
	at com.djrapitops.plan.system.webserver.pages.TreePageHandler.getResponse(TreePageHandler.java:68) ~[Plan-4.8.2.jar:?]
	at com.djrapitops.plan.system.webserver.ResponseHandler.tryToGetResponse(ResponseHandler.java:155) ~[Plan-4.8.2.jar:?]
	at com.djrapitops.plan.system.webserver.ResponseHandler.getResponse(ResponseHandler.java:101) [Plan-4.8.2.jar:?]
	at com.djrapitops.plan.system.webserver.RequestHandler.handle(RequestHandler.java:98) [Plan-4.8.2.jar:?]
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79) [?:1.8.0_191]
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83) [?:1.8.0_191]
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82) [?:1.8.0_191]
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675) [?:1.8.0_191]
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79) [?:1.8.0_191]
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: plan.org.h2.jdbc.JdbcSQLSyntaxErrorException: (Message 90016 not found); SQL statement:
SELECT v1.uuid as uuid,v1.double_value as double_value,v1.long_value as long_value,v1.string_value as string_value,p1.name as provider_name,p1.text as text,p1.format_type as format_type,p1.player_name as is_player_name,i1.name as provider_icon_name,i1.family as provider_icon_family FROM plan_extension_user_values v1 INNER JOIN (SELECT plan_sessions.uuid,MAX(session_end) as last_seen FROM plan_sessions GROUP BY uuid ORDER BY session_end DESC LIMIT ?) as last_seen_q on last_seen_q.uuid=v1.uuid INNER JOIN plan_extension_providers p1 on p1.id=v1.provider_id INNER JOIN plan_extension_plugins e1 on e1.id=p1.plugin_id LEFT JOIN plan_extension_icons i1 on i1.id=p1.icon_id WHERE e1.server_uuid=? AND  v1.boolean_value IS NULL AND  v1.percentage_value IS NULL AND  p1.player_name=? [90016-199]
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:573) ~[?:?]
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:427) ~[?:?]
	at plan.org.h2.message.DbException.get(DbException.java:205) ~[?:?]
	at plan.org.h2.message.DbException.get(DbException.java:181) ~[?:?]
	at plan.org.h2.expression.ExpressionColumn.updateAggregate(ExpressionColumn.java:195) ~[?:?]
	at plan.org.h2.command.dml.Select.updateAgg(Select.java:553) ~[?:?]
	at plan.org.h2.command.dml.Select$LazyResultGroupSorted.fetchNextRow(Select.java:1963) ~[?:?]
	at plan.org.h2.result.LazyResult.hasNext(LazyResult.java:101) ~[?:?]
	at plan.org.h2.result.LazyResult.next(LazyResult.java:60) ~[?:?]
	at plan.org.h2.command.dml.Select.queryGroupSorted(Select.java:311) ~[?:?]
	at plan.org.h2.command.dml.Select.queryWithoutCache(Select.java:877) ~[?:?]
	at plan.org.h2.command.dml.Query.queryWithoutCacheLazyCheck(Query.java:151) ~[?:?]
	at plan.org.h2.command.dml.Query.query(Query.java:435) ~[?:?]
	at plan.org.h2.command.dml.Query.query(Query.java:397) ~[?:?]
	at plan.org.h2.index.ViewIndex.find(ViewIndex.java:288) ~[?:?]
	at plan.org.h2.index.ViewIndex.find(ViewIndex.java:160) ~[?:?]
	at plan.org.h2.index.BaseIndex.find(BaseIndex.java:132) ~[?:?]
	at plan.org.h2.index.IndexCursor.find(IndexCursor.java:163) ~[?:?]
	at plan.org.h2.table.TableFilter.next(TableFilter.java:475) ~[?:?]
	at plan.org.h2.table.TableFilter.next(TableFilter.java:545) ~[?:?]
	at plan.org.h2.table.TableFilter.next(TableFilter.java:545) ~[?:?]
	at plan.org.h2.table.TableFilter.next(TableFilter.java:545) ~[?:?]
	at plan.org.h2.table.TableFilter.next(TableFilter.java:545) ~[?:?]
	at plan.org.h2.command.dml.Select$LazyResultQueryFlat.fetchNextRow(Select.java:1882) ~[?:?]
	at plan.org.h2.result.LazyResult.hasNext(LazyResult.java:101) ~[?:?]
	at plan.org.h2.result.LazyResult.next(LazyResult.java:60) ~[?:?]
	at plan.org.h2.command.dml.Select.queryFlat(Select.java:742) ~[?:?]
	at plan.org.h2.command.dml.Select.queryWithoutCache(Select.java:884) ~[?:?]
	at plan.org.h2.command.dml.Query.queryWithoutCacheLazyCheck(Query.java:151) ~[?:?]
	at plan.org.h2.command.dml.Query.query(Query.java:435) ~[?:?]
	at plan.org.h2.command.dml.Query.query(Query.java:397) ~[?:?]
	at plan.org.h2.command.CommandContainer.query(CommandContainer.java:145) ~[?:?]
	at plan.org.h2.command.Command.executeQuery(Command.java:202) ~[?:?]
	at plan.org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:115) ~[?:?]
	at com.djrapitops.plan.db.access.QueryStatement.executeQuery(QueryStatement.java:65) ~[?:?]
	at com.djrapitops.plan.db.access.QueryStatement.executeQuery(QueryStatement.java:52) ~[?:?]
	... 19 more
[18:06:49] [Plan WebServer Thread-0/WARN]: [Plan] Error was caught by com.djrapitops.plan.system.webserver.response.ResponseFactory
com.djrapitops.plan.api.exceptions.database.DBOpException: SQL Failed: SELECT v1.uuid as uuid,v1.double_value as double_value,v1.long_value as long_value,v1.string_value as string_value,p1.name as provider_name,p1.text as text,p1.format_type as format_type,p1.player_name as is_player_name,i1.name as provider_icon_name,i1.family as provider_icon_family FROM plan_extension_user_values v1 INNER JOIN (SELECT plan_sessions.uuid,MAX(session_end) as last_seen FROM plan_sessions GROUP BY uuid ORDER BY session_end DESC LIMIT ?) as last_seen_q on last_seen_q.uuid=v1.uuid INNER JOIN plan_extension_providers p1 on p1.id=v1.provider_id INNER JOIN plan_extension_plugins e1 on e1.id=p1.plugin_id LEFT JOIN plan_extension_icons i1 on i1.id=p1.icon_id WHERE e1.server_uuid=? AND  v1.boolean_value IS NULL AND  v1.percentage_value IS NULL AND  p1.player_name=?; (Message 90016 not found); SQL statement:
SELECT v1.uuid as uuid,v1.double_value as double_value,v1.long_value as long_value,v1.string_value as string_value,p1.name as provider_name,p1.text as text,p1.format_type as format_type,p1.player_name as is_player_name,i1.name as provider_icon_name,i1.family as provider_icon_family FROM plan_extension_user_values v1 INNER JOIN (SELECT plan_sessions.uuid,MAX(session_end) as last_seen FROM plan_sessions GROUP BY uuid ORDER BY session_end DESC LIMIT ?) as last_seen_q on last_seen_q.uuid=v1.uuid INNER JOIN plan_extension_providers p1 on p1.id=v1.provider_id INNER JOIN plan_extension_plugins e1 on e1.id=p1.plugin_id LEFT JOIN plan_extension_icons i1 on i1.id=p1.icon_id WHERE e1.server_uuid=? AND  v1.boolean_value IS NULL AND  v1.percentage_value IS NULL AND  p1.player_name=? [90016-199]
	at com.djrapitops.plan.api.exceptions.database.DBOpException.forCause(DBOpException.java:37) ~[Plan-4.8.2.jar:?]
	at com.djrapitops.plan.db.access.QueryStatement.executeQuery(QueryStatement.java:55) ~[Plan-4.8.2.jar:?]
	at com.djrapitops.plan.db.SQLDB.query(SQLDB.java:214) ~[Plan-4.8.2.jar:?]
	at com.djrapitops.plan.extension.implementation.storage.queries.ExtensionServerPlayerDataTableQuery.executeQuery(ExtensionServerPlayerDataTableQuery.java:58) ~[Plan-4.8.2.jar:?]
	at com.djrapitops.plan.extension.implementation.storage.queries.ExtensionServerPlayerDataTableQuery.executeQuery(ExtensionServerPlayerDataTableQuery.java:46) ~[Plan-4.8.2.jar:?]
	at com.djrapitops.plan.db.SQLDB.query(SQLDB.java:214) ~[Plan-4.8.2.jar:?]
	at com.djrapitops.plan.system.webserver.pages.json.JSONFactory.serverPlayersTableJSON(JSONFactory.java:66) ~[Plan-4.8.2.jar:?]
	at com.djrapitops.plan.system.webserver.pages.json.PlayersTableJSONHandler.getResponse(PlayersTableJSONHandler.java:61) ~[Plan-4.8.2.jar:?]
	at com.djrapitops.plan.system.webserver.pages.TreePageHandler.getResponse(TreePageHandler.java:68) ~[Plan-4.8.2.jar:?]
	at com.djrapitops.plan.system.webserver.ResponseHandler.tryToGetResponse(ResponseHandler.java:155) ~[Plan-4.8.2.jar:?]
	at com.djrapitops.plan.system.webserver.ResponseHandler.getResponse(ResponseHandler.java:101) [Plan-4.8.2.jar:?]
	at com.djrapitops.plan.system.webserver.RequestHandler.handle(RequestHandler.java:98) [Plan-4.8.2.jar:?]
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79) [?:1.8.0_191]
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83) [?:1.8.0_191]
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82) [?:1.8.0_191]
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675) [?:1.8.0_191]
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79) [?:1.8.0_191]
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: plan.org.h2.jdbc.JdbcSQLSyntaxErrorException: (Message 90016 not found); SQL statement:
SELECT v1.uuid as uuid,v1.double_value as double_value,v1.long_value as long_value,v1.string_value as string_value,p1.name as provider_name,p1.text as text,p1.format_type as format_type,p1.player_name as is_player_name,i1.name as provider_icon_name,i1.family as provider_icon_family FROM plan_extension_user_values v1 INNER JOIN (SELECT plan_sessions.uuid,MAX(session_end) as last_seen FROM plan_sessions GROUP BY uuid ORDER BY session_end DESC LIMIT ?) as last_seen_q on last_seen_q.uuid=v1.uuid INNER JOIN plan_extension_providers p1 on p1.id=v1.provider_id INNER JOIN plan_extension_plugins e1 on e1.id=p1.plugin_id LEFT JOIN plan_extension_icons i1 on i1.id=p1.icon_id WHERE e1.server_uuid=? AND  v1.boolean_value IS NULL AND  v1.percentage_value IS NULL AND  p1.player_name=? [90016-199]
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:573) ~[?:?]
	at plan.org.h2.message.DbException.getJdbcSQLException(DbException.java:427) ~[?:?]
	at plan.org.h2.message.DbException.get(DbException.java:205) ~[?:?]
	at plan.org.h2.message.DbException.get(DbException.java:181) ~[?:?]
	at plan.org.h2.expression.ExpressionColumn.updateAggregate(ExpressionColumn.java:195) ~[?:?]
	at plan.org.h2.command.dml.Select.updateAgg(Select.java:553) ~[?:?]
	at plan.org.h2.command.dml.Select$LazyResultGroupSorted.fetchNextRow(Select.java:1963) ~[?:?]
	at plan.org.h2.result.LazyResult.hasNext(LazyResult.java:101) ~[?:?]
	at plan.org.h2.result.LazyResult.next(LazyResult.java:60) ~[?:?]
	at plan.org.h2.command.dml.Select.queryGroupSorted(Select.java:311) ~[?:?]
	at plan.org.h2.command.dml.Select.queryWithoutCache(Select.java:877) ~[?:?]
	at plan.org.h2.command.dml.Query.queryWithoutCacheLazyCheck(Query.java:151) ~[?:?]
	at plan.org.h2.command.dml.Query.query(Query.java:435) ~[?:?]
	at plan.org.h2.command.dml.Query.query(Query.java:397) ~[?:?]
	at plan.org.h2.index.ViewIndex.find(ViewIndex.java:288) ~[?:?]
	at plan.org.h2.index.ViewIndex.find(ViewIndex.java:160) ~[?:?]
	at plan.org.h2.index.BaseIndex.find(BaseIndex.java:132) ~[?:?]
	at plan.org.h2.index.IndexCursor.find(IndexCursor.java:163) ~[?:?]
	at plan.org.h2.table.TableFilter.next(TableFilter.java:475) ~[?:?]
	at plan.org.h2.table.TableFilter.next(TableFilter.java:545) ~[?:?]
	at plan.org.h2.table.TableFilter.next(TableFilter.java:545) ~[?:?]
	at plan.org.h2.table.TableFilter.next(TableFilter.java:545) ~[?:?]
	at plan.org.h2.table.TableFilter.next(TableFilter.java:545) ~[?:?]
	at plan.org.h2.command.dml.Select$LazyResultQueryFlat.fetchNextRow(Select.java:1882) ~[?:?]
	at plan.org.h2.result.LazyResult.hasNext(LazyResult.java:101) ~[?:?]
	at plan.org.h2.result.LazyResult.next(LazyResult.java:60) ~[?:?]
	at plan.org.h2.command.dml.Select.queryFlat(Select.java:742) ~[?:?]
	at plan.org.h2.command.dml.Select.queryWithoutCache(Select.java:884) ~[?:?]
	at plan.org.h2.command.dml.Query.queryWithoutCacheLazyCheck(Query.java:151) ~[?:?]
	at plan.org.h2.command.dml.Query.query(Query.java:435) ~[?:?]
	at plan.org.h2.command.dml.Query.query(Query.java:397) ~[?:?]
	at plan.org.h2.command.CommandContainer.query(CommandContainer.java:145) ~[?:?]
	at plan.org.h2.command.Command.executeQuery(Command.java:202) ~[?:?]
	at plan.org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:115) ~[?:?]
	at com.djrapitops.plan.db.access.QueryStatement.executeQuery(QueryStatement.java:65) ~[?:?]
	at com.djrapitops.plan.db.access.QueryStatement.executeQuery(QueryStatement.java:52) ~[?:?]
	... 19 more
```

### Additional information

**Frequency of occurrence**: <>
After 10 minutes when I added a player to the white list.
**Other:**

**Comment by Rsl1122** [comment]
Thanks for the detailed error report!
I was able to reproduce the bug with a test so it should be fairly easy to get fixed :)
