### ISSUE TITLE
IllegalStateException: CapabilityService has not been initialised yet.

### ISSUE THREAD

**Issue by xXSchrandXx** [plan-player-analytics/Plan#1041]
### Describe the bug

Startup and Reload error:
```
[SEVERE] [Plan] Error was caught by com.djrapitops.plan.PlanBungee
java.lang.IllegalStateException: CapabilityService has not been initialised yet.
    at com.djrapitops.plan.capability.CapabilityService.lambda$getInstance$0(CapabilityService.java:43)
    at java.util.Optional.orElseThrow(Optional.java:290)
    at com.djrapitops.plan.capability.CapabilityService.getInstance(CapabilityService.java:43)
    at com.djrapitops.extension.AdvancedBanExtensionFactory.isAvailable(AdvancedBanExtensionFactory.java:40)
    at com.djrapitops.extension.AdvancedBanExtensionFactory.createExtension(AdvancedBanExtensionFactory.java:47)
    at com.djrapitops.plan.extension.implementation.ExtensionRegister.registerBuiltInExtensions(ExtensionRegister.java:45)
    at com.djrapitops.plan.extension.ExtensionServiceImplementation.enable(ExtensionServiceImplementation.java:84)
    at com.djrapitops.plan.system.PlanSystem.enable(PlanSystem.java:140)
    at com.djrapitops.plan.PlanBungee.onEnable(PlanBungee.java:47)
    at com.djrapitops.plugin.PluginCommon.reload(PluginCommon.java:43)
    at com.djrapitops.plugin.BungeePlugin.reloadPlugin(BungeePlugin.java:98)
    at com.djrapitops.plan.command.commands.ReloadCommand$1.run(ReloadCommand.java:66)
    at com.djrapitops.plugin.task.bungee.BungeeRunnableFactory$1.run(BungeeRunnableFactory.java:55)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

### Server information

Plan: 4.8.3
Bungee:
```
[INFO] This server is running RageBears - Minecraft version git:BungeeCord-Bootstrap:1.14-SNAPSHOT:f66995b:235 by md_5
[INFO] Protocol support for 1.7.x by Zartec, ghac and I9hdkill
```

### Additional information

I added some code in the HTMLs for my iFrame
``` PHP
<!--added in Body-->
onLoad="resizeParent();"

<script type="text/javascript">
  function resizeParent() {
    var height = document.getElementsByTagName("html")[0].scrollHeight;
    window.parent.postMessage(["setIframeHeight", height], "*");
  }
</script>
```

**Comment by valenvaio** [comment]
[05:57:35 WARN]: [Plan] Error was caught by com.djrapitops.plan.system.info.request.GenerateAnalysisPageRequest
com.djrapitops.plan.api.exceptions.connection.InternalErrorException: Analysis failed due to exception
        at com.djrapitops.plan.system.info.request.GenerateAnalysisPageRequest.analyseAndGetHtml(GenerateAnalysisPageRequest.java:130) ~[?:?]
        at com.djrapitops.plan.system.info.request.GenerateAnalysisPageRequest.generateAndCache(GenerateAnalysisPageRequest.java:113) ~[?:?]
        at com.djrapitops.plan.system.info.request.GenerateAnalysisPageRequest.lambda$null$1(GenerateAnalysisPageRequest.java:105) ~[?:?]
        at com.djrapitops.plan.system.info.connection.WebExceptionLogger.logIfOccurs(WebExceptionLogger.java:57) ~[?:?]
        at com.djrapitops.plan.system.info.request.GenerateAnalysisPageRequest.lambda$handleRequest$2(GenerateAnalysisPageRequest.java:105) ~[?:?]
        at com.djrapitops.plan.system.processing.Processing.lambda$submitNonCritical$0(Processing.java:73) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
        at java.util.HashMap.merge(HashMap.java:1225) ~[?:1.8.0_191]
        at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320) ~[?:1.8.0_191]
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:1.8.0_191]
        at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1625) ~[?:1.8.0_191]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_191]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_191]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_191]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_191]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_191]
        at com.djrapitops.plan.system.settings.config.ConfigNode.getStringMap(ConfigNode.java:278) ~[?:?]
        at com.djrapitops.plan.system.settings.config.WorldAliasSettings.getAliases(WorldAliasSettings.java:77) ~[?:?]
        at com.djrapitops.plan.system.settings.config.WorldAliasSettings.getPlaytimePerAlias(WorldAliasSettings.java:117) ~[?:?]
        at com.djrapitops.plan.utilities.html.graphs.pie.PieGraphFactory.worldPie(PieGraphFactory.java:64) ~[?:?]
        at com.djrapitops.plan.utilities.html.structure.SessionAccordion.addElementsForServer(SessionAccordion.java:126) ~[?:?]
        at com.djrapitops.plan.utilities.html.structure.SessionAccordion.addElements(SessionAccordion.java:105) ~[?:?]
        at com.djrapitops.plan.utilities.html.structure.SessionAccordion.<init>(SessionAccordion.java:94) ~[?:?]
        at com.djrapitops.plan.utilities.html.structure.Accordions.serverSessionAccordion(Accordions.java:107) ~[?:?]
        at com.djrapitops.plan.data.store.containers.AnalysisContainer.lambda$addSessionSuppliers$50(AnalysisContainer.java:307) ~[?:?]
        at com.djrapitops.plan.data.store.CachingSupplier.get(CachingSupplier.java:50) ~[?:?]
        at com.djrapitops.plan.data.store.containers.SupplierDataContainer.getUnsafe(SupplierDataContainer.java:106) ~[?:?]
        at com.djrapitops.plan.data.store.containers.DynamicDataContainer.getUnsafe(DynamicDataContainer.java:80) ~[?:?]
        at com.djrapitops.plan.data.store.containers.AnalysisContainer.lambda$addSessionSuppliers$51(AnalysisContainer.java:315) ~[?:?]
        at com.djrapitops.plan.data.store.containers.SupplierDataContainer.getValue(SupplierDataContainer.java:94) ~[?:?]
        at com.djrapitops.plan.data.store.containers.DynamicDataContainer.getValue(DynamicDataContainer.java:71) ~[?:?]
        at com.djrapitops.plan.utilities.formatting.PlaceholderReplacer.addPlaceholderFrom(PlaceholderReplacer.java:35) ~[?:?]
        at com.djrapitops.plan.utilities.formatting.PlaceholderReplacer.addAllPlaceholdersFrom(PlaceholderReplacer.java:40) ~[?:?]
        at com.djrapitops.plan.utilities.html.pages.AnalysisPage.sessionStructures(AnalysisPage.java:116) ~[?:?]
        at com.djrapitops.plan.utilities.html.pages.AnalysisPage.toHtml(AnalysisPage.java:89) ~[?:?]
        at com.djrapitops.plan.system.info.request.GenerateAnalysisPageRequest.analyseAndGetHtml(GenerateAnalysisPageRequest.java:128) ~[?:?]
        ... 9 more

**Comment by valenvaio** [comment]
4.8.3 
git-Akarin-"9c4d9da"

**Comment by Rsl1122** [comment]
@valenvalo This exception is unrelated to this issue, please open a new one.

Please include your `World_aliases` Plan config section in the issue.

**Comment by xXSchrandXx** [comment]
> Please include your `World_aliases` Plan config section in the issue.

Who do you mean 😄

**Comment by Rsl1122** [comment]
> 
> 
> > Please include your `World_aliases` Plan config section in the issue.
> 
> Who do you mean 😄

The full comment was aimed at @valenvaio
