### ISSUE TITLE
IllegalAccessError onEnable

### ISSUE THREAD

**Issue by SlimeDog** [plan-player-analytics/Plan#1064]
Spigot 1.14.2 (Jenkins 2239) git-Spigot-baafee9-043d31d (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)
Plan 4.8.5
HolographicDisplays 2.3.3-b73

Every second after start-up. I'm guessing that Spigot changed something on which Plan (or HolographicDisplays) relies, since it didn't happen with previous Spigot build and plugins have not changed. Please advise if this is a HolographicDisplays issue, and I will repost there.
```
[14:26:08] [Server thread/WARN]: [Plan] Task #95 for Plan v4.8.5 generated an exception
java.lang.IllegalAccessError: class com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.EntityNMSArmorStand tried to access private field net.minecraft.server.v1_14_R1.Entity.bukkitEntity (com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.EntityNMSArmorStand is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @781ca51a; net.minecraft.server.v1_14_R1.Entity is in unnamed module of loader 'app')
        at com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.EntityNMSArmorStand.getBukkitEntity(EntityNMSArmorStand.java:206) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.getEntities(CraftWorld.java:815) ~[spigot-1.14.2.jar-2019-06-02-1422:git-Spigot-baafee9-043d31d]
        at com.djrapitops.plan.system.tasks.bukkit.BukkitTPSCountTimer.getEntityCount(BukkitTPSCountTimer.java:150) ~[?:?]
        at com.djrapitops.plan.system.tasks.bukkit.BukkitTPSCountTimer.calculateTPS(BukkitTPSCountTimer.java:85) ~[?:?]
        at com.djrapitops.plan.system.tasks.bukkit.BukkitTPSCountTimer.addNewTPSEntry(BukkitTPSCountTimer.java:67) ~[?:?]
        at com.djrapitops.plan.system.tasks.TPSCountTimer.run(TPSCountTimer.java:71) ~[?:?]
        at com.djrapitops.plugin.task.bukkit.BukkitRunnableFactory$1.run(BukkitRunnableFactory.java:55) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.2.jar-2019-06-02-1422:git-Spigot-baafee9-043d31d]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.2.jar-2019-06-02-1422:git-Spigot-baafee9-043d31d]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1008) [spigot-1.14.2.jar-2019-06-02-1422:git-Spigot-baafee9-043d31d]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.2.jar-2019-06-02-1422:git-Spigot-baafee9-043d31d]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [spigot-1.14.2.jar-2019-06-02-1422:git-Spigot-baafee9-043d31d]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [spigot-1.14.2.jar-2019-06-02-1422:git-Spigot-baafee9-043d31d]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Rsl1122** [comment]
Yes  this is a holographic displays issue (I am unable to affect what bukkit does when it counts entities) 

No idea what the underlying problem is, I'm guessing NMS version mismatch

**Comment by SlimeDog** [comment]
Thanks. Posted an issue on HolographicDisplays.
