### ISSUE TITLE
MySQLIntegrityConstraintViolationException: Column 'geolocation' cannot be null

### ISSUE THREAD

**Issue by lukeeexd** [plan-player-analytics/Plan#1101]
### Describe the bug

```[23:55:08] [Plan MySQLDB-transaction-thread-0/ERROR]: [Plan] Error was caught by com.djrapitops.plan.db.MySQLDB
java.util.concurrent.CompletionException: com.djrapitops.plan.api.exceptions.database.DBOpException: GeoInfoStoreTransaction failed: SQL Failed: INSERT INTO plan_ips (uuid, ip, geolocation, last_used) VALUES (?, ?, ?, ?); Column 'geolocation' cannot be null, Transaction was rolled back.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_212]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_212]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592) ~[?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: com.djrapitops.plan.api.exceptions.database.DBOpException: GeoInfoStoreTransaction failed: SQL Failed: INSERT INTO plan_ips (uuid, ip, geolocation, last_used) VALUES (?, ?, ?, ?); Column 'geolocation' cannot be null, Transaction was rolled back.
	at com.djrapitops.plan.db.access.transactions.Transaction.manageFailure(Transaction.java:85) ~[?:?]
	at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:70) ~[?:?]
	at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:236) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_212]
	... 3 more
Caused by: com.djrapitops.plan.api.exceptions.database.DBOpException: SQL Failed: INSERT INTO plan_ips (uuid, ip, geolocation, last_used) VALUES (?, ?, ?, ?); Column 'geolocation' cannot be null
	at com.djrapitops.plan.api.exceptions.database.DBOpException.forCause(DBOpException.java:37) ~[?:?]
	at com.djrapitops.plan.db.access.ExecStatement.execute(ExecStatement.java:45) ~[?:?]
	at com.djrapitops.plan.db.access.queries.DataStoreQueries.lambda$storeGeoInfo$4(DataStoreQueries.java:156) ~[?:?]
	at com.djrapitops.plan.db.access.transactions.Transaction.execute(Transaction.java:119) ~[?:?]
	at com.djrapitops.plan.db.access.transactions.events.GeoInfoStoreTransaction.performOperations(GeoInfoStoreTransaction.java:80) ~[?:?]
	at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:66) ~[?:?]
	at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:236) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_212]
	... 3 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'geolocation' cannot be null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_212]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_212]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.14.3.jar:git-Paper-127]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[patched_1.14.3.jar:git-Paper-127]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936) ~[patched_1.14.3.jar:git-Paper-127]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[patched_1.14.3.jar:git-Paper-127]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[patched_1.14.3.jar:git-Paper-127]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[patched_1.14.3.jar:git-Paper-127]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[patched_1.14.3.jar:git-Paper-127]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[patched_1.14.3.jar:git-Paper-127]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[patched_1.14.3.jar:git-Paper-127]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[patched_1.14.3.jar:git-Paper-127]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[patched_1.14.3.jar:git-Paper-127]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[patched_1.14.3.jar:git-Paper-127]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[patched_1.14.3.jar:git-Paper-127]
	at plan.com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[?:?]
	at plan.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[?:?]
	at com.djrapitops.plan.db.access.ExecStatement.callExecute(ExecStatement.java:60) ~[?:?]
	at com.djrapitops.plan.db.access.ExecStatement.execute(ExecStatement.java:52) ~[?:?]
	at com.djrapitops.plan.db.access.ExecStatement.execute(ExecStatement.java:42) ~[?:?]
	at com.djrapitops.plan.db.access.queries.DataStoreQueries.lambda$storeGeoInfo$4(DataStoreQueries.java:156) ~[?:?]
	at com.djrapitops.plan.db.access.transactions.Transaction.execute(Transaction.java:119) ~[?:?]
	at com.djrapitops.plan.db.access.transactions.events.GeoInfoStoreTransaction.performOperations(GeoInfoStoreTransaction.java:80) ~[?:?]
	at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:66) ~[?:?]
	at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:236) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_212]
	at com.djrapitops.plan.db.SQLDB.executeTransaction(SQLDB.java:229) ~[?:?]
	at com.djrapitops.plan.system.listeners.bukkit.PlayerOnlineListener.actOnJoinEvent(PlayerOnlineListener.java:166) ~[?:?]
	at com.djrapitops.plan.system.listeners.bukkit.PlayerOnlineListener.onPlayerJoin(PlayerOnlineListener.java:138) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor268.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.3.jar:git-Paper-127]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.3.jar:git-Paper-127]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.3.jar:git-Paper-127]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[patched_1.14.3.jar:git-Paper-127]
	at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:191) ~[patched_1.14.3.jar:git-Paper-127]
	at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:169) ~[patched_1.14.3.jar:git-Paper-127]
	at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.14.3.jar:git-Paper-127]
	at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:270) ~[patched_1.14.3.jar:git-Paper-127]
	at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:129) ~[patched_1.14.3.jar:git-Paper-127]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1216) ~[patched_1.14.3.jar:git-Paper-127]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.3.jar:git-Paper-127]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064) ~[patched_1.14.3.jar:git-Paper-127]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.3.jar:git-Paper-127]
	... 1 more
```

### Server information
**Plan Version:** 4.8.6
**Server:** Paper 1.14.3-R0.1-SNAPSHOT (git-Paper-131 (MC: 1.14.3))
**Database:** MySQL

**Operating SubSystem:** Linux (amd64) version 4.15.0-52-generic
**Java Version:** 1.8.0_212, Oracle Corporation
**Java VM Version:** OpenJDK 64-Bit Server VM version 25.212-b03, Oracle Corporation

**Comment by Rsl1122** [comment]
Origin of null: https://github.com/maxmind/GeoIP2-java/blob/master/src/main/java/com/maxmind/geoip2/record/AbstractNamedRecord.java#L51

Looks like MaxMind GeoIP2 returns a null name for a country if the country name isn't found in any locale

----

I'll add a null check that gives "Not Known" as country instead.
