### ISSUE TITLE
Could not pass event PlayerViolationCommandEvent to Plan v4.8.8

### ISSUE THREAD

**Issue by FrozenBeard** [plan-player-analytics/Plan#1116]
Paper 1.12.2 - 1617
Plan v4.8.8

```
[11:35:48] [Server thread/ERROR]: Could not pass event PlayerViolationCommandEvent to Plan v4.8.8
java.lang.IllegalAccessError: tried to access method me.konsolas.aac.api.AACAPIProvider.<init>()V from class com.djrapitops.pluginbridge.plan.aac.PlayerHackKickListener
	at com.djrapitops.pluginbridge.plan.aac.PlayerHackKickListener.onKick(PlayerHackKickListener.java:55) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor935.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1617]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1617]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1617]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1617]
	at me.konsolas.aac.bS.a(bS.java:7) ~[?:?]
	at me.konsolas.aac.b4.run(b4.java:6) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1617]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1617]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

**Comment by Rsl1122** [comment]
Alright looks like issue in #1104 was reverted by konsolas and that causes my fix for the same issue to break.

You can prevent this error by setting `Plugins.AAC.Enabled` to `false`

**Comment by FrozenBeard** [comment]
As a heads up my AAC is Version 3.5.0, I will disable for now.
