### ISSUE TITLE
DataExtension methods are not disabled temporarily when they fail

### ISSUE THREAD

**Issue by Rsl1122** [plan-player-analytics/Plan#1118]
### Describe the bug

DataExtension method calls are supposed to be prevented if an error occurs, but insttead they are not removed always - And the update is attempted again indefinitely.
Leading to massive amount of spam if a server method for a DataExtension fails.

### Exceptions & Other Logs

```
[Plan] <PluginName> ran into IllegalArgumentException (but failed safely) when updating value for 'server', the method was disabled temporarily (won't be called until next Plan reload), stack trace to follow:
[16:42:42 WARN]: [Plan] Error was caught by com.djrapitops.plan.extension.ExtensionServiceImplementation
java.lang.IllegalArgumentException: class com.djrapitops.extension.ViaVersionExtension method protocolTable could not be called: null
	at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:86) ~[?:?]
	at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:65) ~[?:?]
	at com.djrapitops.plan.extension.implementation.providers.gathering.TableProviderValueGatherer.lambda$null$3(TableProviderValueGatherer.java:81) ~[?:?]
	at com.djrapitops.plan.extension.implementation.providers.gathering.TableProviderValueGatherer.getMethodResult(TableProviderValueGatherer.java:118) ~[?:?]
	at com.djrapitops.plan.extension.implementation.providers.gathering.TableProviderValueGatherer.gatherTableDataOfProvider(TableProviderValueGatherer.java:102) ~[?:?]
	at com.djrapitops.plan.extension.implementation.providers.gathering.TableProviderValueGatherer.gatherTableDataOfServer(TableProviderValueGatherer.java:85) ~[?:?]
	at com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer.updateValues(ProviderValueGatherer.java:139) ~[?:?]
	at com.djrapitops.plan.extension.ExtensionServiceImplementation.updateServerValues(ExtensionServiceImplementation.java:192) ~[?:?]
	at com.djrapitops.plan.extension.ExtensionServiceImplementation.updateServerValues(ExtensionServiceImplementation.java:199) ~[?:?]
	at com.djrapitops.plan.extension.ExtensionServiceImplementation.updateServerValues(ExtensionServiceImplementation.java:199) ~[?:?]
	at com.djrapitops.plan.extension.ExtensionServiceImplementation.updateServerValues(ExtensionServiceImplementation.java:199) ~[?:?]
	at com.djrapitops.plan.extension.ExtensionServiceImplementation.updateServerValues(ExtensionServiceImplementation.java:199) ~[?:?]
	at com.djrapitops.plan.extension.ExtensionServiceImplementation.updateServerValues(ExtensionServiceImplementation.java:199) ~[?:?]
	at com.djrapitops.plan.extension.ExtensionServiceImplementation.updateServerValues(ExtensionServiceImplementation.java:199) ~[?:?]
	at com.djrapitops.plan.extension.ExtensionServiceImplementation.updateServerValues(ExtensionServiceImplementation.java:199) ~[?:?]
	at com.djrapitops.plan.extension.ExtensionServiceImplementation.updateServerValues(ExtensionServiceImplementation.java:199) ~[?:?]
	at com.djrapitops.plan.extension.ExtensionServiceImplementation.updateServerValues(ExtensionServiceImplementation.java:199) ~[?:?]
	at com.djrapitops.plan.extension.ExtensionServiceImplementation.updateServerValues(ExtensionServiceImplementation.java:199) 
... continues for many lines
```

### Additional information

**Frequency of occurrence**: <>

**Other:**

**Comment by Rsl1122** [comment]
This is the likely cause of those 1.5 Gb error log files some people have experienced.
