### ISSUE TITLE
Error in the new 4.9.0 update

### ISSUE THREAD

**Issue by DrakePork** [plan-player-analytics/Plan#1121]
Basically from what I could get out of the error message below there's something wrong with the new nuvotifier extension that causes the database to disable itself.

The server is running 1.12.2, but I tested it on a 1.13.2 server and the error occured there too. The plugin version is 4.9.0. I have sqlite as database.

```
[global] Plan-v4.9.0
java.lang.IllegalArgumentException: BukkitNuVotifierExtension class had no methods annotated with a Provider annotation
at com.djrapitops.plan.extension.extractor.ExtensionExtractor.extractMethodAnnotations(ExtensionExtractor.java:112) ~[?:?]
at com.djrapitops.plan.extension.extractor.ExtensionExtractor.extractAnnotationInformation(ExtensionExtractor.java:83) ~[?:?]
at com.djrapitops.plan.extension.implementation.DataProviderExtractor.<init>(DataProviderExtractor.java:57) ~[?:?]
at com.djrapitops.plan.extension.ExtensionServiceImplementation.register(ExtensionServiceImplementation.java:92) ~[?:?]
at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_212]
at com.djrapitops.plan.extension.implementation.ExtensionRegister.registerBuiltInExtensions(ExtensionRegister.java:60) ~[?:?]
at com.djrapitops.plan.extension.ExtensionServiceImplementation.register(ExtensionServiceImplementation.java:85) ~[?:?]
at com.djrapitops.plan.system.PlanSystem.enable(PlanSystem.java:148) ~[?:?]
at com.djrapitops.plan.Plan.onEnable(Plan.java:54) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1618]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by Rsl1122** [comment]
Dang
