### ISSUE TITLE
CompletionException: com.djrapitops.plan.api.exceptions.database.DBOpException:  failed: SQL Failed

### ISSUE THREAD

**Issue by mibby** [plan-player-analytics/Plan#1137]
Paper dev 166 (Spigot 1.14.4)
Plan v4.9.2

nuVotifier plugin logging is off.
```
    nuVotifier:
        Enabled: false
```

```
[01:03:07] [Craft Scheduler Thread - 663/INFO]: [Plan] Removed data of 1 players.
[01:03:08] [Plan MySQLDB-transaction-thread-0/ERROR]: [Plan] Error was caught by com.djrapitops.plan.db.MySQLDB
java.util.concurrent.CompletionException: com.djrapitops.plan.api.exceptions.database.DBOpException:  failed: SQL Failed: REMOVE FROM plan_votes WHERE user_name=?; You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'REMOVE FROM plan_votes WHERE user_name='SageWolf'' at line 1, Transaction was rolled back.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_222]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_222]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592) ~[?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: com.djrapitops.plan.api.exceptions.database.DBOpException:  failed: SQL Failed: REMOVE FROM plan_votes WHERE user_name=?; You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'REMOVE FROM plan_votes WHERE user_name='SageWolf'' at line 1, Transaction was rolled back.
	at com.djrapitops.plan.db.access.transactions.Transaction.manageFailure(Transaction.java:85) ~[?:?]
	at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:70) ~[?:?]
	at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:236) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_222]
	... 3 more
Caused by: com.djrapitops.plan.api.exceptions.database.DBOpException: SQL Failed: REMOVE FROM plan_votes WHERE user_name=?; You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'REMOVE FROM plan_votes WHERE user_name='SageWolf'' at line 1
	at com.djrapitops.plan.api.exceptions.database.DBOpException.forCause(DBOpException.java:37) ~[?:?]
	at com.djrapitops.plan.db.access.QueryAPIExecutable.execute(QueryAPIExecutable.java:47) ~[?:?]
	at com.djrapitops.plan.db.access.transactions.Transaction.execute(Transaction.java:119) ~[?:?]
	at com.djrapitops.plan.query.QueryServiceImplementation$1.performOperations(QueryServiceImplementation.java:80) ~[?:?]
	at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:66) ~[?:?]
	at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:236) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_222]
	... 3 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'REMOVE FROM plan_votes WHERE user_name='SageWolf'' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_222]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_222]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_222]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_222]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.14.4.jar:git-Paper-166]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[patched_1.14.4.jar:git-Paper-166]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[patched_1.14.4.jar:git-Paper-166]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[patched_1.14.4.jar:git-Paper-166]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[patched_1.14.4.jar:git-Paper-166]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[patched_1.14.4.jar:git-Paper-166]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[patched_1.14.4.jar:git-Paper-166]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[patched_1.14.4.jar:git-Paper-166]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[patched_1.14.4.jar:git-Paper-166]
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1242) ~[patched_1.14.4.jar:git-Paper-166]
	at plan.com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[?:?]
	at plan.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[?:?]
	at com.djrapitops.extension.NuVotifierStorage.lambda$removePlayer$0(NuVotifierStorage.java:79) ~[?:?]
	at com.djrapitops.plan.db.access.QueryAPIExecutable.execute(QueryAPIExecutable.java:43) ~[?:?]
	at com.djrapitops.plan.db.access.transactions.Transaction.execute(Transaction.java:119) ~[?:?]
	at com.djrapitops.plan.query.QueryServiceImplementation$1.performOperations(QueryServiceImplementation.java:80) ~[?:?]
	at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:66) ~[?:?]
	at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:236) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_222]
	at com.djrapitops.plan.db.SQLDB.executeTransaction(SQLDB.java:229) ~[?:?]
	at com.djrapitops.plan.query.QueryServiceImplementation.execute(QueryServiceImplementation.java:76) ~[?:?]
	at com.djrapitops.extension.NuVotifierStorage.removePlayer(NuVotifierStorage.java:75) ~[?:?]
	at com.djrapitops.plan.query.QueryServiceImplementation.lambda$playerRemoved$0(QueryServiceImplementation.java:97) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_222]
	at com.djrapitops.plan.query.QueryServiceImplementation.playerRemoved(QueryServiceImplementation.java:97) ~[?:?]
	at com.djrapitops.plan.db.tasks.DBCleanTask.cleanOldPlayers(DBCleanTask.java:120) ~[?:?]
	at com.djrapitops.plan.db.tasks.DBCleanTask.run(DBCleanTask.java:102) ~[?:?]
	at com.djrapitops.plugin.task.bukkit.BukkitRunnableFactory$1.run(BukkitRunnableFactory.java:55) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-166]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-166]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-166]
	... 3 more
```

Another error.
https://paste.ubuntu.com/p/TFHR7JdTg5/

I did recently update my VotingPlugin to dev 278 which seems to have made some SQL changes in their API dependency, but not sure if related.

https://github.com/Ben12345rocks/AdvancedCore/commit/067c937b309e60e7c2293a0394e5d620a5a7a215
https://github.com/Ben12345rocks/AdvancedCore/commit/828db4d502323a80c102d34d4aa5a6cd1cf79133

**Comment by Rsl1122** [comment]
This is completely my fault, there is no such thing as `REMOVE` in SQL. Proper SQL would be `DELETE`
