### ISSUE TITLE
Red Protect Error (?)

### ISSUE THREAD

**Issue by robertdrakedennis** [plan-player-analytics/Plan#1167]
### Describe the issue

No serious effects yet? Seems to be some sort of issue with redprotect: https://ore.spongepowered.org/FabioZumbi12/RedProtect

### Server information

Pterodactyl for host
SpongeForge Version: 1.12.2-2838-7.1.7-RC3924
Forge Version: 14.23.5.2838
Plan Version:

### Exceptions & Other Logs

https://ptero.co/igukimerih.sql

<details>
<summary>Exception (Rsl's edit)</summary>

```
[05:44:52] [pool-3-thread-5/WARN] [plan]: Encountered IllegalArgumentException with RedProtect Extension (please report this) (failed safely) when updating value for 'server', the method was disabled temporarily (won't be called until next Plan reload), stack trace to follow:
[05:44:52] [pool-3-thread-5/WARN] [plan]: Error was caught by com.djrapitops.plan.extension.ExtensionServiceImplementation
java.lang.IllegalArgumentException: class com.djrapitops.extension.RedProtectBukkitExtension method regionTable could not be called: null
	at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:85) ~[MethodWrapper.class:?]
	at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:64) ~[MethodWrapper.class:?]
	at com.djrapitops.plan.extension.implementation.providers.gathering.TableProviderValueGatherer.lambda$null$3(TableProviderValueGatherer.java:81) ~[TableProviderValueGatherer.class:?]
	at com.djrapitops.plan.extension.implementation.providers.gathering.TableProviderValueGatherer.getMethodResult(TableProviderValueGatherer.java:118) ~[TableProviderValueGatherer.class:?]
	at com.djrapitops.plan.extension.implementation.providers.gathering.TableProviderValueGatherer.gatherTableDataOfProvider(TableProviderValueGatherer.java:102) ~[TableProviderValueGatherer.class:?]
	at com.djrapitops.plan.extension.implementation.providers.gathering.TableProviderValueGatherer.gatherTableDataOfServer(TableProviderValueGatherer.java:85) ~[TableProviderValueGatherer.class:?]
	at com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer.updateValues(ProviderValueGatherer.java:139) ~[ProviderValueGatherer.class:?]
	at com.djrapitops.plan.extension.ExtensionServiceImplementation.updateServerValues(ExtensionServiceImplementation.java:194) ~[ExtensionServiceImplementation.class:?]
	at com.djrapitops.plan.extension.ExtensionServiceImplementation.updateServerValues(ExtensionServiceImplementation.java:183) ~[ExtensionServiceImplementation.class:?]
	at com.djrapitops.plan.extension.ExtensionServerMethodCallerTask.run(ExtensionServerMethodCallerTask.java:41) ~[ExtensionServerMethodCallerTask.class:?]
	at com.djrapitops.plugin.task.sponge.SpongeRunnableFactory$1.run(SpongeRunnableFactory.java:57) ~[SpongeRunnableFactory$1.class:?]
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2838-7.1.7-RC3924]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:192) ~[SchedulerBase.class:1.12.2-2838-7.1.7-RC3924]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:71) ~[MethodWrapper.class:?]
	... 17 more
Caused by: java.lang.NoClassDefFoundError: br/net/fabiozumbi12/RedProtect/Bukkit/RedProtect
	at com.djrapitops.extension.RedProtectBukkitExtension.regionTable(RedProtectBukkitExtension.java:79) ~[RedProtectBukkitExtension.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:71) ~[MethodWrapper.class:?]
	... 17 more
Caused by: java.lang.ClassNotFoundException: br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
	at com.djrapitops.extension.RedProtectBukkitExtension.regionTable(RedProtectBukkitExtension.java:79) ~[RedProtectBukkitExtension.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:71) ~[MethodWrapper.class:?]
	... 17 more
```

</details>

**Comment by Rsl1122** [comment]
Bug identified: https://github.com/plan-player-analytics/Extension-RedProtect/blob/master/src/main/java/com/djrapitops/extension/RedProtectExtensionFactory.java#L51

Solution: Change class checks to better account for the platform in use
