### ISSUE TITLE
Plan SQL Error

### ISSUE THREAD

**Issue by Hrubin2020** [plan-player-analytics/Plan#1170]
### Describe the issue

Plan throws an SQL error upon loading up.

### Server information

Spigot 1.12.2
Plan-5.0.RC.build.196

### Exceptions & Other Logs

```[08:21:01] [Plan SQLiteDB-transaction-thread-1/ERROR] [com.djrapitops.plan.Plan]: [Plan] Error was caught by com.djrapitops.plan.storage.database.SQLiteDB
java.util.concurrent.CompletionException: com.djrapitops.plan.exceptions.database.DBOpException: RemoveInvalidResultsTransaction failed: SQL Failed: DELETE FROM plan_extension_tables WHERE plan_extension_tables=? AND plugin_id=(SELECT id FROM plan_extension_plugins WHERE name=? AND server_uuid=?); [SQLITE_ERROR] SQL error or missing database (no such column: plan_extension_tables), Transaction was rolled back.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_222]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) [?:1.8.0_222]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: com.djrapitops.plan.exceptions.database.DBOpException: RemoveInvalidResultsTransaction failed: SQL Failed: DELETE FROM plan_extension_tables WHERE plan_extension_tables=? AND plugin_id=(SELECT id FROM plan_extension_plugins WHERE name=? AND server_uuid=?); [SQLITE_ERROR] SQL error or missing database (no such column: plan_extension_tables), Transaction was rolled back.
	at com.djrapitops.plan.storage.database.transactions.Transaction.manageFailure(Transaction.java:87) ~[?:?]
	at com.djrapitops.plan.storage.database.transactions.Transaction.executeTransaction(Transaction.java:69) ~[?:?]
	at com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$2(SQLDB.java:243) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_222]
	... 3 more
Caused by: com.djrapitops.plan.exceptions.database.DBOpException: SQL Failed: DELETE FROM plan_extension_tables WHERE plan_extension_tables=? AND plugin_id=(SELECT id FROM plan_extension_plugins WHERE name=? AND server_uuid=?); [SQLITE_ERROR] SQL error or missing database (no such column: plan_extension_tables)
	at com.djrapitops.plan.exceptions.database.DBOpException.forCause(DBOpException.java:37) ~[?:?]
	at com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:45) ~[?:?]
	at com.djrapitops.plan.storage.database.transactions.Transaction.execute(Transaction.java:140) ~[?:?]
	at com.djrapitops.plan.extension.implementation.storage.transactions.results.RemoveInvalidResultsTransaction.performOperations(RemoveInvalidResultsTransaction.java:57) ~[?:?]
	at com.djrapitops.plan.storage.database.transactions.Transaction.executeTransaction(Transaction.java:65) ~[?:?]
	at com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$2(SQLDB.java:243) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_222]
	... 3 more
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such column: plan_extension_tables)
	at org.sqlite.core.DB.newSQLException(DB.java:909) ~[DB.class:?]
	at org.sqlite.core.DB.newSQLException(DB.java:921) ~[DB.class:?]
	at org.sqlite.core.DB.throwex(DB.java:886) ~[DB.class:?]
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method) ~[NativeDB.class:?]
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:127) ~[NativeDB.class:?]
	at org.sqlite.core.DB.prepare(DB.java:227) ~[DB.class:?]
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:41) ~[CorePreparedStatement.class:?]
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30) ~[JDBC3PreparedStatement.class:?]
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19) ~[JDBC4PreparedStatement.class:?]
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:48) ~[JDBC4Connection.class:?]
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:263) ~[JDBC3Connection.class:?]
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:235) ~[JDBC3Connection.class:?]
	at com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:41) ~[?:?]
	at com.djrapitops.plan.storage.database.transactions.Transaction.execute(Transaction.java:140) ~[?:?]
	at com.djrapitops.plan.extension.implementation.storage.transactions.results.RemoveInvalidResultsTransaction.performOperations(RemoveInvalidResultsTransaction.java:57) ~[?:?]
	at com.djrapitops.plan.storage.database.transactions.Transaction.executeTransaction(Transaction.java:65) ~[?:?]
	at com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$2(SQLDB.java:243) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_222]
	at com.djrapitops.plan.storage.database.SQLDB.executeTransaction(SQLDB.java:236) ~[?:?]
	at com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer.storeExtensionInformation(ProviderValueGatherer.java:127) ~[?:?]
	at com.djrapitops.plan.extension.ExtensionServiceImplementation.register(ExtensionServiceImplementation.java:106) ~[?:?]
	at com.djrapitops.plan.extension.implementation.ExtensionRegister.register(ExtensionRegister.java:139) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_222]
	at com.djrapitops.plan.extension.implementation.ExtensionRegister.register(ExtensionRegister.java:108) ~[?:?]
	at com.djrapitops.plan.extension.implementation.ExtensionRegister.registerBuiltInExtensions(ExtensionRegister.java:60) ~[?:?]
	at com.djrapitops.plan.extension.ExtensionServiceImplementation.register(ExtensionServiceImplementation.java:87) ~[?:?]
	at com.djrapitops.plan.PlanSystem.enable(PlanSystem.java:176) ~[?:?]
	at com.djrapitops.plan.Plan.onEnable(Plan.java:53) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-master-a187670]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) ~[JavaPluginLoader.class:git-master-a187670]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) ~[SimplePluginManager.class:git-master-a187670]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:435) ~[CraftServer.class:git-master-a187670]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[CraftServer.class:git-master-a187670]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:394) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:324) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:621) ~[MinecraftServer.class:?]
	... 1 more```

**Comment by Rsl1122** [comment]
Fixed in build 200
https://plan.djrapitops.com/job/Player%20Analytics/job/development/
