### ISSUE TITLE
BukkitNetworkPlayerColorSetEvent error

### ISSUE THREAD

**Issue by DrakePork** [plan-player-analytics/Plan#1176]
### Describe the issue
Everytime a player leaves or joins I get a Could not pass event BukkitNetworkPlayerColorSetEvent to Plan

### Server information

Server Version: 1.14.4, Paper v207
Plan Version: 5.0, Build 224

### Exceptions & Other Logs
[Pastebin](https://pastebin.com/GyjATzqq)

**Comment by Rsl1122** [comment]
Alright, looks like a bug in one of the new extensions, you can prevent the exception by setting `Plugins.DKBans.Enabled` to `false`

**Comment by Rsl1122** [comment]
<details>
<summary>The reported Exception</summary>

```
Could not pass event BukkitNetworkPlayerColorSetEvent to Plan v5.0 build 224
java.lang.IllegalArgumentException: 'playerUUID' can not be null!
at com.djrapitops.plan.extension.implementation.CallerImplementation.lambda$updatePlayerData$0(CallerImplementation.java:51) ~[?:?]
at com.djrapitops.plugin.utilities.Verify.nullCheck(Verify.java:277) ~[?:?]
at com.djrapitops.plan.extension.implementation.CallerImplementation.updatePlayerData(CallerImplementation.java:51) ~[?:?]
at com.djrapitops.extension.DKBansBukkitDKBListener.onPlayerEvent(DKBansBukkitDKBListener.java:51) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor694.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-207]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.14.4.jar:git-Paper-207]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-207]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-207]
at ch.dkrieger.bansystem.bukkit.BukkitBanSystemBootstrap.getColor(BukkitBanSystemBootstrap.java:178) ~[?:?]
at ch.dkrieger.bansystem.bukkit.listener.BukkitPlayerListener.lambda$onDisconnect$2(BukkitPlayerListener.java:135) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-207]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-207]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-207]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

</details>

**Comment by Rsl1122** [comment]
Fixed in build 229
https://plan.djrapitops.com/job/Player%20Analytics/job/master/

**Comment by Rsl1122** [comment]
Sorry wrong issue 🤦‍♂
