### ISSUE TITLE
Export does not export players

### ISSUE THREAD

**Issue by TripleNothing** [plan-player-analytics/Plan#1200]
### Describe the issue
'player' folder never gets created. External web. BungeeCord provided errors. Spigot stayed clean. It references the database fine. The values appear, so I'm guessing a reference wrong.

`com.djrapitops.plan.exceptions.connection.BadRequestException: Given 'player' was not found in the database: '7150d7f4-6b34-4fde-b051-a1d39c43cf7d'`

[Plan's Errors.txt](http://minecraft.hellzoneinc.com/player-analytics/Errors-2019_10_20.txt)
The defined player appears to exist...
[DB users](http://minecraft.hellzoneinc.com/player-analytics/users.png)
[DB user_info](http://minecraft.hellzoneinc.com/player-analytics/user_info.png)

As a rough test, I enabled and trigger it from within Spigot(Paper) and it created the 'json' info, but errored as well with 'player'

### Server information
Ubuntu 18.04 LTS
BungeeCord Build 1421 (Most recent at this moment)
PaperSpigot 1.14.4 Build 221 (Most recent at this moment)
Player Analytics 5.0 Build 249 (Most recent at this moment)

**Comment by Rsl1122** [comment]
Related exception (Suspected cause):
```
[Plan] Error was caught by com.djrapitops.plan.processing.Processing
java.lang.IllegalStateException: Unexpected exception thrown: com.djrapitops.plan.exceptions.connection.BadRequestException: Given 'player' was not found in the database: '<some uuid>'
	at com.djrapitops.plan.delivery.export.PlayerPageExporter.getJSONResponse(PlayerPageExporter.java:130) ~[?:?]
	at com.djrapitops.plan.delivery.export.PlayerPageExporter.exportJSON(PlayerPageExporter.java:110) ~[?:?]
	at com.djrapitops.plan.delivery.export.PlayerPageExporter.exportJSON(PlayerPageExporter.java:106) ~[?:?]
	at com.djrapitops.plan.delivery.export.PlayerPageExporter.export(PlayerPageExporter.java:90) ~[?:?]
	at com.djrapitops.plan.delivery.export.Exporter.exportPlayerPage(Exporter.java:145) ~[?:?]
	at com.djrapitops.plan.commands.subcommands.manage.ManageExportCommand.performExport(ManageExportCommand.java:162) ~[?:?]
	at com.djrapitops.plan.commands.subcommands.manage.ManageExportCommand.lambda$exportPlayers$3(ManageExportCommand.java:148) ~[?:?]
	at com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:78) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_221]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: com.djrapitops.plan.exceptions.connection.BadRequestException: Given 'player' was not found in the database: 'f3cc3e96-1bc9-35ad-994f-d894e9764b93'
	at com.djrapitops.plan.identification.Identifiers.lambda$getPlayerUUIDFromName$3(Identifiers.java:71) ~[?:?]
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:1.8.0_221]
	at com.djrapitops.plan.identification.Identifiers.getPlayerUUIDFromName(Identifiers.java:71) ~[?:?]
	at com.djrapitops.plan.identification.Identifiers.getPlayerUUID(Identifiers.java:65) ~[?:?]
	at com.djrapitops.plan.delivery.webserver.pages.json.PlayerJSONHandler.getResponse(PlayerJSONHandler.java:49) ~[?:?]
	at com.djrapitops.plan.delivery.webserver.pages.TreePageHandler$1.getResponse(TreePageHandler.java:54) ~[?:?]
	at com.djrapitops.plan.delivery.webserver.pages.TreePageHandler.getResponse(TreePageHandler.java:81) ~[?:?]
	at com.djrapitops.plan.delivery.export.PlayerPageExporter.getJSONResponse(PlayerPageExporter.java:127) ~[?:?]
	... 11 more
```
