### ISSUE TITLE
IllegalArgumentException with latest LuckPerms/ExtraContexts

### ISSUE THREAD

**Issue by SlimeDog** [plan-player-analytics/Plan#1236]
### Describe the issue
On server start-up, new version of LuckPerm ExtraContexts doesn't play well.
```
[13:29:32] [Server thread/INFO]: [Plan] Registered extension: LuckPerms
[13:29:32] [Plan Non critical-pool-4/WARN]: [Plan] Encountered IllegalArgumentException with LuckPerms Extension (failed safely) when updating value for 'server', the method was disabled temporarily (won't be called until next Plan reload), stack trace to follow (please report this):
[13:29:32] [Plan Non critical-pool-4/WARN]: [Plan] Error was caught by com.djrapitops.plan.extension.ExtensionServiceImplementation
java.lang.IllegalArgumentException: class com.djrapitops.extension.LuckPermsExtension method tracks could not be called: null
        at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:85) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:64) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.gathering.TableProviderValueGatherer.lambda$null$3(TableProviderValueGatherer.java:81) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.gathering.TableProviderValueGatherer.getMethodResult(TableProviderValueGatherer.java:118) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.gathering.TableProviderValueGatherer.gatherTableDataOfProvider(TableProviderValueGatherer.java:102) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.gathering.TableProviderValueGatherer.gatherTableDataOfServer(TableProviderValueGatherer.java:85) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer.updateValues(ProviderValueGatherer.java:144) ~[?:?]
        at com.djrapitops.plan.extension.ExtensionServiceImplementation.updateServerValues(ExtensionServiceImplementation.java:198) ~[?:?]
        at com.djrapitops.plan.extension.ExtensionServiceImplementation.lambda$register$0(ExtensionServiceImplementation.java:109) ~[?:?]
        at com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:78) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:71) ~[?:?]
        ... 13 more
Caused by: java.lang.NoSuchMethodError: net.luckperms.api.track.Track.getSize()I
        at me.lucko.luckperms.extension.legacyapi.impl.track.TrackProxy.getSize(TrackProxy.java:42) ~[?:?]
        at com.djrapitops.extension.LuckPermsExtension.lambda$tracks$5(LuckPermsExtension.java:196) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at com.djrapitops.extension.LuckPermsExtension.tracks(LuckPermsExtension.java:196) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:71) ~[?:?]
        ... 13 more
```

### Server information
Spigot 1.14.4 (Jenkins 2494)
Plan 5.0-b288
LuckPerms 5.0.6-b928
ExtraContexts 1.0-b12

**Comment by SlimeDog** [comment]
Confirmed fixed in b292.
