### ISSUE TITLE
Improve ErrorLog.txt situation

### ISSUE THREAD

**Issue by Rsl1122** [plan-player-analytics/Plan#1246]
### Is your feature request related to a problem? Please describe.

Errors are currently logged to quite unreadable exception logs. Better logging would be beneficial. See #510 for previous fix attempt.

### I would like to be able to..

One idea would be to hash stacktraces and save one log per error (and somehow count their frequency) so that no duplicate errors would be logged.

**Comment by Rsl1122** [comment]
Refined idea with an example:

What shows up on console:
```
[14-05-2020 10:21][WARN]: Ran into IllegalArgumentException - logged to /plugins/Plan/logs/java.lang.IllegalArgumentException-a01658ba.txt.
[14-05-2020 10:21][WARN]: (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[14-05-2020 10:21][WARN]: What to do: Report error and/or disable BuyCraftExtension in Plan config
```
if instructions on what to do are not present:
```
[14-05-2020 10:21][WARN]: Ran into IllegalArgumentException - logged to /plugins/Plan/logs/java.lang.IllegalArgumentException-a01658ba.txt.
[14-05-2020 10:21][WARN]: (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[14-05-2020 10:21][WARN]: Error msg: "class com.djrapitops.extension.BuycraftExtension method purchaseTable could not be called: null"
```

Filename: `java.lang.IllegalArgumentException-a01658ba.txt`

File contents:
```
Last occurred: 14-05-2020 10:21, Occurrences: 43
-----  Context -----
Plan version: 5.1 build 483
Server: Paper 1.15.2

1: BuyCraftExtension
    gathering for Server
2: BuyCraftExtension
    gathering for Server
3: BuyCraftExtension
    gathering for Server
4: BuyCraftExtension
    gathering for Server
5: BuyCraftExtension
    gathering for Server
---- Stacktrace ----
java.lang.IllegalArgumentException: class com.djrapitops.extension.BuycraftExtension method purchaseTable could not be called: null
        at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:51) ~[Plan-5.1-build-505.jar:?]
        at com.djrapitops.plan.extension.implementation.providers.gathering.TableProviderValueGatherer.lambda$null$3(TableProviderValueGatherer.java:82) ~[Plan-5.1-build-505.jar:?]
        at com.djrapitops.plan.extension.implementation.providers.gathering.TableProviderValueGatherer.getMethodResult(TableProviderValueGatherer.java:119) ~[Plan-5.1-build-505.jar:?]
        at com.djrapitops.plan.extension.implementation.providers.gathering.TableProviderValueGatherer.gatherTableDataOfProvider(TableProviderValueGatherer.java:103) ~[Plan-5.1-build-505.jar:?]
        at com.djrapitops.plan.extension.implementation.providers.gathering.TableProviderValueGatherer.gatherTableDataOfServer(TableProviderValueGatherer.java:86) ~[Plan-5.1-build-505.jar:?]
        at com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer.updateValues(ProviderValueGatherer.java:162) ~[Plan-5.1-build-505.jar:?]
        at com.djrapitops.plan.extension.ExtensionSvc.updateServerValues(ExtensionSvc.java:200) [Plan-5.1-build-505.jar:?]
        at com.djrapitops.plan.extension.ExtensionSvc.updateServerValues(ExtensionSvc.java:187) [Plan-5.1-build-505.jar:?]
        at com.djrapitops.plan.extension.ExtensionServerMethodCallerTask.run(ExtensionServerMethodCallerTask.java:41) [Plan-5.1-build-505.jar:?]
        at com.djrapitops.plugin.task.bukkit.BukkitRunnableFactory$1.run(BukkitRunnableFactory.java:55) [Plan-5.1-build-505.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
        at com.djrapitops.plan.extension.implementation.providers.Parameters$ServerParameters.usingOn(Parameters.java:63) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:46) ~[?:?]
        ... 14 more
Caused by: java.lang.IllegalStateException: IOException occurred
        at com.djrapitops.extension.ListPaymentRequest.makeRequest(ListPaymentRequest.java:82) ~[?:?]
        at com.djrapitops.extension.BuycraftExtension.purchaseTable(BuycraftExtension.java:72) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
        at com.djrapitops.plan.extension.implementation.providers.Parameters$ServerParameters.usingOn(Parameters.java:63) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:46) ~[?:?]
        ... 14 more
Caused by: java.io.IOException: Server returned HTTP response code: 504 for URL: https://plugin.tebex.io/payments
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900) ~[?:1.8.0_252]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498) ~[?:1.8.0_252]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268) ~[?:1.8.0_252]
        at com.djrapitops.extension.ListPaymentRequest.makeRequest(ListPaymentRequest.java:64) ~[?:?]
        at com.djrapitops.extension.BuycraftExtension.purchaseTable(BuycraftExtension.java:72) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
        at com.djrapitops.plan.extension.implementation.providers.Parameters$ServerParameters.usingOn(Parameters.java:63) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:46) ~[?:?]
        ... 14 more
```
----

How this would work:
- The error logger is given a Context that is created using a Builder. The context is used to write the instructions on the console and extra information on the error log.
- Context can include any objects that might help debugging the situation and toString is called on them to log into the file.
- Error log only keeps 5 context instances in case the error happens in the hundreds to avoid too large files
- The `ErrorHanlder` interface currently in use is extended and use of the current interface is phased out slowly.
