### ISSUE TITLE
The length of "weapon" is too short in PvP records, causing failed SQL operations

### ISSUE THREAD

**Issue by database64128** [plan-player-analytics/Plan#1272]
### Describe the issue

When a player is killed by a weapon that has a long name, like Draconic Evolution's Draconic Staff of Power `draconicevolution:draconic_staff_of_power`, an error is thrown indicating a failed SQL operation. The kill is not shown in the recent kills list.

### Server information

Minecraft: 1.12.2
Forge: 2847
SpongeForge: 7.1.7 RC3928
Plan: 5.0 build 335

### Exceptions & Other Logs

```
[03:00:37] [Plan MySQLDB-transaction-thread-1/ERROR] [plan]: Error was caught by com.djrapitops.plan.storage.database.MySQLDB
java.util.concurrent.CompletionException: com.djrapitops.plan.exceptions.database.DBOpException: SQL Failed: INSERT INTO plan_kills (session_id,killer_uuid,victim_uuid,server_uuid,date,weapon) VALUES ((SELECT plan_sessions.id FROM plan_sessions WHERE plan_sessions.uuid=? AND plan_sessions.server_uuid=? AND session_start=? AND session_end=? LIMIT 1), ?, ?, ?, ?, ?); (conn:10089) Data too long for column 'weapon' at row 2
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_232]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) [?:1.8.0_232]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: com.djrapitops.plan.exceptions.database.DBOpException: SQL Failed: INSERT INTO plan_kills (session_id,killer_uuid,victim_uuid,server_uuid,date,weapon) VALUES ((SELECT plan_sessions.id FROM plan_sessions WHERE plan_sessions.uuid=? AND plan_sessions.server_uuid=? AND session_start=? AND session_end=? LIMIT 1), ?, ?, ?, ?, ?); (conn:10089) Data too long for column 'weapon' at row 2
	at com.djrapitops.plan.exceptions.database.DBOpException.forCause(DBOpException.java:37) ~[DBOpException.class:?]
	at com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:45) ~[ExecStatement.class:?]
	at com.djrapitops.plan.storage.database.queries.DataStoreQueries.lambda$storeSession$1(DataStoreQueries.java:56) ~[DataStoreQueries.class:?]
	at com.djrapitops.plan.storage.database.transactions.Transaction.execute(Transaction.java:170) ~[Transaction.class:?]
	at com.djrapitops.plan.storage.database.transactions.events.SessionEndTransaction.performOperations(SessionEndTransaction.java:41) ~[SessionEndTransaction.class:?]
	at com.djrapitops.plan.storage.database.transactions.Transaction.executeTransaction(Transaction.java:72) ~[Transaction.class:?]
	at com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$2(SQLDB.java:245) ~[SQLDB.class:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_232]
	... 3 more
Caused by: java.sql.BatchUpdateException: (conn:10089) Data too long for column 'weapon' at row 2
	at org.mariadb.jdbc.MariaDbStatement.executeBatchExceptionEpilogue(MariaDbStatement.java:296) ~[MariaDbStatement.class:1.12.2-2838-7.1.7-RC3928]
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeBatch(MariaDbPreparedStatementClient.java:290) ~[MariaDbPreparedStatementClient.class:1.12.2-2838-7.1.7-RC3928]
	at plan.com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[ProxyStatement.class:?]
	at plan.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[HikariProxyPreparedStatement.class:?]
	at com.djrapitops.plan.storage.database.transactions.ExecBatchStatement.callExecute(ExecBatchStatement.java:35) ~[ExecBatchStatement.class:?]
	at com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:52) ~[ExecStatement.class:?]
	at com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:42) ~[ExecStatement.class:?]
	at com.djrapitops.plan.storage.database.queries.DataStoreQueries.lambda$storeSession$1(DataStoreQueries.java:56) ~[DataStoreQueries.class:?]
	at com.djrapitops.plan.storage.database.transactions.Transaction.execute(Transaction.java:170) ~[Transaction.class:?]
	at com.djrapitops.plan.storage.database.transactions.events.SessionEndTransaction.performOperations(SessionEndTransaction.java:41) ~[SessionEndTransaction.class:?]
	at com.djrapitops.plan.storage.database.transactions.Transaction.executeTransaction(Transaction.java:72) ~[Transaction.class:?]
	at com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$2(SQLDB.java:245) ~[SQLDB.class:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_232]
	... 3 more
Caused by: java.sql.SQLDataException: (conn:10089) Data too long for column 'weapon' at row 2
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148) ~[ExceptionMapper.class:1.12.2-2838-7.1.7-RC3928]
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118) ~[ExceptionMapper.class:1.12.2-2838-7.1.7-RC3928]
	at org.mariadb.jdbc.MariaDbStatement.executeBatchExceptionEpilogue(MariaDbStatement.java:293) ~[MariaDbStatement.class:1.12.2-2838-7.1.7-RC3928]
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeBatch(MariaDbPreparedStatementClient.java:290) ~[MariaDbPreparedStatementClient.class:1.12.2-2838-7.1.7-RC3928]
	at plan.com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[ProxyStatement.class:?]
	at plan.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[HikariProxyPreparedStatement.class:?]
	at com.djrapitops.plan.storage.database.transactions.ExecBatchStatement.callExecute(ExecBatchStatement.java:35) ~[ExecBatchStatement.class:?]
	at com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:52) ~[ExecStatement.class:?]
	at com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:42) ~[ExecStatement.class:?]
	at com.djrapitops.plan.storage.database.queries.DataStoreQueries.lambda$storeSession$1(DataStoreQueries.java:56) ~[DataStoreQueries.class:?]
	at com.djrapitops.plan.storage.database.transactions.Transaction.execute(Transaction.java:170) ~[Transaction.class:?]
	at com.djrapitops.plan.storage.database.transactions.events.SessionEndTransaction.performOperations(SessionEndTransaction.java:41) ~[SessionEndTransaction.class:?]
	at com.djrapitops.plan.storage.database.transactions.Transaction.executeTransaction(Transaction.java:72) ~[Transaction.class:?]
	at com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$2(SQLDB.java:245) ~[SQLDB.class:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_232]
	... 3 more
Caused by: java.sql.SQLException: Data too long for column 'weapon' at row 2
Query is: INSERT INTO plan_kills (session_id,killer_uuid,victim_uuid,server_uuid,date,weapon) VALUES ((SELECT plan_sessions.id FROM plan_sessions WHERE plan_sessions.uuid=? AND plan_sessions.server_uuid=? AND session_start=? AND session_end=? LIMIT 1), ?, ?, ?, ?, ?)
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:168) ~[LogQueryTool.class:1.12.2-2838-7.1.7-RC3928]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeBatchRewrite(AbstractQueryProtocol.java:544) ~[AbstractQueryProtocol.class:1.12.2-2838-7.1.7-RC3928]
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternalBatch(MariaDbPreparedStatementClient.java:349) ~[MariaDbPreparedStatementClient.class:1.12.2-2838-7.1.7-RC3928]
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeBatch(MariaDbPreparedStatementClient.java:282) ~[MariaDbPreparedStatementClient.class:1.12.2-2838-7.1.7-RC3928]
	at plan.com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[ProxyStatement.class:?]
	at plan.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[HikariProxyPreparedStatement.class:?]
	at com.djrapitops.plan.storage.database.transactions.ExecBatchStatement.callExecute(ExecBatchStatement.java:35) ~[ExecBatchStatement.class:?]
	at com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:52) ~[ExecStatement.class:?]
	at com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:42) ~[ExecStatement.class:?]
	at com.djrapitops.plan.storage.database.queries.DataStoreQueries.lambda$storeSession$1(DataStoreQueries.java:56) ~[DataStoreQueries.class:?]
	at com.djrapitops.plan.storage.database.transactions.Transaction.execute(Transaction.java:170) ~[Transaction.class:?]
	at com.djrapitops.plan.storage.database.transactions.events.SessionEndTransaction.performOperations(SessionEndTransaction.java:41) ~[SessionEndTransaction.class:?]
	at com.djrapitops.plan.storage.database.transactions.Transaction.executeTransaction(Transaction.java:72) ~[Transaction.class:?]
	at com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$2(SQLDB.java:245) ~[SQLDB.class:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_232]
	at com.djrapitops.plan.storage.database.SQLDB.executeTransaction(SQLDB.java:238) ~[SQLDB.class:?]
	at com.djrapitops.plan.gathering.listeners.sponge.PlayerOnlineListener.lambda$actOnQuitEvent$9(PlayerOnlineListener.java:232) ~[PlayerOnlineListener.class:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_232]
	at com.djrapitops.plan.gathering.listeners.sponge.PlayerOnlineListener.actOnQuitEvent(PlayerOnlineListener.java:232) ~[PlayerOnlineListener.class:?]
	at com.djrapitops.plan.gathering.listeners.sponge.PlayerOnlineListener.onQuit(PlayerOnlineListener.java:209) ~[PlayerOnlineListener.class:?]
	at org.spongepowered.common.event.listener.DisconnectListener_PlayerOnlineListener_onQuit182.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2838-7.1.7-RC3928]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:381) ~[SpongeModEventManager.class:1.12.2-2838-7.1.7-RC3928]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:345) ~[SpongeModEventManager.class:1.12.2-2838-7.1.7-RC3928]
	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:446) ~[SpongeModEventManager.class:1.12.2-2838-7.1.7-RC3928]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:415) ~[SpongeModEventManager.class:1.12.2-2838-7.1.7-RC3928]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:465) ~[SpongeEventManager.class:1.12.2-2838-7.1.7-RC3928]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:247) ~[SpongeImpl.class:1.12.2-2838-7.1.7-RC3928]
	at net.minecraft.network.NetHandlerPlayServer.redirect$onDisconnectHandler$zih000(NetHandlerPlayServer.java:2921) ~[pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.onDisconnect(NetHandlerPlayServer.java:851) ~[pa.class:?]
	at net.minecraft.network.NetworkManager.handleDisconnection(NetworkManager.java:453) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:213) ~[oz.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) ~[MinecraftServer.class:?]
	... 1 more
```

### Additional information

The error is not thrown right after the kill. In this case, it was thrown after the killer logged out.

**Comment by Rsl1122** [comment]
Looks like something that was not really thought about (of course mods can add items with very long names) - I'll add some code that truncate the weapon item name to fit the length.

If you're running only a single Sponge server (doesn't work for networks) you can move to using SQLite with `plan m move mysql sqlite` - SQLite doesn't limit the varchar column length.

Alternative temporary fix is changing `plan_kills.weapon` column to have a larger varchar field (Can be done with an `ALTER TABLE` sql statement)
