### ISSUE TITLE
Nukkit error

### ISSUE THREAD

**Issue by imjack** [plan-player-analytics/Plan#1307]
### Describe the issue

This error happens when someone attempts to log in (not signed in using Xbox live) the error prints then: USERNAME[/IP ADRESS] logged out due to disconnectionScreen.notAuthenticated

### Server information

Nukkit version: This server is running Nukkit git-f79eb4f 「」 implementing API version 1.0.9 for Minecraft: BE v1.14.0 (protocol version 389)
Plan verison: Plan v5.0 build 367

### Exceptions & Other Logs

```
23:32:28 [ERROR] [Plan] Error was caught by com.djrapitops.plan.storage.database.H2DB
java.util.concurrent.CompletionException: java.lang.NullPointerException
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_212]
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) [?:1.8.0_212]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
at com.djrapitops.plan.storage.database.transactions.events.BanStatusTransaction$1.prepare(BanStatusTransaction.java:59) ~[?:?]
at com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:51) ~[?:?]
at com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:42) ~[?:?]
at com.djrapitops.plan.storage.database.transactions.Transaction.execute(Transaction.java:170) ~[?:?]
at com.djrapitops.plan.storage.database.transactions.events.BanStatusTransaction.performOperations(BanStatusTransaction.java:47) ~[?:?]
at com.djrapitops.plan.storage.database.transactions.Transaction.executeTransaction(Transaction.java:72) ~[?:?]
at com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$2(SQLDB.java:245) ~[?:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_212]
at com.djrapitops.plan.storage.database.SQLDB.executeTransaction(SQLDB.java:238) ~[?:?]
at com.djrapitops.plan.gathering.listeners.nukkit.PlayerOnlineListener.actOnQuitEvent(PlayerOnlineListener.java:222) ~[?:?]
at com.djrapitops.plan.gathering.listeners.nukkit.PlayerOnlineListener.onPlayerQuit(PlayerOnlineListener.java:203) ~[?:?]
at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[server.jar:?]
at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[server.jar:?]
at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) ~[server.jar:?]
at cn.nukkit.Player.close(Player.java:3560) ~[server.jar:?]
at cn.nukkit.Player.close(Player.java:3538) ~[server.jar:?]
at cn.nukkit.Player.close(Player.java:3534) ~[server.jar:?]
at cn.nukkit.Player.handleDataPacket(Player.java:2118) ~[server.jar:?]
at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_212]
at cn.nukkit.network.Network.processPackets(Network.java:203) ~[server.jar:?]
at cn.nukkit.network.Network.processBatch(Network.java:186) ~[server.jar:?]
at cn.nukkit.Player.handleDataPacket(Player.java:2069) ~[server.jar:?]
at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:76) ~[server.jar:?]
at cn.nukkit.network.Network.processInterfaces(Network.java:87) ~[server.jar:?]
at cn.nukkit.Server.tick(Server.java:1139) ~[server.jar:?]
at cn.nukkit.Server.tickProcessor(Server.java:919) ~[server.jar:?]
at cn.nukkit.Server.start(Server.java:887) ~[server.jar:?]
at cn.nukkit.Server.<init>(Server.java:568) ~[server.jar:?]
at cn.nukkit.Nukkit.main(Nukkit.java:119) ~[server.jar:?]
```

**Comment by Rsl1122** [comment]
Didn't expect player UUID to be null, which causes this issue.
