### ISSUE TITLE
Vault economy error

### ISSUE THREAD

**Issue by Rsl1122** [plan-player-analytics/Plan#1331]
### Describe the issue

Reported on Discord

### Exceptions & Other Logs

```
[19:09:49 WARN]: [Plan] Encountered IllegalArgumentException with Economy (Vault) Extension (failed safely) when updating value for 'SuperMarty2005', the method was disabled temporarily (won't be called until next Plan reload), stack trace to follow (please report this):
[19:09:49 WARN]: [Plan] Error was caught by com.djrapitops.plan.extension.ExtensionServiceImplementation
java.lang.IllegalArgumentException: class com.djrapitops.extension.VaultExtension method balance could not be called: null
        at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:85) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:50) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.gathering.DoubleAndPercentageProviderValueGatherer.lambda$null$0(DoubleAndPercentageProviderValueGatherer.java:70) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.gathering.DoubleAndPercentageProviderValueGatherer.getMethodResult(DoubleAndPercentageProviderValueGatherer.java:122) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.gathering.DoubleAndPercentageProviderValueGatherer.gatherDoubleDataOfProvider(DoubleAndPercentageProviderValueGatherer.java:105) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.gathering.DoubleAndPercentageProviderValueGatherer.gatherDoubleDataOfPlayer(DoubleAndPercentageProviderValueGatherer.java:75) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer.updateValues(ProviderValueGatherer.java:133) ~[?:?]
        at com.djrapitops.plan.extension.ExtensionServiceImplementation.updatePlayerValues(ExtensionServiceImplementation.java:157) ~[?:?]
        at com.djrapitops.plan.extension.ExtensionServiceImplementation.updatePlayerValues(ExtensionServiceImplementation.java:146) ~[?:?]
        at com.djrapitops.plan.gathering.listeners.bukkit.PlayerOnlineListener.lambda$beforePlayerQuit$5(PlayerOnlineListener.java:200) ~[?:?]
        at com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:78) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
        at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:73) ~[?:?]
        ... 14 more
Caused by: java.lang.RuntimeException: Economy username cannot be null
        at com.earth2me.essentials.api.Economy.getUserByName(Economy.java:66) ~[?:?]
        at com.earth2me.essentials.api.Economy.getMoneyExact(Economy.java:110) ~[?:?]
        at com.earth2me.essentials.api.Economy.getMoney(Economy.java:99) ~[?:?]
        at net.milkbowl.vault.economy.plugins.Economy_Essentials.getBalance(Economy_Essentials.java:79) ~[?:?]
        at net.milkbowl.vault.economy.AbstractEconomy.getBalance(AbstractEconomy.java:20) ~[?:?]
        at com.djrapitops.extension.VaultExtension.balance(VaultExtension.java:57) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
        at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:73) ~[?:?]
        ... 14 more
>
```

**Comment by lukeeexd** [comment]
He's using essx https://i.tws.gg/tlVOa5R20S.png
