### ISSUE TITLE
WARN messages with BSkyBlock extension

### ISSUE THREAD

**Issue by SlimeDog** [plan-player-analytics/Plan#1332]
### Describe the issue
Various WARN messages related to BSkyBlock extension

### Server information
Spigot 1.15.2 (Jenkins 2628)
BentoBox versions as below
Plan 5.0-b410

### Exceptions & Other Logs
On player connect
```
[07:49:42] [Plan Non critical-pool-4/WARN]: [Plan] Encountered unexpected error with BSkyBlock Extension: java.lang.IllegalArgumentException: class com.djrapitops.extension.BentoBoxExtension method islandLevel could not be called: null (but failed safely) when updating value for 'rambeau', stack trace to follow (please report this):
[07:49:42] [Plan Non critical-pool-4/WARN]: [Plan] Error was caught by com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer
java.lang.IllegalArgumentException: class com.djrapitops.extension.BentoBoxExtension method islandLevel could not be called: null
        at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:51) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer$Gatherer.gather(ProviderValueGatherer.java:193) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer$Gatherer.gather(ProviderValueGatherer.java:183) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer.updateValues(ProviderValueGatherer.java:148) ~[?:?]
        at com.djrapitops.plan.extension.ExtensionServiceImplementation.updatePlayerValues(ExtensionServiceImplementation.java:157) ~[?:?]
        at com.djrapitops.plan.extension.ExtensionServiceImplementation.updatePlayerValues(ExtensionServiceImplementation.java:146) ~[?:?]
        at com.djrapitops.plan.gathering.listeners.bukkit.PlayerOnlineListener.lambda$actOnJoinEvent$3(PlayerOnlineListener.java:189) ~[?:?]
        at com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:78) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.Parameters$PlayerParameters.usingOn(Parameters.java:95) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:46) ~[?:?]
        ... 11 more
Caused by: java.lang.IllegalArgumentException: The validated object is null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-1.15.2.jar-2020-02-12-1651:git-Spigot-c574e08-37f32da]
        at org.apache.commons.lang.Validate.notNull(Validate.java:178) ~[spigot-1.15.2.jar-2020-02-12-1651:git-Spigot-c574e08-37f32da]
        at world.bentobox.bentobox.api.addons.request.AddonRequestBuilder.request(AddonRequestBuilder.java:63) ~[?:?]
        at com.djrapitops.extension.BentoBoxExtension.islandLevel(BentoBoxExtension.java:147) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.Parameters$PlayerParameters.usingOn(Parameters.java:95) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:46) ~[?:?]
        ... 11 more
```
On player disconnect
```
[08:02:32] [Plan Non critical-pool-5/WARN]: [Plan] Encountered unexpected error with BSkyBlock Extension: java.lang.IllegalArgumentException: class com.djrapitops.extension.BentoBoxExtension method islandLevel could not be called: null (but failed safely) when updating value for 'rambeau', stack trace to follow (please report this):
[08:02:32] [Plan Non critical-pool-5/WARN]: [Plan] Error was caught by com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer
java.lang.IllegalArgumentException: class com.djrapitops.extension.BentoBoxExtension method islandLevel could not be called: null
        at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:51) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer$Gatherer.gather(ProviderValueGatherer.java:193) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer$Gatherer.gather(ProviderValueGatherer.java:183) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer.updateValues(ProviderValueGatherer.java:148) ~[?:?]
        at com.djrapitops.plan.extension.ExtensionServiceImplementation.updatePlayerValues(ExtensionServiceImplementation.java:157) ~[?:?]
        at com.djrapitops.plan.extension.ExtensionServiceImplementation.updatePlayerValues(ExtensionServiceImplementation.java:146) ~[?:?]
        at com.djrapitops.plan.gathering.listeners.bukkit.PlayerOnlineListener.lambda$beforePlayerQuit$5(PlayerOnlineListener.java:200) ~[?:?]
        at com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:78) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.Parameters$PlayerParameters.usingOn(Parameters.java:95) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:46) ~[?:?]
        ... 11 more
Caused by: java.lang.IllegalArgumentException: The validated object is null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-1.15.2.jar-2020-02-12-1651:git-Spigot-c574e08-37f32da]
        at org.apache.commons.lang.Validate.notNull(Validate.java:178) ~[spigot-1.15.2.jar-2020-02-12-1651:git-Spigot-c574e08-37f32da]
        at world.bentobox.bentobox.api.addons.request.AddonRequestBuilder.request(AddonRequestBuilder.java:63) ~[?:?]
        at com.djrapitops.extension.BentoBoxExtension.islandLevel(BentoBoxExtension.java:147) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.Parameters$PlayerParameters.usingOn(Parameters.java:95) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:46) ~[?:?]
        ... 11 more
```

**Comment by Rsl1122** [comment]
Looks like I didn't call `label` method on the AddOnRequestBuilder

**Comment by SlimeDog** [comment]
Confirmed fixed in build 415. Thanks.
