### ISSUE TITLE
Plan started before LiteBans and caused an error.

### ISSUE THREAD

**Issue by momoservertw** [plan-player-analytics/Plan#1335]
### Describe the issue

Plan started before LiteBans and caused an error.

### Server information

BungeeCord version git:BungeeCord-Bootstrap:1.15-SNAPSHOT:e6b0d43:1479

### Exceptions & Other Logs

```
20:26:23 [警告] [Plan] One or more extensions failed to register, see suppressed exceptions (They can be disabled in Plan config).
20:26:23 [警告] [Plan] Error was caught by com.djrapitops.plan.extension.ExtensionService
java.lang.IllegalStateException: One or more extensions failed to register:
    Suppressed: java.lang.IllegalStateException: LitebansExtensionFactory failed to create Extension
    Caused by: litebans.api.exception.MissingImplementationException: LiteBans API implementation is not available! This means that LiteBans is not installed on this server or it hasn't been loaded yet.
        at litebans.api.Events.get(Events.java:1)
        at com.djrapitops.extension.LitebansExtension.registerEvents(LitebansExtension.java:65)
        at com.djrapitops.extension.LitebansExtensionFactory.registerEvents(LitebansExtensionFactory.java:54)
        at com.djrapitops.plan.extension.implementation.ExtensionRegister.lambda$register$0(ExtensionRegister.java:173)
        at java.util.Optional.ifPresent(Unknown Source)
        at com.djrapitops.plan.extension.implementation.ExtensionRegister.register(ExtensionRegister.java:173)
        at com.djrapitops.plan.extension.implementation.ExtensionRegister.registerBuiltInExtensions(ExtensionRegister.java:77)
        at com.djrapitops.plan.extension.ExtensionServiceImplementation.register(ExtensionServiceImplementation.java:87)
        at com.djrapitops.plan.PlanSystem.enable(PlanSystem.java:180)
        at com.djrapitops.plan.PlanBungee.onEnable(PlanBungee.java:46)
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:280)
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
20:26:23 [資訊] [Plan] Player Analytics Enabled.
```

**Comment by Rsl1122** [comment]
What name does litebans have in the bungee enable log?

**Comment by austin4195** [comment]
Seeing this error as well and can submit a log if needed

**Comment by Rsl1122** [comment]
Looks like it says `[LiteBans]` in the logs.

This unfortunately means that Bungee is enabling the plugins in the "wrong" order (because LiteBans is a softdependency in [`bungee.yml`](https://github.com/plan-player-analytics/Plan/blob/master/Plan/common/src/main/resources/bungee.yml#L7)).

I can move the extension registration to after all plugins have started.

**Comment by austin4195** [comment]
I was about to say that it just looks like Plan is "jumping the gun" and not waiting leading to this error.

**Comment by Rsl1122** [comment]
It's unfortunate that Bungee sometimes ignores the dependency order for some reason. I've had many reports about it (not necessarily related to LiteBans integration).

It is down to luck with the plugin mix you have, as many servers don't have any issues while others do (My test server for example doesn't run into this exception)

**Comment by austin4195** [comment]
This is the error I see

[15:40:43 WARN] [Plan]: One or more extensions failed to register, see suppressed exceptions (They can be disabled in Plan config).
[15:40:43 WARN] [Plan]: Error was caught by com.djrapitops.plan.extension.ExtensionService
java.lang.IllegalStateException: One or more extensions failed to register:
Suppressed: java.lang.IllegalStateException: LitebansExtensionFactory failed to create Extension
Caused by: litebans.api.exception.MissingImplementationException: LiteBans API implementation is not available! This means that LiteBans is not installed on this server or it hasn't been loaded yet.
at litebans.api.Events.get(Events.java:1) ~[?:?]
at com.djrapitops.extension.LitebansExtension.registerEvents(LitebansExtension.java:65) ~[?:?]
at com.djrapitops.extension.LitebansExtensionFactory.registerEvents(LitebansExtensionFactory.java:54) ~[?:?]
at com.djrapitops.plan.extension.implementation.ExtensionRegister.lambda$register$0(ExtensionRegister.java:173) ~[?:?]
at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_212]
at com.djrapitops.plan.extension.implementation.ExtensionRegister.register(ExtensionRegister.java:173) ~[?:?]
at com.djrapitops.plan.extension.implementation.ExtensionRegister.registerBuiltInExtensions(ExtensionRegister.java:77) ~[?:?]
at com.djrapitops.plan.extension.ExtensionServiceImplementation.register(ExtensionServiceImplementation.java:87) ~[?:?]
at com.djrapitops.plan.PlanSystem.enable(PlanSystem.java:180) ~[?:?]
at com.djrapitops.plan.PlanBungee.onEnable(PlanBungee.java:46) ~[?:?]
at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:285) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:ea7863f:319]
at net.md_5.bungee.BungeeCord.start(BungeeCord.java:282) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:ea7863f:319]
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:ea7863f:319]
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:ea7863f:319]

**Comment by austin4195** [comment]
Issue not resolved after Build 415 Release

**Comment by Rsl1122** [comment]
Please post the new stacktrace

**Comment by austin4195** [comment]
```
[11:22:44 WARN] [Plan]: One or more extensions failed to register, see suppressed exceptions (They can be disabled in Plan config).
[11:22:44 WARN] [Plan]: Error was caught by com.djrapitops.plan.extension.ExtensionService
java.lang.IllegalStateException: One or more extensions failed to register:
Suppressed: java.lang.IllegalStateException: LitebansExtensionFactory failed to create Extension
Caused by: litebans.api.exception.MissingImplementationException: LiteBans API implementation is not available! This means that LiteBans is not installed on this server or it hasn't been loaded yet.
at litebans.api.Events.get(Events.java:1) ~[?:?]
at com.djrapitops.extension.LitebansExtension.registerEvents(LitebansExtension.java:65) ~[?:?]
at com.djrapitops.extension.LitebansExtensionFactory.registerEvents(LitebansExtensionFactory.java:54) ~[?:?]
at com.djrapitops.plan.extension.implementation.ExtensionRegister.lambda$register$0(ExtensionRegister.java:173) ~[?:?]
at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_212]
at com.djrapitops.plan.extension.implementation.ExtensionRegister.register(ExtensionRegister.java:173) ~[?:?]
at com.djrapitops.plan.extension.implementation.ExtensionRegister.registerBuiltInExtensions(ExtensionRegister.java:77) ~[?:?]
at com.djrapitops.plan.extension.ExtensionServiceImplementation.register(ExtensionServiceImplementation.java:87) ~[?:?]
at com.djrapitops.plan.PlanSystem$1.run(PlanSystem.java:189) ~[?:?]
at com.djrapitops.plugin.task.bungee.BungeeRunnableFactory$1.run(BungeeRunnableFactory.java:55) ~[?:?]
at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:ea7863f:319]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by Rsl1122** [comment]
Looks like it's not possible to fix it then.

**Comment by Rsl1122** [comment]
Try updating Bungee to newest version.

If that doesn't work, could you send a plugin list and bungee version so that I can open an issue on Bungee issue tracker for enable order issue

**Comment by austin4195** [comment]
Currently Running Waterfall Build 323 (Latest for Waterfall but appears to be based on Build 1479 of BungeeCord)

Plugins:
Bungeecord Party and Friends
BuycraftX
LiteAnnouncer
LiteBans
LuckPerms 5.0.72
Maintenance
NuVotifier
Plan v5 Build 415
SlashServer

**Comment by Rsl1122** [comment]
I have opened an issue on BungeeCord issue tracker.
