### ISSUE TITLE
Essentials Extension totalServerBalance

### ISSUE THREAD

**Issue by austin4195** [plan-player-analytics/Plan#1336]
### Describe the issue
Error appears periodically saying that the Essentials Extension has failed to collect the totalServerBalance.

### Server information
Server Version: Paper 1.8.8 Build 443
Plan Version: 5.0 build 410

### Exceptions & Other Logs

```
[00:49:27] [Craft Scheduler Thread - 1179/WARN]: [Plan] Encountered unexpected error with Essentials Extension: java.lang.IllegalArgumentException: class com.djrapitops.extension.EssentialsExtension method totalServerBalance could not be called: null (failed safely) when updating value for server, stack trace to follow (please report this):
[00:49:27] [Craft Scheduler Thread - 1179/WARN]: [Plan] Error was caught by com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer
java.lang.IllegalArgumentException: class com.djrapitops.extension.EssentialsExtension method totalServerBalance could not be called: null
	at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:51) ~[Plan-5.0-build-410.jar:?]
	at com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer$Gatherer.gather(ProviderValueGatherer.java:193) ~[Plan-5.0-build-410.jar:?]
	at com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer$Gatherer.gather(ProviderValueGatherer.java:183) ~[Plan-5.0-build-410.jar:?]
	at com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer.updateValues(ProviderValueGatherer.java:160) ~[Plan-5.0-build-410.jar:?]
	at com.djrapitops.plan.extension.ExtensionServiceImplementation.updateServerValues(ExtensionServiceImplementation.java:198) [Plan-5.0-build-410.jar:?]
	at com.djrapitops.plan.extension.ExtensionServiceImplementation.updateServerValues(ExtensionServiceImplementation.java:185) [Plan-5.0-build-410.jar:?]
	at com.djrapitops.plan.extension.ExtensionServerMethodCallerTask.run(ExtensionServerMethodCallerTask.java:41) [Plan-5.0-build-410.jar:?]
	at com.djrapitops.plugin.task.bukkit.BukkitRunnableFactory$1.run(BukkitRunnableFactory.java:55) [Plan-5.0-build-410.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at com.djrapitops.plan.extension.implementation.providers.Parameters$ServerParameters.usingOn(Parameters.java:63) ~[Plan-5.0-build-410.jar:?]
	at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:46) ~[Plan-5.0-build-410.jar:?]
	... 13 more
Caused by: java.lang.NoSuchMethodError: net.ess3.api.ISettings.isNpcsInBalanceRanking()Z
	at com.djrapitops.extension.EssentialsExtension.totalServerBalance(EssentialsExtension.java:156) ~[Plan-5.0-build-410.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at com.djrapitops.plan.extension.implementation.providers.Parameters$ServerParameters.usingOn(Parameters.java:63) ~[Plan-5.0-build-410.jar:?]
	at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:46) ~[Plan-5.0-build-410.jar:?]
	... 13 more
```

### Additional information
N/A

**Comment by Rsl1122** [comment]
I remember someone having this issue earlier, but I can't find the issue/discussion.

Try updating EssentialsX to a newer version https://www.spigotmc.org/resources/essentialsx.9089/

**Comment by Rsl1122** [comment]
Closing this as this is occurs due to older version of Essentials than the one that is supported.
As you stated you can prevent this error by disabling the Essentials integration in the Plan config.
