### ISSUE TITLE
ConcurrentModificationException in ExtensionServiceImplementation

### ISSUE THREAD

**Issue by Vankka** [plan-player-analytics/Plan#1348]
### Describe the issue

```
[Plan] Error was caught by com.djrapitops.plan.processing.Processing
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_221]
        at java.util.HashMap$ValueIterator.next(HashMap.java:1474) ~[?:1.8.0_221]
        at com.djrapitops.plan.extension.ExtensionServiceImplementation.updatePlayerValues(ExtensionServiceImplementation.java:145) ~[?:?]
        at com.djrapitops.plan.gathering.listeners.bukkit.PlayerOnlineListener.lambda$actOnJoinEvent$3(PlayerOnlineListener.java:189) ~[?:?]
        at com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:78) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_221]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
```

Line throwing exception: https://github.com/plan-player-analytics/Plan/blob/274bd2755b8f4b372b96912dee08e4ded6da16b7/Plan/common/src/main/java/com/djrapitops/plan/extension/ExtensionServiceImplementation.java#L145

Cause (non-concurrent map): https://github.com/plan-player-analytics/Plan/blob/274bd2755b8f4b372b96912dee08e4ded6da16b7/Plan/common/src/main/java/com/djrapitops/plan/extension/ExtensionServiceImplementation.java#L80

### Server information

Plan Version: 5.0 build 415

### Exceptions & Other Logs

n/a

### Additional information

n/a

**Comment by Rsl1122** [comment]
Likely cause: 4e8f509ebcd54ae52746ca0c7cf075559a18cc29
- Two tasks doing things at the same time, one registering the extensions and one gathering the values already.

Commit in question was reverted in 36579cfcd03ae0ba0a566b07250e9cb4c16a65ba (Latest commit on `master`)
