### ISSUE TITLE
Unhandled deadlock during rollback

### ISSUE THREAD

**Issue by poqdavid** [plan-player-analytics/Plan#1383]
### Describe the issue
unhandled rollback in the deadlock

### Server information
spongeforge-1.12.2-2825-7.1.6
Plan-5.1-build-486

### Exceptions & Other Logs
https://hastebin.com/avolecohet.txt

**Comment by Rsl1122** [comment]
<details>
<summary>Stacktrace</summary>

```
[04:17:12] [Plan MySQLDB-transaction-thread-1/ERROR] [plan]: Error was caught by com.djrapitops.plan.storage.database.MySQLDB
java.util.concurrent.CompletionException: com.djrapitops.plan.exceptions.database.DBOpException: SQL Failed: UPDATE plan_extension_user_values SET long_value=? WHERE uuid=? AND provider_id=(SELECT id FROM plan_extension_providers WHERE name=? AND plugin_id=(SELECT id FROM plan_extension_plugins WHERE name=? AND server_uuid=? LIMIT 1) LIMIT 1); (conn:576982) Deadlock found when trying to get lock; try restarting transaction
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_242]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) [?:1.8.0_242]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: com.djrapitops.plan.exceptions.database.DBOpException: SQL Failed: UPDATE plan_extension_user_values SET long_value=? WHERE uuid=? AND provider_id=(SELECT id FROM plan_extension_providers WHERE name=? AND plugin_id=(SELECT id FROM plan_extension_plugins WHERE name=? AND server_uuid=? LIMIT 1) LIMIT 1); (conn:576982) Deadlock found when trying to get lock; try restarting transaction
	at com.djrapitops.plan.exceptions.database.DBOpException.forCause(DBOpException.java:37) ~[DBOpException.class:?]
	at com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:45) ~[ExecStatement.class:?]
	at com.djrapitops.plan.extension.implementation.storage.transactions.results.StorePlayerNumberResultTransaction.lambda$storeValue$0(StorePlayerNumberResultTransaction.java:63) ~[StorePlayerNumberResultTransaction.class:?]
	at com.djrapitops.plan.storage.database.transactions.Transaction.execute(Transaction.java:170) ~[Transaction.class:?]
	at com.djrapitops.plan.extension.implementation.storage.transactions.results.StorePlayerNumberResultTransaction.performOperations(StorePlayerNumberResultTransaction.java:58) ~[StorePlayerNumberResultTransaction.class:?]
	at com.djrapitops.plan.storage.database.transactions.Transaction.executeTransaction(Transaction.java:72) ~[Transaction.class:?]
	at com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$2(SQLDB.java:246) ~[SQLDB.class:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_242]
	... 3 more
Caused by: java.sql.SQLTransactionRollbackException: (conn:576982) Deadlock found when trying to get lock; try restarting transaction
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:160) ~[ExceptionMapper.class:1.12.2-2825-7.1.6]
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118) ~[ExceptionMapper.class:1.12.2-2825-7.1.6]
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:245) ~[MariaDbStatement.class:1.12.2-2825-7.1.6]
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:218) ~[MariaDbPreparedStatementClient.class:1.12.2-2825-7.1.6]
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:153) ~[MariaDbPreparedStatementClient.class:1.12.2-2825-7.1.6]
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeUpdate(MariaDbPreparedStatementClient.java:186) ~[MariaDbPreparedStatementClient.class:1.12.2-2825-7.1.6]
	at plan.com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[ProxyPreparedStatement.class:?]
	at plan.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariProxyPreparedStatement.class:?]
	at com.djrapitops.plan.storage.database.transactions.ExecStatement.callExecute(ExecStatement.java:60) ~[ExecStatement.class:?]
	at com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:52) ~[ExecStatement.class:?]
	at com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:42) ~[ExecStatement.class:?]
	at com.djrapitops.plan.extension.implementation.storage.transactions.results.StorePlayerNumberResultTransaction.lambda$storeValue$0(StorePlayerNumberResultTransaction.java:63) ~[StorePlayerNumberResultTransaction.class:?]
	at com.djrapitops.plan.storage.database.transactions.Transaction.execute(Transaction.java:170) ~[Transaction.class:?]
	at com.djrapitops.plan.extension.implementation.storage.transactions.results.StorePlayerNumberResultTransaction.performOperations(StorePlayerNumberResultTransaction.java:58) ~[StorePlayerNumberResultTransaction.class:?]
	at com.djrapitops.plan.storage.database.transactions.Transaction.executeTransaction(Transaction.java:72) ~[Transaction.class:?]
	at com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$2(SQLDB.java:246) ~[SQLDB.class:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_242]
	... 3 more
Caused by: java.sql.SQLException: Deadlock found when trying to get lock; try restarting transaction
Query is: UPDATE plan_extension_user_values SET long_value=? WHERE uuid=? AND provider_id=(SELECT id FROM plan_extension_providers WHERE name=? AND plugin_id=(SELECT id FROM plan_extension_plugins WHERE name=? AND server_uuid=? LIMIT 1) LIMIT 1), parameters [1260,'9e525eb3-68e3-4681-800a-d1c149d1c423','votes','nuVotifier','6e4547b9-b154-4e9a-b009-c6fc4286dbd4']
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:146) ~[LogQueryTool.class:1.12.2-2825-7.1.6]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:223) ~[AbstractQueryProtocol.class:1.12.2-2825-7.1.6]
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:212) ~[MariaDbPreparedStatementClient.class:1.12.2-2825-7.1.6]
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:153) ~[MariaDbPreparedStatementClient.class:1.12.2-2825-7.1.6]
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeUpdate(MariaDbPreparedStatementClient.java:186) ~[MariaDbPreparedStatementClient.class:1.12.2-2825-7.1.6]
	at plan.com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[ProxyPreparedStatement.class:?]
	at plan.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariProxyPreparedStatement.class:?]
	at com.djrapitops.plan.storage.database.transactions.ExecStatement.callExecute(ExecStatement.java:60) ~[ExecStatement.class:?]
	at com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:52) ~[ExecStatement.class:?]
	at com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:42) ~[ExecStatement.class:?]
	at com.djrapitops.plan.extension.implementation.storage.transactions.results.StorePlayerNumberResultTransaction.lambda$storeValue$0(StorePlayerNumberResultTransaction.java:63) ~[StorePlayerNumberResultTransaction.class:?]
	at com.djrapitops.plan.storage.database.transactions.Transaction.execute(Transaction.java:170) ~[Transaction.class:?]
	at com.djrapitops.plan.extension.implementation.storage.transactions.results.StorePlayerNumberResultTransaction.performOperations(StorePlayerNumberResultTransaction.java:58) ~[StorePlayerNumberResultTransaction.class:?]
	at com.djrapitops.plan.storage.database.transactions.Transaction.executeTransaction(Transaction.java:72) ~[Transaction.class:?]
	at com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$2(SQLDB.java:246) ~[SQLDB.class:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_242]
	at com.djrapitops.plan.storage.database.SQLDB.executeTransaction(SQLDB.java:239) ~[SQLDB.class:?]
	at com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer$Gatherer.gather(ProviderValueGatherer.java:201) ~[ProviderValueGatherer$Gatherer.class:?]
	at com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer$Gatherer.gather(ProviderValueGatherer.java:183) ~[ProviderValueGatherer$Gatherer.class:?]
	at com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer.updateValues(ProviderValueGatherer.java:148) ~[ProviderValueGatherer.class:?]
	at com.djrapitops.plan.extension.ExtensionSvc.updatePlayerValues(ExtensionSvc.java:159) ~[ExtensionSvc.class:?]
	at com.djrapitops.plan.extension.ExtensionSvc.updatePlayerValues(ExtensionSvc.java:148) ~[ExtensionSvc.class:?]
	at com.djrapitops.plan.gathering.listeners.sponge.PlayerOnlineListener.lambda$actOnJoinEvent$5(PlayerOnlineListener.java:192) ~[PlayerOnlineListener.class:?]
	at com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:78) ~[Processing.class:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_242]
	... 3 more
```

</details>
