### ISSUE TITLE
Encountered IllegalArgumentException with Buycraft Extension [HTTP 504 error, gateway timeout, buycraft api down]

### ISSUE THREAD

**Issue by poqdavid** [plan-player-analytics/Plan#1410]
### Describe the issue
After a server reboot it just happened and had to reboot for it to be fixed and as to why it happened I have no idea 

### Server information
Spigot 1.12.2
Plan v5.1 build 505

### Exceptions & Other Logs
https://hastebin.com/najibapica.log

**Comment by Rsl1122** [comment]
<details>
<summary>Stacktrace</summary>

```
[15:32:37 WARN]: [Plan] Encountered IllegalArgumentException with Buycraft Extension (failed safely) when updating value for 'server', the method was disabled temporarily (won't be called until next Plan reload), stack trace to follow (please report this):
[15:32:37 WARN]: [Plan] Error was caught by com.djrapitops.plan.extension.ExtensionSvc
java.lang.IllegalArgumentException: class com.djrapitops.extension.BuycraftExtension method purchaseTable could not be called: null
        at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:51) ~[Plan-5.1-build-505.jar:?]
        at com.djrapitops.plan.extension.implementation.providers.gathering.TableProviderValueGatherer.lambda$null$3(TableProviderValueGatherer.java:82) ~[Plan-5.1-build-505.jar:?]
        at com.djrapitops.plan.extension.implementation.providers.gathering.TableProviderValueGatherer.getMethodResult(TableProviderValueGatherer.java:119) ~[Plan-5.1-build-505.jar:?]
        at com.djrapitops.plan.extension.implementation.providers.gathering.TableProviderValueGatherer.gatherTableDataOfProvider(TableProviderValueGatherer.java:103) ~[Plan-5.1-build-505.jar:?]
        at com.djrapitops.plan.extension.implementation.providers.gathering.TableProviderValueGatherer.gatherTableDataOfServer(TableProviderValueGatherer.java:86) ~[Plan-5.1-build-505.jar:?]
        at com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer.updateValues(ProviderValueGatherer.java:162) ~[Plan-5.1-build-505.jar:?]
        at com.djrapitops.plan.extension.ExtensionSvc.updateServerValues(ExtensionSvc.java:200) [Plan-5.1-build-505.jar:?]
        at com.djrapitops.plan.extension.ExtensionSvc.updateServerValues(ExtensionSvc.java:187) [Plan-5.1-build-505.jar:?]
        at com.djrapitops.plan.extension.ExtensionServerMethodCallerTask.run(ExtensionServerMethodCallerTask.java:41) [Plan-5.1-build-505.jar:?]
        at com.djrapitops.plugin.task.bukkit.BukkitRunnableFactory$1.run(BukkitRunnableFactory.java:55) [Plan-5.1-build-505.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
        at com.djrapitops.plan.extension.implementation.providers.Parameters$ServerParameters.usingOn(Parameters.java:63) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:46) ~[?:?]
        ... 14 more
Caused by: java.lang.IllegalStateException: IOException occurred
        at com.djrapitops.extension.ListPaymentRequest.makeRequest(ListPaymentRequest.java:82) ~[?:?]
        at com.djrapitops.extension.BuycraftExtension.purchaseTable(BuycraftExtension.java:72) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
        at com.djrapitops.plan.extension.implementation.providers.Parameters$ServerParameters.usingOn(Parameters.java:63) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:46) ~[?:?]
        ... 14 more
Caused by: java.io.IOException: Server returned HTTP response code: 504 for URL: https://plugin.tebex.io/payments
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900) ~[?:1.8.0_252]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498) ~[?:1.8.0_252]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268) ~[?:1.8.0_252]
        at com.djrapitops.extension.ListPaymentRequest.makeRequest(ListPaymentRequest.java:64) ~[?:?]
        at com.djrapitops.extension.BuycraftExtension.purchaseTable(BuycraftExtension.java:72) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
        at com.djrapitops.plan.extension.implementation.providers.Parameters$ServerParameters.usingOn(Parameters.java:63) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:46) ~[?:?]
        ... 14 more
```

</details>

**Comment by Rsl1122** [comment]
504 Gateway Timeout

Seems like the buycraft API was down. I guess this case should be gracefully handled

**Comment by poqdavid** [comment]
Ok so it's nothing important it's just on their side ty
