### ISSUE TITLE
SSL related mysql error spam

### ISSUE THREAD

**Issue by Govindass** [plan-player-analytics/Plan#1423]
### Describe the issue

```
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: Sun May 03 00:00:36 EEST 2020 WARN: Caught while disconnecting...
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: 
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: EXCEPTION STACK TRACE:
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: 
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: 
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: 
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: ** BEGIN NESTED EXCEPTION ** 
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: 
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: javax.net.ssl.SSLException
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: MESSAGE: closing inbound before receiving peer's close_notify
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: 
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: STACKTRACE:
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: 
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: 	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: 	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: 	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: 	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: 	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(Unknown Source)
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(Unknown Source)
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: 	at com.mysql.jdbc.MysqlIO.quit(MysqlIO.java:2246)
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: 	at com.mysql.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:4236)
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: 	at com.mysql.jdbc.ConnectionImpl.close(ConnectionImpl.java:1462)
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: 	at plan.com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(PoolBase.java:139)
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: 	at plan.com.zaxxer.hikari.pool.HikariPool.lambda$closeConnection$1(HikariPool.java:447)
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: 
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: 
[00:00:36] [Plan Connection Pool-1 connection closer/WARN]: ** END NESTED EXCEPTION **
```

### Server information
5.1 build 505

### Additional information
I think this could be caused by some dependencies being out of date.

**Comment by Rsl1122** [comment]
What MySQL version are you using?
What server are you using Plan on?

**Comment by Govindass** [comment]
I am using Plan on variety of servers (it's a network) and they all get the same spam

mysql  Ver 15.1 Distrib 10.4.12-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2


happens on Paper 1.12.2 and Paper 1.13.2

**Comment by Govindass** [comment]
the problem started since I started using self-signed certificate for the mysql instead of useSSL=false

**Comment by Rsl1122** [comment]
Have you added the self-signed certificate to the Java trust store?

**Comment by Govindass** [comment]
I've created a new truststore that I merged with java truststore, so yup my certificate is in it

**Comment by Govindass** [comment]
I'm using Java 11 btw, which I found to be the cause based on google

**Comment by Rsl1122** [comment]
Related bug in MySQL driver https://bugs.mysql.com/bug.php?id=93590

Spigot based servers sometimes don't load the MySQL driver in Plan and so 1.12.2 and 1.13.2 likely have the MySQL driver that has the issue

**Comment by Govindass** [comment]
thanks for letting me know, I'll try updating it inside my server's jar then
