### ISSUE TITLE
Improve command UX

### ISSUE THREAD

**Issue by Rsl1122** [plan-player-analytics/Plan#1427]
### Is your feature request related to a problem? Please describe.

Current command usage user experience could be improved, as the commands do not use features that have been available for years. These include things like tab completion and hover & click events.

Main UX concerns are:
- Confirming actions is done by adding an argument to the command.
- Effects of command usage are unclear
- Subcommands are often lacking in granularity of permissions
- The command names are unintuative
  - Proxy commands are long `planbungee` `planvelocity`
- Dicoverability
  - Player removal command is hidden under manage subcommand and is often asked for on discord.
- Effective use of the chatbox

#### Example case of bad UX

`plan m remove <player>` command

- The effect of the command is unclear
  - "Remove player's data"
  - "Remove player's data from the active database."
  - "Add -a to confirm execution: Data in MySQL will be removed"
  - "Processing Data.."
  - "Success"
- The command is confirmed with `-a` parameter
- Subcommand uses `plan.manage` permission
- The manage command is not available on bungeecord or velocity servers

#### Confirm actions by clicking or via a command (console)

- Clickable [✔] [❌] dialog when confirming actions is more intuative to the user than writing a command or adding parameters to commands. 
- `/plan confirm` `/plan cancel` commands to use when clicking is not available, eg. console

#### Know the effect the command will have upon confirmation

```
Data of 'Rsl1122' will be removed from SQLite (database.db)
```
```
All data in MySQL ('Plan') will be replaced with data from `mysql-backup-2020-05-06.db`
```

#### Tab complete server names / UUIDs

For these subcommands:
- analyze
- manage uninstalled

#### Tab completion 

- web user names: web check, web delete, unregister
- player names / UUIDs: inspect, qinspect, manage remove
- file names: manage restore
- database types: manage backup, manage hotswap, manage clear, manage move, manage restore
- importers: manage import
- exporters: manage export
- features: manage disable

#### Command name disambiguation

- web delete vs manage remove
- planbungee disable vs plan manage disable kickcount
- analyze vs server
- inspect vs player
- qinspect vs ?

#### Language

Current | Suggested alternative
-- | --
Active database | Current database
Processing (data) | Removing, Moving, Modifying, Creating
Success | X Removed, Moved, Modified, Created successfully

#### Effective use of chatbox

Current code moves text to next line if it over 60 characters, which can lead to odd line wraps.
Code exists to calculate the actual width of the text with default font and settings. Any indentation is lost with the current line breaks.

Table like data is possible to be displayed using spaces and `§l §r` (fat space) for indentation. This could improve help, info and qinspect commands.

----

### Code

Current command execution is done with Abstract-Plugin-Framework that abstracts the command sender. This makes it a bit difficult to access internal APIs such as tab completion or the builders for hover and click events. The constructor parameter definition for aliases, permissions etc feels very clunky to me, so perhaps this could be made into a builder.

Since 3 of 5 supported platforms use builders for the special behavior, the chat component builders could be abstracted behind a builder interface

Seems like I like builders now 🤔

**Comment by Rsl1122** [comment]
`planbungee register` requires `plan.manage` which is means nobody can use the register page on Bungee without allowing other commands from being used. This breaks the register flow,

**Comment by Rsl1122** [comment]
TODO:

- --force argument option to use the commands similar to -a worked
- Refresh locale files
- Honing alignment in-game for the tables
- Allow in-depth help access via /plan ?
- Tab completion
  - commands
  - web users
  - file names
  - server names
- Test all of the above on Spigot, Bungee, Sponge and Velocity. (Unable to test on Nukkit)

**Comment by Rsl1122** [comment]
Compiled with older version of velocity, must be updated because of error:
![image](https://user-images.githubusercontent.com/24460436/92311316-a5a37880-efbe-11ea-981c-bd633389f829.png)

**Comment by Rsl1122** [comment]
Testing plan (for sanity)

- `plan` shows help. Hovering over arguments shows info. 
- `plan ?` shows in depth help and arguments
- tab completion for `plan clear h`
- `plan clear h2` gives a confirmation option, clicking runs plan accept command
- `plan accept` clear clears the database
- tab completion for `plan player R`
- `plan player Rsl1122` gives a link to the page and the link can be clicked in game
- tab completion for `plan server `
- tab completion for `plan restore `
- tab completion for `plan unregister `
- Make sure tab completion is not run sync by running some timings

----

- [ ] Spigot console
- [ ] Spigot standalone player
- [ ] BungeeCord console
- [ ] Bungeecord connected Spigot player
- [ ] Sponge console
- [ ] Sponge connected player
- [ ] Velocity console
- [ ] Velocity connected Spigot player
- [ ] Nukkit console

**Comment by Rsl1122** [comment]
Issues found during testing: Spigot Player

- [ ] Tab completion not linked to implementation
  - [x] Spigot
  - [ ] Bungeecord
  - [ ] Sponge
  - [ ] Velocity
  - [ ] Nukkit
- [x] Error in Server name query
- [ ] Extra line-break at the end of hover messages in help
- [ ] Hover message applied to footer of help
- [ ] ClassCastException on /plan users (see below)
- [ ] Help for /plan db shows /db as the command
- [ ] Clicking on the commands in help menu should suggest the command
- [ ] Wrong argument tab completed when using a subcommand (/plan db hotswap)

<details>
<summary>ClassCastException on /plan users</summary>

```
091184fa31 - Last occurred: 2020-09-09 Occurrences: 1
---- Context 1 ----
Plan v5.1 build 729
CraftBukkit git-Spigot-b5a13e6-b8ee6a8 (MC: 1.16.2)
Server v1.16.2-R0.1-SNAPSHOT

com.djrapitops.plan.commands.use.BukkitPlayerCMDSender@83b0ec42
Arguments{args=[users]}

---- Stacktrace ----
java.lang.ClassCastException: com.djrapitops.plan.delivery.domain.auth.User cannot be cast to java.lang.Comparable
   java.util.Comparators$NaturalOrderComparator.compare(Unknown Source)
   java.util.TimSort.countRunAndMakeAscending(Unknown Source)
   java.util.TimSort.sort(Unknown Source)
   java.util.Arrays.sort(Unknown Source)
   java.util.stream.SortedOps$SizedRefSortingSink.end(Unknown Source)
   java.util.stream.AbstractPipeline.copyInto(Unknown Source)
   java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
   java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
   java.util.stream.AbstractPipeline.evaluate(Unknown Source)
   java.util.stream.ReferencePipeline.collect(Unknown Source)
   com.djrapitops.plan.commands.subcommands.LinkCommands.onWebUsersCommand(LinkCommands.java:218)
   com.djrapitops.plan.commands.use.CommandWithSubcommands.executeCommand(CommandWithSubcommands.java:105)
   com.djrapitops.plan.commands.use.CommandWithSubcommands.onCommand(CommandWithSubcommands.java:82)
   com.djrapitops.plan.commands.use.BukkitCommand$1.run(BukkitCommand.java:53)
   com.djrapitops.plugin.task.bukkit.BukkitRunnableFactory$1.run(BukkitRunnableFactory.java:55)
   org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:81)
   org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
   java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   java.lang.Thread.run(Unknown Source)
```

</details>

**Comment by Rsl1122** [comment]
Issues found during testing: BungeeCord through Spigot player

- [ ] No permission plugin, can not access any commands
- [ ] NPE on /planproxy cancel tab completion

<details>
<summary>NPE on /planproxy cancel</summary>

```
ed16cc9100 - Last occurred: 2020-09-21 Occurrences: 1
---- Context 1 ----
Plan v5.1 build 735
BungeeCord git:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:c987ee1:1536
Server vgit:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:c987ee1:1536

class net.md_5.bungee.UserConnection
tab completion
[cancel]

---- Stacktrace ----
java.lang.NullPointerException
   com.djrapitops.plan.commands.use.CommandWithSubcommands.onTabComplete(CommandWithSubcommands.java:128)
   com.djrapitops.plan.command.use.BungeeCommand.onTabComplete(BungeeCommand.java:81)
   net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:195)
   net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:169)
   net.md_5.bungee.protocol.packet.TabCompleteRequest.handle(TabCompleteRequest.java:87)
   net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105)
   io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
   io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
   io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
   io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
   io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
   io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
   io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
   io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
   io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
   io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
   io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
   io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
   io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
   io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
   io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
   io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
   io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
   io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
   io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
   io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
   io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
   io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
   io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
   io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
   io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
   io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
   io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
   io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
   io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
   io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
   io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
   io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
   io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
   io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
   io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
   java.lang.Thread.run(Unknown Source)
```

</details>

**Comment by Rsl1122** [comment]
Unknown cause
```
[15:15:49 WARN]: [Plan] Plugin Plan v5.1 build 735 generated an exception while executing task 1811
java.lang.NoClassDefFoundError: org/apache/commons/text/TextStringBuilder
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.hover(BukkitPartBuilder.java:82) ~[?:?]
        at com.djrapitops.plan.commands.use.HelpFormatter.addSubcommands(HelpFormatter.java:67) ~[?:?]
        at com.djrapitops.plan.commands.use.MessageBuilder.apply(MessageBuilder.java:50) ~[?:?]
        at com.djrapitops.plan.commands.use.CommandWithSubcommands.onHelp(CommandWithSubcommands.java:59) ~[?:?]
        at com.djrapitops.plan.commands.use.CommandWithSubcommands.executeCommand(CommandWithSubcommands.java:114) ~[?:?]
        at com.djrapitops.plan.commands.use.CommandWithSubcommands.onCommand(CommandWithSubcommands.java:84) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitCommand$1.run(BukkitCommand.java:60) ~[?:?]
        at com.djrapitops.plugin.task.bukkit.BukkitRunnableFactory$1.run(BukkitRunnableFactory.java:55) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-195]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.3.jar:git-Paper-195]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.3.jar:git-Paper-195]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_241]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.text.TextStringBuilder
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_241]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.3.jar:git-Paper-195]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.3.jar:git-Paper-195]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
        ... 14 more
```

**Comment by Rsl1122** [comment]
Issues found when testing with Sponge player

- [ ] Help hover messages are empty
- [ ] /plan users header does not have amount of web users in it
- [ ] /plan users output is weird when no users are registered
- [ ] "Cancel" hover message is applied to the whole message for confirmation
- [ ] The suggested command does not work (Instead said in chat)
- [ ] The whole message has the cancel action applied to it
- [ ] Tab completion for restore does not work
- [ ] /plan ingame breaks using : which is also a character in the time format, leading to odd register date row
