### ISSUE TITLE
Plan Build 600 is conflicting with AAC Anti-Cheat in version 1.15.2

### ISSUE THREAD

**Issue by AshuGuptaGamer** [plan-player-analytics/Plan#1492]
### Describe the issue
If I try to load AAC Anti-Cheat and Plan Build 600 on a 1.15.2 server, AAC will throw a startup error.
Error
If I remove the Plan plugin or downgrade it to Build 586 the AAC will work fine.

### Server information

Plan Version- Build 600
Server Version- PaperMC 1.15.2 Build 201

### Exceptions & Other Logs

```
> [03:10:22 INFO]: [AAC] Attempting to inject into PlayerConnection
> [03:10:23 ERROR]: [AAC] ERROR: Failed to inject into PlayerConnection.class: 1
> [03:10:23 ERROR]: [AAC] The Move check WILL NOT function correctly.
> [03:10:23 ERROR]: Could not load 'plugins/AAC-4.3.12.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:331) ~[patched.jar:git-PaperSpigot-"4c7641d"]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:254) [patched.jar:git-PaperSpigot-"4c7641d"]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) [patched.jar:git-PaperSpigot-"4c7641d"]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [patched.jar:git-PaperSpigot-"4c7641d"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.ExceptionInInitializerError
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_242]
    at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_242]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[patched.jar:git-PaperSpigot-"4c7641d"]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[patched.jar:git-PaperSpigot-"4c7641d"]
    ... 6 more
Caused by: java.lang.RuntimeException: Failed to inject into PlayerConnection.class
    at me.konsolas.aac.aQ.run(aQ.java) ~[?:?]
    at me.konsolas.aac.AAC.<clinit>(AAC.java) ~[?:?]
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_242]
    at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_242]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[patched.jar:git-PaperSpigot-"4c7641d"]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[patched.jar:git-PaperSpigot-"4c7641d"]
    ... 6 more
> [03:10:23 ERROR]: Could not load 'plugins/AACPlus-2.3.2.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: AAC
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:222) [patched.jar:git-PaperSpigot-"4c7641d"]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) [patched.jar:git-PaperSpigot-"4c7641d"]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [patched.jar:git-PaperSpigot-"4c7641d"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Comment by Rsl1122** [comment]
Have you tried to redownload both plugins?

I can't unfortunately fix this issue because AAC is not open source so I can't look at what is causing the issue on their end. Please report this to AAC.

**Comment by AshuGuptaGamer** [comment]
Yeah but still you can get a jar from some and see why that happening
