### ISSUE TITLE
NoSuchMethodError on server shutdown

### ISSUE THREAD

**Issue by SlimeDog** [plan-player-analytics/Plan#1568]
### Describe the issue
On server shutdown, WARN issues below are logged. I have not seen them on previous Plan releases (but they may have been missed). Primary server (no bungee).

### Server information
Spigot 1.16.2 (Jenkins 2900)
Plan 5.1 build 705

### Exceptions & Other Logs
On server shutdown:
```
[16:26:06] [Craft Scheduler Thread - 30/WARN]: [Plan] Plugin Plan v5.1 build 705 generated an exception while executing task 12745
java.lang.NoSuchMethodError: org.bukkit.command.CommandSender.sendMessage([Lnet/md_5/bungee/api/chat/BaseComponent;)V
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:105) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.subcommands.LinkCommands.onServerCommand(LinkCommands.java:110) ~[?:?]
        at com.djrapitops.plan.commands.use.CommandWithSubcommands.executeCommand(CommandWithSubcommands.java:86) ~[?:?]
        at com.djrapitops.plan.commands.use.CommandWithSubcommands.onCommand(CommandWithSubcommands.java:67) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitCommand$1.run(BukkitCommand.java:44) ~[?:?]
        at com.djrapitops.plugin.task.bukkit.BukkitRunnableFactory$1.run(BukkitRunnableFactory.java:55) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.2.jar-2020-08-31-0857:git-Spigot-b5a13e6-927200a]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.16.2.jar-2020-08-31-0857:git-Spigot-b5a13e6-927200a]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[16:26:09] [Craft Scheduler Thread - 35/WARN]: [Plan] Plugin Plan v5.1 build 705 generated an exception while executing task 12748
java.lang.NoSuchMethodError: org.bukkit.command.CommandSender.sendMessage([Lnet/md_5/bungee/api/chat/BaseComponent;)V
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:105) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.send(BukkitPartBuilder.java:108) ~[?:?]
        at com.djrapitops.plan.commands.use.CommandWithSubcommands.onHelp(CommandWithSubcommands.java:58) ~[?:?]
        at com.djrapitops.plan.commands.use.CommandWithSubcommands.executeCommand(CommandWithSubcommands.java:93) ~[?:?]
        at com.djrapitops.plan.commands.use.CommandWithSubcommands.onCommand(CommandWithSubcommands.java:67) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitCommand$1.run(BukkitCommand.java:44) ~[?:?]
        at com.djrapitops.plugin.task.bukkit.BukkitRunnableFactory$1.run(BukkitRunnableFactory.java:55) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.2.jar-2020-08-31-0857:git-Spigot-b5a13e6-927200a]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.16.2.jar-2020-08-31-0857:git-Spigot-b5a13e6-927200a]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Rsl1122** [comment]
Interesting, I wonder if this is 1.16 specific 🤔 (I ran my test using 1.15.2) - will test.

**Comment by SlimeDog** [comment]
I don't have a 1.15.2 test server ATM (only when we're validating our own plugins). Sorry.

**Comment by Rsl1122** [comment]
Hmm, I was not able to reproduce the issue with paper-182 (1.16.2) - I'll have to try again with a spigot build later.

**Comment by SlimeDog** [comment]
It occurs on both of my Spigot 1.16.2 test servers.

**Comment by Rsl1122** [comment]
Ah I see - looking at the code the method that I was using is Paper only

**Comment by Rsl1122** [comment]
Should be fixed in the new dev release

**Comment by SlimeDog** [comment]
Confirmed fixed in build 740. Thanks.
