### ISSUE TITLE
NoSuchMethodError net.md_5.bungee.api.chat.ComponentBuilder.appendLegacy on Spigot 1.8.8

### ISSUE THREAD

**Issue by Rsl1122** [plan-player-analytics/Plan#1600]
### Describe the issue

Old version runs an old version of a library.

### Server information

Spigot 1.8.8

### Exceptions & Other Logs

```
12.10 08:07:00 [Server] WARN Exception in thread "Craft Scheduler Thread - 3" 
12.10 08:07:00 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin Plan v5.1 build 770 generated an exception while executing task 666
12.10 08:07:00 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
12.10 08:07:00 [Server] INFO at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
12.10 08:07:00 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
12.10 08:07:00 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
12.10 08:07:00 [Server] INFO at java.lang.Thread.run(Thread.java:748)
12.10 08:07:00 [Server] INFO Caused by: java.lang.NoSuchMethodError: net.md_5.bungee.api.chat.ComponentBuilder.appendLegacy(Ljava/lang/String;)Lnet/md_5/bungee/api/chat/ComponentBuilder;
12.10 08:07:00 [Server] INFO at com.djrapitops.plan.commands.use.BukkitPartBuilder.addPart(BukkitPartBuilder.java:46)
12.10 08:07:00 [Server] INFO at com.djrapitops.plan.commands.use.CommandWithSubcommands.onHelp(CommandWithSubcommands.java:57)
12.10 08:07:00 [Server] INFO at com.djrapitops.plan.commands.use.CommandWithSubcommands.executeCommand(CommandWithSubcommands.java:114)
12.10 08:07:00 [Server] INFO at com.djrapitops.plan.commands.use.CommandWithSubcommands.onCommand(CommandWithSubcommands.java:84)
12.10 08:07:00 [Server] INFO at com.djrapitops.plan.commands.use.BukkitCommand$1.run(BukkitCommand.java:60)
12.10 08:07:00 [Server] INFO at com.djrapitops.plugin.task.bukkit.BukkitRunnableFactory$1.run(BukkitRunnableFactory.java:55)
12.10 08:07:00 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
12.10 08:07:00 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
12.10 08:07:00 [Server] INFO ... 4 more
```

**Comment by Rsl1122** [comment]
```
[04:41:14 WARN]: org.apache.commons.lang.UnhandledException: Plugin Plan v5.1 build 791 generated an exception while executing task 17779
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: net.md_5.bungee.api.chat.ComponentBuilder.append([Lnet/md_5/bungee/api/chat/BaseComponent;)Lnet/md_5/bungee/api/chat/ComponentBuilder;
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.addPart(BukkitPartBuilder.java:48)
        at com.djrapitops.plan.commands.use.CommandWithSubcommands.onHelp(CommandWithSubcommands.java:57)
        at com.djrapitops.plan.commands.use.CommandWithSubcommands.executeCommand(CommandWithSubcommands.java:114)
        at com.djrapitops.plan.commands.use.CommandWithSubcommands.onCommand(CommandWithSubcommands.java:84)
        at com.djrapitops.plan.commands.use.BukkitCommand$1.run(BukkitCommand.java:60)
        at com.djrapitops.plugin.task.bukkit.BukkitRunnableFactory$1.run(BukkitRunnableFactory.java:55)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```
