### ISSUE TITLE
Support for Velocity 1.1.5-SNAPSHOT

### ISSUE THREAD

**Issue by ItsMCB** [plan-player-analytics/Plan#1782]
### Describe the issue
The latest build, Plan-5.2-build-1068.jar, doesn't load on Velocity version 1.1.5-SNAPSHOT.

### Exceptions & Other Logs

```
[04:34:14 INFO]: Loading plugins...
[04:34:15 ERROR]: Unable to load plugin plugins/Plan-5.2-build-1068.jar
java.io.EOFException: Unexpected end of ZLIB input stream
        at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:245) ~[?:?]
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159) ~[?:?]
        at java.util.zip.ZipInputStream.read(ZipInputStream.java:197) ~[?:?]
        at java.util.jar.JarInputStream.read(JarInputStream.java:207) ~[?:?]
        at java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:143) ~[?:?]
        at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:121) ~[?:?]
        at java.util.jar.JarInputStream.getNextEntry(JarInputStream.java:142) ~[?:?]
        at java.util.jar.JarInputStream.getNextJarEntry(JarInputStream.java:179) ~[?:?]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.getSerializedPluginInfo(JavaPluginLoader.java:120) ~[velocity.jar:1.1.5-SNAPSHOT (git-d4a7ee4a-b4)]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadPluginDescription(JavaPluginLoader.java:44) ~[velocity.jar:1.1.5-SNAPSHOT (git-d4a7ee4a-b4)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:76) ~[velocity.jar:1.1.5-SNAPSHOT (git-d4a7ee4a-b4)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:266) ~[velocity.jar:1.1.5-SNAPSHOT (git-d4a7ee4a-b4)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:208) ~[velocity.jar:1.1.5-SNAPSHOT (git-d4a7ee4a-b4)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:58) ~[velocity.jar:1.1.5-SNAPSHOT (git-d4a7ee4a-b4)]

```

**Comment by AuroraLS3** [comment]
Looks like the file might be corrupt, try re-downloading the jar
