### ISSUE TITLE
NoClassDefFoundError onLoad of plugin implementing API

### ISSUE THREAD

**Issue by Silthus** [plan-player-analytics/Plan#1794]
### Describe the issue

I am quite confused as to why this is happening...
I properly implemented `Plan` in my plugin, added a `softdepend` and catch all exceptions when enabling plan. However at the very start of the server I get a `java.lang.NoClassDefFoundError: com/djrapitops/plan/extension/DataExtension` before the plugin is even loaded.

You can find the full source code of my plugin here: https://github.com/raidcraft/rcreferrals/blob/master/src/main/java/de/raidcraft/referrals/RCReferrals.java#L128

And as you can see I have no static initialization of Plan whatsoever. And nontheless it is throwing that exception at startup. Do you have any idea why this would be happening?

### Exceptions & Other Logs

```
[05:01:36] [Server thread/ERROR]: Could not load 'plugins/RCReferrals-1.6.2.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/djrapitops/plan/extension/DataExtension
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[patched_1.16.5.jar:git-Paper-549]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.16.5.jar:git-Paper-549]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:336) ~[patched_1.16.5.jar:git-Paper-549]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:389) ~[patched_1.16.5.jar:git-Paper-549]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:212) ~[patched_1.16.5.jar:git-Paper-549]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:943) ~[patched_1.16.5.jar:git-Paper-549]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.5.jar:git-Paper-549]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NoClassDefFoundError: com/djrapitops/plan/extension/DataExtension
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:79) ~[patched_1.16.5.jar:git-Paper-549]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.5.jar:git-Paper-549]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: com.djrapitops.plan.extension.DataExtension
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[patched_1.16.5.jar:git-Paper-549]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Paper-549]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:79) ~[patched_1.16.5.jar:git-Paper-549]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.5.jar:git-Paper-549]
        ... 7 more
```

```
[05:01:27] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[05:01:27] [main/INFO]: Reloading ResourceManager: Default, bukkit
[05:01:28] [Worker-Main-3/INFO]: Loaded 7 recipes
[05:01:30] [Server thread/INFO]: Starting minecraft server version 1.16.5
[05:01:30] [Server thread/INFO]: Loading properties
[05:01:30] [Server thread/INFO]: This server is running Paper version git-Paper-549 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[05:01:30] [Server thread/INFO]: Server Ping Player Sample Count: 12
[05:01:30] [Server thread/INFO]: Using 4 threads for Netty based IO
[05:01:30] [Server thread/INFO]: Debug logging is disabled
[05:01:30] [Server thread/INFO]: Default game type: SURVIVAL
[05:01:30] [Server thread/INFO]: Generating keypair
[05:01:30] [Server thread/INFO]: Starting Minecraft server on *:25565
[05:01:30] [Server thread/INFO]: Using epoll channel type
[05:01:32] [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[05:01:35] [Server thread/WARN]: Legacy plugin EffectLib v6.4 does not specify an api-version.
[05:01:35] [Server thread/WARN]: Legacy plugin LangUtils v1.9 does not specify an api-version.
[05:01:35] [Server thread/WARN]: Legacy plugin dynmap v3.1-beta6-438 does not specify an api-version.
[05:01:36] [Server thread/ERROR]: Could not load 'plugins/RCReferrals-1.6.2.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/djrapitops/plan/extension/DataExtension
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[patched_1.16.5.jar:git-Paper-549]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.16.5.jar:git-Paper-549]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:336) ~[patched_1.16.5.jar:git-Paper-549]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:389) ~[patched_1.16.5.jar:git-Paper-549]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:212) ~[patched_1.16.5.jar:git-Paper-549]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:943) ~[patched_1.16.5.jar:git-Paper-549]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.5.jar:git-Paper-549]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NoClassDefFoundError: com/djrapitops/plan/extension/DataExtension
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:79) ~[patched_1.16.5.jar:git-Paper-549]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.5.jar:git-Paper-549]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: com.djrapitops.plan.extension.DataExtension
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[patched_1.16.5.jar:git-Paper-549]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Paper-549]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:79) ~[patched_1.16.5.jar:git-Paper-549]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.5.jar:git-Paper-549]
        ... 7 more
[05:01:36] [Server thread/INFO]: [AdvancedMonthlyCrates] Loading AdvancedMonthlyCrates v1.9.574
[05:01:36] [Server thread/INFO]: [ebean-wrapper] Loading ebean-wrapper v2.9.1
[05:01:36] [Server thread/INFO]: [PlaceholderAPI] Loading PlaceholderAPI v2.10.9
[05:01:36] [Server thread/INFO]: [UltimateAutoRestart] Loading UltimateAutoRestart vBuild 42a
[05:01:36] [Server thread/INFO]: [PureTickets] Loading PureTickets v3.1.1
[05:01:36] [Server thread/INFO]: [VoxelSniper] Loading VoxelSniper v6.1.2
[05:01:36] [Server thread/INFO]: [NBTAPI] Loading NBTAPI v2.7.1
[05:01:36] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_16_R3! Trying to find NMS support
[05:01:36] [Server thread/INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_16_R3' loaded!
[05:01:36] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
[05:01:36] [Server thread/INFO]: [NBTAPI] [NBTAPI] Using the plugin 'AdvancedMonthlyCrates' to create a bStats instance!
[05:01:36] [Server thread/INFO]: [LightAPI] Loading LightAPI v3.4.6
[05:01:36] [Server thread/INFO]: [LuckPerms] Loading LuckPerms v5.3.0
[05:01:37] [Thread-14/INFO]: [NBTAPI] [NBTAPI] The NBT-API seems to be up-to-date!
[05:01:39] [Server thread/INFO]: [RCTips] Loading RCTips v1.3.2
[05:01:39] [Server thread/INFO]: [art-framework] Loading art-framework v4.5.3
[05:01:39] [Server thread/INFO]: [art-framework] [REGISTERED] resolver: io.artframework.resolver.EnumResolver for type: java.lang.Enum
```

**Comment by AuroraLS3** [comment]
If you softdepend and Plan is not installed you can't have Plan classes in the main class (JavaPlugin) because the class loader will attempt to find all imports when loading the main class. It's best to to do all Plan imports in a separate class, see <https://github.com/plan-player-analytics/Plan/wiki/DataExtension-API---Getting-started#21-create-a-class-to-separate-plan-imports-from-your-main-class> for more

**Comment by Silthus** [comment]
> If you softdepend and Plan is not installed you can't have Plan classes in the main class (JavaPlugin) because the class loader will attempt to find all imports when loading the main class. It's best to to do all Plan imports in a separate class, see https://github.com/plan-player-analytics/Plan/wiki/DataExtension-API---Getting-started#21-create-a-class-to-separate-plan-imports-from-your-main-class for more

Thank you, I did not catch that when creating my class. Maybe you could add a link to the link from above here (https://github.com/plan-player-analytics/Plan/wiki/APIv5---DataExtension-API#-how-to-register-a-dataextension)

**Comment by AuroraLS3** [comment]
There is a Getting started link above that section
