### ISSUE TITLE
Plan fails to initialize if the plugins/Plan directory is a symbolic link

### ISSUE THREAD

**Issue by Combustible** [plan-player-analytics/Plan#1866]
### Describe the issue
If the Plan directory is a symbolic link, Plan fails to load. We use symbolic links to manage the persistent plugin config files of many servers that have their configuration frequently regenerated. 

A couple years back a similar issue existed which I created a pull request for - #1208 - but I haven't had a chance to look into fixing it again. 

### Exceptions & Other Logs
```
[04:35:55 INFO]: [Plan] Enabling Plan v5.2 build 1174
[04:35:55 ERROR]: [Plan] Plan-v5.2 build 1174
java.lang.IllegalStateException: plugins/Plan
        at com.djrapitops.plan.settings.config.Config.<init>(Config.java:55) ~[?:?]
        at com.djrapitops.plan.settings.config.PlanConfig.<init>(PlanConfig.java:66) ~[?:?]
        at com.djrapitops.plan.settings.config.PlanConfig.<init>(PlanConfig.java:56) ~[?:?]
        at com.djrapitops.plan.settings.config.PlanConfig_Factory.newInstance(PlanConfig_Factory.java:45) ~[?:?]
        at com.djrapitops.plan.settings.config.PlanConfig_Factory.get(PlanConfig_Factory.java:34) ~[?:?]
        at com.djrapitops.plan.settings.config.PlanConfig_Factory.get(PlanConfig_Factory.java:9) ~[?:?]
        at plan.dagger.internal.DoubleCheck.get(DoubleCheck.java:47) ~[?:?]
        at plan.dagger.internal.DelegateFactory.get(DelegateFactory.java:36) ~[?:?]
        at com.djrapitops.plan.settings.BukkitConfigSystem_Factory.get(BukkitConfigSystem_Factory.java:52) ~[?:?]
        at com.djrapitops.plan.settings.BukkitConfigSystem_Factory.get(BukkitConfigSystem_Factory.java:14) ~[?:?]
        at plan.dagger.internal.DoubleCheck.get(DoubleCheck.java:47) ~[?:?]
        at com.djrapitops.plan.PlanSystem_Factory.get(PlanSystem_Factory.java:120) ~[?:?]
        at com.djrapitops.plan.PlanSystem_Factory.get(PlanSystem_Factory.java:28) ~[?:?]
        at plan.dagger.internal.DoubleCheck.get(DoubleCheck.java:47) ~[?:?]
        at com.djrapitops.plan.DaggerPlanBukkitComponent.system(DaggerPlanBukkitComponent.java:881) ~[?:?]
        at com.djrapitops.plan.Plan.onEnable(Plan.java:81) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-"90a81ae6e"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-"90a81ae6e"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-"90a81ae6e"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:502) ~[patched_1.16.5.jar:git-Paper-"90a81ae6e"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-"90a81ae6e"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.5.jar:git-Paper-"90a81ae6e"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.5.jar:git-Paper-"90a81ae6e"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:944) ~[patched_1.16.5.jar:git-Paper-"90a81ae6e"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.5.jar:git-Paper-"90a81ae6e"]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.nio.file.FileAlreadyExistsException: plugins/Plan
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:94) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[?:?]
        at java.nio.file.Files.createDirectory(Files.java:690) ~[?:?]
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:797) ~[?:?]
        at java.nio.file.Files.createDirectories(Files.java:743) ~[?:?]
        at com.djrapitops.plan.settings.config.Config.<init>(Config.java:50) ~[?:?]
        ... 25 more
[04:35:55 ERROR]: [Plan] Plugin Failed to Initialize Correctly. If this issue is caused by config settings you can use /plan reload
[04:35:55 ERROR]: [Plan] This error should be reported at https://github.com/plan-player-analytics/Plan/issues
[04:35:55 INFO]: [Plan] Player Analytics Disabled.
[04:35:55 ERROR]: Error occurred while enabling Plan v5.2 build 1174 (Is it up to date?)
java.lang.IllegalStateException: plugins/Plan
        at com.djrapitops.plan.settings.config.Config.<init>(Config.java:55) ~[?:?]
        at com.djrapitops.plan.settings.config.PlanConfig.<init>(PlanConfig.java:66) ~[?:?]
        at com.djrapitops.plan.settings.config.PlanConfig.<init>(PlanConfig.java:56) ~[?:?]
        at com.djrapitops.plan.settings.config.PlanConfig_Factory.newInstance(PlanConfig_Factory.java:45) ~[?:?]
        at com.djrapitops.plan.settings.config.PlanConfig_Factory.get(PlanConfig_Factory.java:34) ~[?:?]
        at com.djrapitops.plan.settings.config.PlanConfig_Factory.get(PlanConfig_Factory.java:9) ~[?:?]
        at plan.dagger.internal.DoubleCheck.get(DoubleCheck.java:47) ~[?:?]
        at plan.dagger.internal.DelegateFactory.get(DelegateFactory.java:36) ~[?:?]
        at com.djrapitops.plan.settings.locale.LocaleSystem_Factory.get(LocaleSystem_Factory.java:39) ~[?:?]
        at com.djrapitops.plan.settings.locale.LocaleSystem_Factory.get(LocaleSystem_Factory.java:11) ~[?:?]
        at plan.dagger.internal.DoubleCheck.get(DoubleCheck.java:47) ~[?:?]
        at com.djrapitops.plan.modules.SystemObjectProvidingModule_ProvideLocaleFactory.get(SystemObjectProvidingModule_ProvideLocaleFactory.java:31) ~[?:?]
        at com.djrapitops.plan.modules.SystemObjectProvidingModule_ProvideLocaleFactory.get(SystemObjectProvidingModule_ProvideLocaleFactory.java:10) ~[?:?]
        at plan.dagger.internal.DoubleCheck.get(DoubleCheck.java:47) ~[?:?]
        at plan.dagger.internal.DelegateFactory.get(DelegateFactory.java:36) ~[?:?]
        at com.djrapitops.plan.commands.PlanCommand_Factory.get(PlanCommand_Factory.java:75) ~[?:?]
        at com.djrapitops.plan.commands.PlanCommand_Factory.get(PlanCommand_Factory.java:17) ~[?:?]
        at plan.dagger.internal.DoubleCheck.get(DoubleCheck.java:47) ~[?:?]
        at com.djrapitops.plan.DaggerPlanBukkitComponent.planCommand(DaggerPlanBukkitComponent.java:876) ~[?:?]
        at com.djrapitops.plan.Plan.onEnable(Plan.java:105) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-"90a81ae6e"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-"90a81ae6e"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-"90a81ae6e"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:502) ~[patched_1.16.5.jar:git-Paper-"90a81ae6e"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-"90a81ae6e"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.5.jar:git-Paper-"90a81ae6e"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.5.jar:git-Paper-"90a81ae6e"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:944) ~[patched_1.16.5.jar:git-Paper-"90a81ae6e"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.5.jar:git-Paper-"90a81ae6e"]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.nio.file.FileAlreadyExistsException: plugins/Plan
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:94) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[?:?]
        at java.nio.file.Files.createDirectory(Files.java:690) ~[?:?]
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:797) ~[?:?]
        at java.nio.file.Files.createDirectories(Files.java:743) ~[?:?]
        at com.djrapitops.plan.settings.config.Config.<init>(Config.java:50) ~[?:?]
        ... 29 more
```

**Comment by AuroraLS3** [comment]
Probable regression due to https://github.com/plan-player-analytics/Plan/commit/e1bffbcc1ff48ea67ae74562acc54a803d090563#diff-2fa5bf607d3ac1ab50c3fb17b1d8a83377a14d8c491eb7f794552a0838217fdeL53-R51

**Comment by AuroraLS3** [comment]
Problematic calls https://github.com/plan-player-analytics/Plan/search?q=Files.createdirectories

**Comment by Combustible** [comment]
Looks like this is a step in the right direction, but now introduces an infinite recursion error
```
[19:34:24 WARN]: [Plan] Plugin Plan v5.2 build 1254 generated an exception while executing task 197
java.lang.StackOverflowError: null
        at java.io.File.list(File.java:1136) ~[?:?]
        at java.io.File.listFiles(File.java:1221) ~[?:?]
        at com.djrapitops.plan.storage.upkeep.OldDependencyCacheDeletionTask.deleteDirectory(OldDependencyCacheDeletionTask.java:76) ~[?:?]
        at com.djrapitops.plan.storage.upkeep.OldDependencyCacheDeletionTask.deleteDirectory(OldDependencyCacheDeletionTask.java:80) ~[?:?]
        at com.djrapitops.plan.storage.upkeep.OldDependencyCacheDeletionTask.deleteDirectory(OldDependencyCacheDeletionTask.java:80) ~[?:?]
        at com.djrapitops.plan.storage.upkeep.OldDependencyCacheDeletionTask.deleteDirectory(OldDependencyCacheDeletionTask.java:80) ~[?:?]
        at com.djrapitops.plan.storage.upkeep.OldDependencyCacheDeletionTask.deleteDirectory(OldDependencyCacheDeletionTask.java:80) ~[?:?]```

**Comment by AuroraLS3** [comment]
Could be unrelated error that occurs in untested code anyway 😅 - thanks for reporting I'll have to fix that

**Comment by Combustible** [comment]
Looks like if I delete these dependency/libraries directories this problem went away. Still probably worth fixing?

Really appreciate the quick fix, thanks!
