### ISSUE TITLE
Java 16

### ISSUE THREAD

**Issue by Voten641** [plan-player-analytics/Plan#1926]
Plan doesnt work with java 16
`[13:00:40] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] null initializing Plan v5.3 build 1284 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at net.playeranalytics.plugin.dependencies.DependencyLoader.load(DependencyLoader.java:48) ~[?:?]
	at com.djrapitops.plan.DependencyStartup.loadDependencies(DependencyStartup.java:67) ~[?:?]
	at com.djrapitops.plan.Plan.onLoad(Plan.java:68) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:399) ~[patched_1.16.5.jar:git-Tuinity-"df76b3c"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:270) ~[patched_1.16.5.jar:git-Tuinity-"df76b3c"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1071) ~[patched_1.16.5.jar:git-Tuinity-"df76b3c"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Tuinity-"df76b3c"]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @7a62dc8
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
	at java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[?:?]
	at java.lang.reflect.Method.setAccessible(Method.java:193) ~[?:?]
	at net.playeranalytics.plugin.ninja.egg82.mvn.classloaders.TransparentInjectableClassLoader.<clinit>(TransparentInjectableClassLoader.java:28) ~[?:?]
	... 8 more`

**Comment by AuroraLS3** [comment]
Yes it's the pinned issue - workaround in that ticket https://github.com/plan-player-analytics/Plan/issues/1886
