### ISSUE TITLE
Plan causes AntiVPN to throw SQLite NoClassDefFoundError

### ISSUE THREAD

**Issue by Kopo942** [plan-player-analytics/Plan#1935]
### Describe the issue

Since we don't relocate our SQLite driver, AntiVPN refuses to load with Plan installed. Because of the issue comment in :plugin `build.gradle`, I'll leave this up to you to solve.
### Exceptions & Other Logs

```
[00:36:37 WARN]: Error loading plugin AntiVPN
java.lang.NoClassDefFoundError: org/sqlite/jdbc3/JDBC3Connection
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_282]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_282]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_282]
        at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:146) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:47fa16d:431]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_282]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:47fa16d:431]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:47fa16d:431]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_282]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_282]
        at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_282]
        at me.egg82.antivpn.BungeeBootstrap.loadJars(BungeeBootstrap.java:185) ~[?:?]
        at me.egg82.antivpn.BungeeBootstrap.onLoad(BungeeBootstrap.java:44) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:398) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:47fa16d:431]
        at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:300) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:47fa16d:431]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:47fa16d:431]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:80) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:47fa16d:431]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:47fa16d:431]
Caused by: java.lang.ClassNotFoundException: org.sqlite.jdbc3.JDBC3Connection
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:97) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:47fa16d:431]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:47fa16d:431]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_282]
        ... 17 more
```

### Additional information

Plan version: 7db894c

**Comment by AuroraLS3** [comment]
Oh no I thought that class wasn't necessary, I guess I can just remove the exclude rule then..
