### ISSUE TITLE
"Couldn't pass ProxyInitializeEvent to plan" - Velocity 3.0 

### ISSUE THREAD

**Issue by bugattiboy01** [plan-player-analytics/Plan#1957]
Start Velocity 3.0 with Plan

->

```
[00:41:41 ERROR]: Couldn't pass ProxyInitializeEvent to plan
java.lang.NoSuchMethodError: 'void com.velocitypowered.api.command.CommandManager.register(com.velocitypowered.api.command.Command, java.lang.String[])'
        at com.djrapitops.plan.PlanVelocity.registerCommand(PlanVelocity.java:149) ~[?:?]
        at com.djrapitops.plan.PlanVelocity.onEnable(PlanVelocity.java:129) ~[?:?]
        at com.djrapitops.plan.PlanVelocity.onProxyStart(PlanVelocity.java:84) ~[?:?]
        at com.djrapitops.plan.Lmbda$8.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.0.0-SNAPSHOT (git-3b6b73f2-b32)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:587) ~[velocity.jar:3.0.0-SNAPSHOT (git-3b6b73f2-b32)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$6(VelocityEventManager.java:468) ~[velocity.jar:3.0.0-SNAPSHOT (git-3b6b73f2-b32)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

```

### Additional information
Plan starts. But i dont know what if any functions are inhibited by this error

**Comment by AuroraLS3** [comment]
Plan hasn't updated to newer velocity api yet.

Seems like command registration failed and that's the last thing Plan does during enable so everything else should work fine
