### ISSUE TITLE
Session shutdown save runs into class loading issue when trying to store unfinished sessions

### ISSUE THREAD

**Issue by Produktecheck** [plan-player-analytics/Plan#1970]
### Describe the issue
Error on server shutdown

### Exceptions & Other Logs

```
[20:53:24] [Server thread/INFO]: Closing Thread Pool
[20:53:24] [Server thread/INFO]: Closing Server
[20:53:24] [Thread-37/WARN]: Exception in thread "Thread-37" java.lang.IllegalStateException: zip file closed
[20:53:24] [Thread-37/WARN]: 	at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:828)
[20:53:24] [Thread-37/WARN]: 	at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:327)
[20:53:24] [Thread-37/WARN]: 	at java.base/java.util.jar.JarFile.getEntry(JarFile.java:513)
[20:53:24] [Thread-37/WARN]: 	at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:468)
[20:53:24] [Thread-37/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158)
[20:53:24] [Thread-37/WARN]: 	at java.base/java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1208)
[20:53:24] [Thread-37/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1123)
[20:53:24] [Thread-37/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
[20:53:24] [Thread-37/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[20:53:24] [Thread-37/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1106)
[20:53:24] [Thread-37/WARN]: 	at com.djrapitops.plan.gathering.domain.FinishedSession.serializeCSV(FinishedSession.java:194)
[20:53:24] [Thread-37/WARN]: 	at com.djrapitops.plan.gathering.ShutdownDataPreservation$$Lambda$10722/0x00000000cc118b58.apply(Unknown Source)
[20:53:24] [Thread-37/WARN]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[20:53:24] [Thread-37/WARN]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[20:53:24] [Thread-37/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
[20:53:24] [Thread-37/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
[20:53:24] [Thread-37/WARN]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
[20:53:24] [Thread-37/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
[20:53:24] [Thread-37/WARN]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[20:53:24] [Thread-37/WARN]: 	at com.djrapitops.plan.gathering.ShutdownDataPreservation.storeFinishedSessions(ShutdownDataPreservation.java:148)
[20:53:24] [Thread-37/WARN]: 	at com.djrapitops.plan.gathering.ShutdownDataPreservation.preserveSessionsInCache(ShutdownDataPreservation.java:139)
[20:53:24] [Thread-37/WARN]: 	at com.djrapitops.plan.gathering.ShutdownHook.run(ShutdownHook.java:67)
```

### Additional information
1.17

**Comment by mibby** [comment]
Can also reproduce Plan outputting this exception on shutdown with Plan 5.4 build 1330 on Java 16 / Paper 1.17.

```
[03:21:46] [Server thread/INFO]: Closing Thread Pool
[03:21:46] [Server thread/INFO]: Closing Server
[03:21:46] [Thread-67/WARN]: Exception in thread "Thread-67" java.lang.IllegalStateException: zip file closed
[03:21:46] [Thread-67/WARN]: 	at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:828)
[03:21:46] [Thread-67/WARN]: 	at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:327)
[03:21:46] [Thread-67/WARN]: 	at java.base/java.util.jar.JarFile.getEntry(JarFile.java:513)
[03:21:46] [Thread-67/WARN]: 	at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:468)
[03:21:46] [Thread-67/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:159)
[03:21:46] [Thread-67/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
[03:21:46] [Thread-67/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
[03:21:46] [Thread-67/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[03:21:46] [Thread-67/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[03:21:46] [Thread-67/WARN]: 	at com.djrapitops.plan.gathering.domain.FinishedSession.serializeCSV(FinishedSession.java:194)
[03:21:46] [Thread-67/WARN]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[03:21:46] [Thread-67/WARN]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[03:21:46] [Thread-67/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[03:21:46] [Thread-67/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[03:21:46] [Thread-67/WARN]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
[03:21:46] [Thread-67/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[03:21:46] [Thread-67/WARN]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[03:21:46] [Thread-67/WARN]: 	at com.djrapitops.plan.gathering.ShutdownDataPreservation.storeFinishedSessions(ShutdownDataPreservation.java:148)
[03:21:46] [Thread-67/WARN]: 	at com.djrapitops.plan.gathering.ShutdownDataPreservation.preserveSessionsInCache(ShutdownDataPreservation.java:139)
[03:21:46] [Thread-67/WARN]: 	at com.djrapitops.plan.gathering.ShutdownHook.run(ShutdownHook.java:67)
```

**Comment by AuroraLS3** [comment]
Looks like server now unloads its own libraries during shutdown and Gson is not available when server shutdown hook is triggered

**Comment by Kopo942** [comment]
> Looks like server now unloads its own libraries during shutdown and Gson is not available when server shutdown hook is triggered

This problem is actually caused by Spigot & its forks closing classloaders during plugin shutdown -> plugins can't load new classes after they've been/are in the middle of shutting down (we're using the shaded gson). An easy fix would be to simply `Class.forName(SomeClass.class.getName());` all erroring classes at `onEnable`, that creates a reference in the class loader which then keeps the class loaded until the server has been completely shut down.

**Comment by AuroraLS3** [comment]
I decided to write the json serialization by hand to avoid loading Gson - but I'll keep that solution in mind in case this comes up again.
