### ISSUE TITLE
OutOfMemory - running out of threads

### ISSUE THREAD

**Issue by runescapejon** [plan-player-analytics/Plan#1984]
### Describe the issue

I'm having this memory problem, at first I assumed that I ran out of ram space. So, I increase it the ram on my server the issue still remains. However, when I updated the plugin from `Plan-5.3-build-1284` to `Plan-5.4-build-1330` Still remains, the only solution I'd found was disabling Plans altogether. 

Time Setting from config:

```
# -----------------------------------------------------
# Supported time units: MILLISECONDS, SECONDS, MINUTES, HOURS, DAYS
# -----------------------------------------------------
Time:
    Delays:
        Ping_server_enable_delay: 300
            Unit: SECONDS
        Ping_player_join_delay: 30
            Unit: SECONDS
        Wait_for_DB_Transactions_on_disable: 20
            Unit: SECONDS
    Thresholds:
        # How long player needs to be idle until Plan considers them AFK
        AFK_threshold: 3
            Unit: MINUTES
        # Activity Index considers last 3 weeks and uses these thresholds in the calculation
        # The index is a number from 0 to 5.
        # These numbers were calibrated with data of 250 players (Small sample size).
        Activity_index:
            Playtime_threshold: 30
                Unit: MINUTES
        Remove_inactive_player_data_after: 36500
            Unit: DAYS
        # Includes players online, tps and performance time series
        Remove_time_series_data_after: 36500
            Unit: DAYS
        Remove_ping_data_after: 36500
            Unit: DAYS
        Remove_disabled_extension_data_after: 36500
            Unit: DAYS
    Periodic_tasks:
        Extension_data_refresh_every: 1
            Unit: HOURS
        Check_DB_for_server_config_files_every: 1
            Unit: MINUTES
        Clean_Database_every: 1
            Unit: HOURS
# -----------------------------------------------------
```

### Exceptions & Other Logs

```
[13:35:53] [Netty Worker IO Thread #13/WARN]: Error dispatching event ServerConnectedEvent(player=runescapejon, server=net.md_5.bungee.ServerConnection@20b9d9f1) to listener com.djrapitops.plan.gathering.timed.BungeePingCounter@4228f269
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method) ~[?:1.8.0_282]
	at java.lang.Thread.start(Thread.java:717) ~[?:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957) ~[?:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1378) ~[?:1.8.0_282]
	at net.md_5.bungee.scheduler.BungeeScheduler.schedule(BungeeScheduler.java:104) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at net.md_5.bungee.scheduler.BungeeScheduler.schedule(BungeeScheduler.java:88) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at net.playeranalytics.plugin.scheduling.UnscheduledBungeeTask.runTaskLaterAsynchronously(UnscheduledBungeeTask.java:32) ~[?:?]
	at net.playeranalytics.plugin.scheduling.UnscheduledBungeeTask.runTaskLater(UnscheduledBungeeTask.java:62) ~[?:?]
	at com.djrapitops.plan.gathering.timed.BungeePingCounter.onPlayerJoin(BungeePingCounter.java:145) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor59.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:47) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:453) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:215) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at net.md_5.bungee.protocol.packet.Login.handle(Login.java:181) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Travertine.jar:git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:89a00ae:unknown]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
```

----

*by AuroraLS3:*

### TODO

- Run server and inspect if any tasks are leaving behind unclosed threads, and see if something is holding up heap
- Replace asynchronous task execution on bungeecord with a ScheduledExecutor based RunnableFactory to reduce the amount threads being created for tasks
- Detect if database has a lot of transactions in the queue with an AtomicInteger and start ignoring some unimportant transactions such as extension data transactions.

**Comment by AuroraLS3** [comment]
The other report from about a week ago

```
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 12582912 bytes for committing reserved memory.
# Possible reasons:
#   The system is out of physical RAM or swap space
#   The process is running with CompressedOops enabled, and the Java Heap may be blocking the growth of the native heap
# Possible solutions:
#   Reduce memory load on the system
#   Increase physical memory or swap space
#   Check if swap backing store is full
#   Decrease Java heap size (-Xmx/-Xms)
#   Decrease number of Java threads
#   Decrease Java thread stack sizes (-Xss)
#   Set larger code cache with -XX:ReservedCodeCacheSize=
#   JVM is running with Zero Based Compressed Oops mode in which the Java heap is
#     placed in the first 32GB address space. The Java Heap base address is the
#     maximum limit for the native heap growth. Please use -XX:HeapBaseMinAddress
#     to set the Java Heap base and to place the Java Heap above 32GB virtual address.
# This output file may be truncated or incomplete.
#
#  Out of Memory Error (os_linux.cpp:2756), pid=32475, tid=0x00007f8909efc700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_281-b09) (build 1.8.0_281-b09)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.281-b09 mixed mode linux-amd64 compressed oops)
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#

---------------  T H R E A D  ---------------

Current thread (0x00007f899000c800):  JavaThread "Plan MySQLDB-transaction-thread-1" [_thread_in_vm, id=28762, stack(0x00007f8909dfc000,0x00007f8909efd000)]

Stack: [0x00007f8909dfc000,0x00007f8909efd000],  sp=0x00007f8909efa3a0,  free space=1016k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0xade185]  VMError::report_and_die()+0x2e5
V  [libjvm.so+0x4e1f67]  report_vm_out_of_memory(char const*, int, unsigned long, VMErrorType, char const*)+0x67
V  [libjvm.so+0x917b96]  os::pd_commit_memory_or_exit(char*, unsigned long, unsigned long, bool, char const*)+0x106
V  [libjvm.so+0x90f34d]  os::commit_memory_or_exit(char*, unsigned long, unsigned long, bool, char const*)+0x1d
V  [libjvm.so+0x5b1b14]  G1PageBasedVirtualSpace::commit_internal(unsigned long, unsigned long)+0x224
V  [libjvm.so+0x5b1b9e]  G1PageBasedVirtualSpace::commit(unsigned long, unsigned long)+0x7e
V  [libjvm.so+0x5b4785]  G1RegionsLargerThanCommitSizeMapper::commit_regions(unsigned int, unsigned long)+0x35
V  [libjvm.so+0x61fc66]  HeapRegionManager::commit_regions(unsigned int, unsigned long)+0x76
V  [libjvm.so+0x620d7f]  HeapRegionManager::make_regions_available(unsigned int, unsigned int)+0x3f
V  [libjvm.so+0x6213b3]  HeapRegionManager::expand_at(unsigned int, unsigned int)+0x113
V  [libjvm.so+0x58e389]  G1CollectedHeap::humongous_obj_allocate(unsigned long, unsigned char)+0x129
V  [libjvm.so+0x58e78d]  G1CollectedHeap::attempt_allocation_humongous(unsigned long, unsigned int*, unsigned int*)+0x10d
V  [libjvm.so+0x58eb2d]  G1CollectedHeap::mem_allocate(unsigned long, bool*)+0x1ad
V  [libjvm.so+0xa9dc07]  TypeArrayKlass::allocate_common(int, bool, Thread*)+0x147
V  [libjvm.so+0x9bffe6]  OptoRuntime::new_array_nozero_C(Klass*, int, JavaThread*)+0x26
v  ~RuntimeStub::_new_array_nozero_Java
J 5702 C2 java.io.ByteArrayOutputStream.write([BII)V (66 bytes) @ 0x00007f8b494fae8c [0x00007f8b494faa80+0x40c]
J 22217 C2 plan.com.maxmind.db.BufferHolder.<init>(Ljava/io/InputStream;)V (71 bytes) @ 0x00007f8b4af8edb4 [0x00007f8b4af8eb80+0x234]
J 22049 C1 plan.com.maxmind.geoip2.DatabaseReader.<init>(Lplan/com/maxmind/geoip2/DatabaseReader$Builder;)V (93 bytes) @ 0x00007f8b4ae8a804 [0x00007f8b4ae8a3e0+0x424]
J 22044 C1 com.djrapitops.plan.gathering.geolocation.GeoLite2Geolocator.getCountry(Ljava/net/InetAddress;)Ljava/util/Optional; (255 bytes) @ 0x00007f8b4b334314 [0x00007f8b4b333740+0xbd4]
J 22043 C1 com.djrapitops.plan.gathering.geolocation.Geolocator.getCountry(Ljava/lang/String;)Ljava/util/Optional; (18 bytes) @ 0x00007f8b496090d4 [0x00007f8b49608f00+0x1d4]
J 22759 C1 com.djrapitops.plan.gathering.geolocation.GeolocationCache$$Lambda$1127.apply(Ljava/lang/Object;)Ljava/lang/Object; (12 bytes) @ 0x00007f8b4ae869f4 [0x00007f8b4ae86780+0x274]
J 22758 C1 plan.com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14([Ljava/lang/Object;Ljava/util/function/Function;Ljava/lang/Object;[J[I[Ljava/lang/Object;[Ljava/lang/Object;[Lplan/com/github/benmanes/caffeine/cache/RemovalCause;[Lplan/com/github/benmanes/caffeine/cache/Node;Ljava/lang/Object;Lplan/com/github/benmanes/caffeine/cache/Node;)Lplan/com/github/benmanes/caffeine/cache/Node; (355 bytes) @ 0x00007f8b4b853d34 [0x00007f8b4b853bc0+0x174]
J 21877 C1 plan.com.github.benmanes.caffeine.cache.BoundedLocalCache$$Lambda$1128.apply(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (49 bytes) @ 0x00007f8b4c166314 [0x00007f8b4c166100+0x214]
J 22624 C2 java.util.concurrent.ConcurrentHashMap.compute(Ljava/lang/Object;Ljava/util/function/BiFunction;)Ljava/lang/Object; (617 bytes) @ 0x00007f8b4cd69040 [0x00007f8b4cd68d80+0x2c0]
J 21874 C1 plan.com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(Ljava/lang/Object;Ljava/lang/Object;Ljava/util/function/Function;[JZ)Ljava/lang/Object; (276 bytes) @ 0x00007f8b4a7d860c [0x00007f8b4a7d7e40+0x7cc]
J 22428 C1 plan.com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(Ljava/lang/Object;Ljava/util/function/Function;ZZ)Ljava/lang/Object; (161 bytes) @ 0x00007f8b4b886884 [0x00007f8b4b885580+0x1304]
J 22427 C1 plan.com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(Ljava/lang/Object;Ljava/util/function/Function;)Ljava/lang/Object; (11 bytes) @ 0x00007f8b4cca0b14 [0x00007f8b4cca0a00+0x114]
J 22426 C1 plan.com.github.benmanes.caffeine.cache.LocalManualCache.get(Ljava/lang/Object;Ljava/util/function/Function;)Ljava/lang/Object; (14 bytes) @ 0x00007f8b4cb3c4dc [0x00007f8b4cb3c320+0x1bc]
J 22422 C1 com.djrapitops.plan.gathering.listeners.bungee.PlayerOnlineListener$$Lambda$1125.apply(Ljava/lang/Object;)Ljava/lang/Object; (12 bytes) @ 0x00007f8b4cb3ce24 [0x00007f8b4cb3c8a0+0x584]
J 22420 C1 com.djrapitops.plan.storage.database.transactions.events.GeoInfoStoreTransaction.performOperations()V (43 bytes) @ 0x00007f8b4aa536cc [0x00007f8b4aa53520+0x1ac]
J 19253 C2 com.djrapitops.plan.storage.database.transactions.Transaction.executeTransaction(Lcom/djrapitops/plan/storage/database/SQLDB;)V (164 bytes) @ 0x00007f8b4c251110 [0x00007f8b4c24f9c0+0x1750]
J 19252 C2 com.djrapitops.plan.storage.database.SQLDB$$Lambda$824.get()Ljava/lang/Object; (12 bytes) @ 0x00007f8b4c23e0e4 [0x00007f8b4c23e060+0x84]
J 18771 C2 java.util.concurrent.CompletableFuture$AsyncSupply.run()V (61 bytes) @ 0x00007f8b4bfa9db8 [0x00007f8b4bfa9d00+0xb8]
J 20668 C2 java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V (225 bytes) @ 0x00007f8b4c79880c [0x00007f8b4c7986e0+0x12c]
J 13789 C1 java.util.concurrent.ThreadPoolExecutor$Worker.run()V (9 bytes) @ 0x00007f8b49d56b84 [0x00007f8b49d56a80+0x104]
J 11684 C1 java.lang.Thread.run()V (17 bytes) @ 0x00007f8b4af65284 [0x00007f8b4af65140+0x144]
v  ~StubRoutines::call_stub
V  [libjvm.so+0x68b29a]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0xe1a
V  [libjvm.so+0x688953]  JavaCalls::call_virtual(JavaValue*, KlassHandle, Symbol*, Symbol*, JavaCallArguments*, Thread*)+0x263
V  [libjvm.so+0x688f27]  JavaCalls::call_virtual(JavaValue*, Handle, KlassHandle, Symbol*, Symbol*, Thread*)+0x57
V  [libjvm.so+0x6f68ac]  thread_entry(JavaThread*, Thread*)+0x6c
V  [libjvm.so+0xa86a6b]  JavaThread::thread_main_inner()+0xdb
V  [libjvm.so+0xa86d71]  JavaThread::run()+0x2d1
V  [libjvm.so+0x915052]  java_start(Thread*)+0x102
C  [libpthread.so.0+0x7fa3]  start_thread+0xf3

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
v  ~RuntimeStub::_new_array_nozero_Java
J 5702 C2 java.io.ByteArrayOutputStream.write([BII)V (66 bytes) @ 0x00007f8b494fae8c [0x00007f8b494faa80+0x40c]
J 22217 C2 plan.com.maxmind.db.BufferHolder.<init>(Ljava/io/InputStream;)V (71 bytes) @ 0x00007f8b4af8edb4 [0x00007f8b4af8eb80+0x234]
J 22049 C1 plan.com.maxmind.geoip2.DatabaseReader.<init>(Lplan/com/maxmind/geoip2/DatabaseReader$Builder;)V (93 bytes) @ 0x00007f8b4ae8a804 [0x00007f8b4ae8a3e0+0x424]
J 22044 C1 com.djrapitops.plan.gathering.geolocation.GeoLite2Geolocator.getCountry(Ljava/net/InetAddress;)Ljava/util/Optional; (255 bytes) @ 0x00007f8b4b334314 [0x00007f8b4b333740+0xbd4]
J 22043 C1 com.djrapitops.plan.gathering.geolocation.Geolocator.getCountry(Ljava/lang/String;)Ljava/util/Optional; (18 bytes) @ 0x00007f8b496090d4 [0x00007f8b49608f00+0x1d4]
J 22759 C1 com.djrapitops.plan.gathering.geolocation.GeolocationCache$$Lambda$1127.apply(Ljava/lang/Object;)Ljava/lang/Object; (12 bytes) @ 0x00007f8b4ae869f4 [0x00007f8b4ae86780+0x274]
J 22758 C1 plan.com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14([Ljava/lang/Object;Ljava/util/function/Function;Ljava/lang/Object;[J[I[Ljava/lang/Object;[Ljava/lang/Object;[Lplan/com/github/benmanes/caffeine/cache/RemovalCause;[Lplan/com/github/benmanes/caffeine/cache/Node;Ljava/lang/Object;Lplan/com/github/benmanes/caffeine/cache/Node;)Lplan/com/github/benmanes/caffeine/cache/Node; (355 bytes) @ 0x00007f8b4b853d34 [0x00007f8b4b853bc0+0x174]
J 21877 C1 plan.com.github.benmanes.caffeine.cache.BoundedLocalCache$$Lambda$1128.apply(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (49 bytes) @ 0x00007f8b4c166314 [0x00007f8b4c166100+0x214]
J 22624 C2 java.util.concurrent.ConcurrentHashMap.compute(Ljava/lang/Object;Ljava/util/function/BiFunction;)Ljava/lang/Object; (617 bytes) @ 0x00007f8b4cd69040 [0x00007f8b4cd68d80+0x2c0]
J 21874 C1 plan.com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(Ljava/lang/Object;Ljava/lang/Object;Ljava/util/function/Function;[JZ)Ljava/lang/Object; (276 bytes) @ 0x00007f8b4a7d860c [0x00007f8b4a7d7e40+0x7cc]
J 22428 C1 plan.com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(Ljava/lang/Object;Ljava/util/function/Function;ZZ)Ljava/lang/Object; (161 bytes) @ 0x00007f8b4b886884 [0x00007f8b4b885580+0x1304]
J 22427 C1 plan.com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(Ljava/lang/Object;Ljava/util/function/Function;)Ljava/lang/Object; (11 bytes) @ 0x00007f8b4cca0b14 [0x00007f8b4cca0a00+0x114]
J 22426 C1 plan.com.github.benmanes.caffeine.cache.LocalManualCache.get(Ljava/lang/Object;Ljava/util/function/Function;)Ljava/lang/Object; (14 bytes) @ 0x00007f8b4cb3c4dc [0x00007f8b4cb3c320+0x1bc]
J 22422 C1 com.djrapitops.plan.gathering.listeners.bungee.PlayerOnlineListener$$Lambda$1125.apply(Ljava/lang/Object;)Ljava/lang/Object; (12 bytes) @ 0x00007f8b4cb3ce24 [0x00007f8b4cb3c8a0+0x584]
J 22420 C1 com.djrapitops.plan.storage.database.transactions.events.GeoInfoStoreTransaction.performOperations()V (43 bytes) @ 0x00007f8b4aa536cc [0x00007f8b4aa53520+0x1ac]
J 19253 C2 com.djrapitops.plan.storage.database.transactions.Transaction.executeTransaction(Lcom/djrapitops/plan/storage/database/SQLDB;)V (164 bytes) @ 0x00007f8b4c251110 [0x00007f8b4c24f9c0+0x1750]
J 19252 C2 com.djrapitops.plan.storage.database.SQLDB$$Lambda$824.get()Ljava/lang/Object; (12 bytes) @ 0x00007f8b4c23e0e4 [0x00007f8b4c23e060+0x84]
J 18771 C2 java.util.concurrent.CompletableFuture$AsyncSupply.run()V (61 bytes) @ 0x00007f8b4bfa9db8 [0x00007f8b4bfa9d00+0xb8]... (164 KB left)
```

**Comment by AuroraLS3** [comment]
Could you test if the new dev release has improved the situation https://github.com/plan-player-analytics/Plan/releases/tag/5.4.1536
