### ISSUE TITLE
FloodgateBungeeListener error with Plan on latest

### ISSUE THREAD

**Issue by vijaypondini** [plan-player-analytics/Plan#2004]
### Describe the issue

There is an error at the proxy for trying to load in a player's customized skin. After review with the geyser team ( posting an issue in their github when i had many spammy errors ), there was only this remaining, which is in relation to player analytics, so here i am, Refer to this issue at - https://github.com/GeyserMC/Geyser/issues/2380#issuecomment-879450834
Running on Waterfall version git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445 

### Exceptions & other logs

`
[04:04:52 INFO] [floodgate]: Floodgate player logged in as _Phobetor1687 joined (UUID: 00000000-0000-0000-0009-01fbc3122541) [04:04:52 INFO] [Geyser-BungeeCord]: Registering bedrock skin for _Phobetor1687 (00000000-0000-0000-0009-01fbc3122541) [04:04:52 WARN]: Error dispatching event PostLoginEvent(player=_Phobetor1687) to listener com.djrapitops.extension.FloodgateBungeeListener@4f4a7083 java.lang.LinkageError: loader constraint violation: when resolving interface method 'org.geysermc.floodgate.util.LinkedPlayer org.geysermc.floodgate.api.player.FloodgatePlayer.getLinkedPlayer()' the class loader net.md_5.bungee.api.plugin.PluginClassloader @78c1372d of the current class, com/djrapitops/extension/FloodgateBungeeListener, and the class loader net.md_5.bungee.api.plugin.PluginClassloader @73ba6fe6 for the method's defining class, org/geysermc/floodgate/api/player/FloodgatePlayer, have different Class objects for the type org/geysermc/floodgate/util/LinkedPlayer used in the signature (com.djrapitops.extension.FloodgateBungeeListener is in unnamed module of loader net.md_5.bungee.api.plugin.PluginClassloader @78c1372d, parent loader 'app'; org.geysermc.floodgate.api.player.FloodgatePlayer is in unnamed module of loader net.md_5.bungee.api.plugin.PluginClassloader @73ba6fe6, parent loader 'app') at com.djrapitops.extension.FloodgateBungeeListener.onLogin(FloodgateBungeeListener.java:62) ~[?:?] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445] at net.md_5.bungee.event.EventBus.post(EventBus.java:48) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445] at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:466) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445] at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:549) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445] at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445] at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445] at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445] at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445] at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445] at java.lang.Thread.run(Thread.java:831) [?:?]
`

### Plugin versions

![image](https://user-images.githubusercontent.com/70318494/125534635-33b166df-5be8-43db-8318-d21af3cc5ee1.png)

### Additional information

Had recently updated geyser and floodgate to support 1.17.10.04 update, so yeah.

**Comment by Kopo942** [comment]
This is a Floodgate issue: GeyserMC/Floodgate#178

**Comment by AuroraLS3** [comment]
I dunno if I can do anything other than just ignoring the exceptions, but that seems pretty pointless since no data will come out anyway while failing silently

**Comment by vijaypondini** [comment]
Is it possible regardless to ignore it for now? If you check out that floodgate issue they don't plan to fix it anytime soon ( I had asked ) and my proxy has been crying for so long with this error :/

**Comment by AuroraLS3** [comment]
> add this ignore in the next update?

Yep

**Comment by AuroraLS3** [comment]
### TODO

- Add catch clause to the Floodgate Extension listeners that ignores this error
- Bump extension version
- Release extension
- Update extension version in Plan
