### ISSUE TITLE
MySql driver....

### ISSUE THREAD

**Issue by 1stian** [plan-player-analytics/Plan#2034]
### Question

Hello, I'm recieving that I need to install a mysql driver on my server?
There is a local mysql serve running on the same machine... But what and where do I need to install a "driver" for it?

https://pastebin.com/ETEBi8jM
`[23:21:39 INFO]: [Plan] Processing complete.
[23:21:39 INFO]: [Plan] Player Analytics Disabled.
[23:21:39 WARN]: [Plan] Ran into EnableException - logged to plugins/Plan/logs/EnableException-e9d30d80a7.txt
[23:21:39 WARN]: [Plan] (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[23:21:39 WARN]: [Plan] Error msg: "Database failed to open, Query has failed. (This exception is necessary to not keep query threads waiting)"
[23:21:39 INFO]: [Plan] 
[23:21:39 INFO]: [Plan]            ???
[23:21:39 INFO]: [Plan]      ???   ???
[23:21:39 INFO]: [Plan]   ????????????  Player Analytics
[23:21:39 INFO]: [Plan]   ????????????  v5.3 build 1284
[23:21:39 INFO]: [Plan] 
[23:21:39 INFO]: [Plan] Locale: 'English' by AuroraLS3
[23:21:39 ERROR]: [Plan] Ran into ClassNotFoundException - logged to plugins/Plan/logs/ClassNotFoundException-ed16cc9100.txt
[23:21:39 ERROR]: [Plan] (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[23:21:39 ERROR]: [Plan] What to do: Install MySQL Driver to the server
[23:21:39 ERROR]: [Plan] CRITICAL error triggered a plugin shutdown.
[23:21:39 INFO]: [Plan] Processing complete.
[23:21:39 INFO]: [Plan] Waiting for unfinished transactions to avoid data loss..
[23:21:39 INFO]: [Plan] Transaction queue closed.
[23:21:39 INFO]: [Plan] Player Analytics Disabled.
[23:21:39 ERROR]: [Plan] Plan-v5.3 build 1284
java.lang.RuntimeException: Failed to load driver class plan.com.mysql.cj.jdbc.Driver in either of HikariConfig class loader or Thread context classloader
        at plan.com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:491) ~[?:?]
        at com.djrapitops.plan.storage.database.MySQLDB.setupDataSource(MySQLDB.java:103) ~[?:?]
        at com.djrapitops.plan.storage.database.SQLDB.init(SQLDB.java:108) ~[?:?]
        at com.djrapitops.plan.storage.database.DBSystem.enable(DBSystem.java:92) ~[?:?]
        at com.djrapitops.plan.storage.database.BukkitDBSystem.enable(BukkitDBSystem.java:58) ~[?:?]
        at com.djrapitops.plan.PlanSystem.enableSystems(PlanSystem.java:189) ~[?:?]
        at com.djrapitops.plan.PlanSystem.enable(PlanSystem.java:160) ~[?:?]
        at com.djrapitops.plan.Plan.onEnable(Plan.java:85) ~[?:?]
        at com.djrapitops.plan.commands.subcommands.PluginStatusCommands.lambda$onReload$0(PluginStatusCommands.java:72) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[23:21:39 ERROR]: [Plan] Plugin Failed to Initialize Correctly. If this issue is caused by config settings you can use /plan reload
[23:21:39 ERROR]: [Plan] This error should be reported at https://github.com/plan-player-analytics/Plan/issues`

Thanks in advance!

**Comment by Kopo942** [comment]
This might be caused by using Java 16 & an outdated version of Plan. Please update to the latest release and see if that fixes the issue.

**Comment by 1stian** [comment]
My bad, works like a charm now! Ty
