### ISSUE TITLE
Plugin Failed to Initialize Correctly - MineOS FreeNAS

### ISSUE THREAD

**Issue by OskarKaptacz** [plan-player-analytics/Plan#2086]
### Describe the issue

```
[12:05:09] [Server thread/ERROR]: [Plan] Plan-v5.4 build 1366
--
com.djrapitops.plan.exceptions.database.DBOpException: Transaction tried to execute although database is closed.
at com.djrapitops.plan.storage.database.SQLDB.executeTransaction(SQLDB.java:257) ~[Plan-5.4-build-1366.jar:?]
at com.djrapitops.plan.identification.storage.ServerDBLoader.save(ServerDBLoader.java:63) ~[Plan-5.4-build-1366.jar:?]
at com.djrapitops.plan.identification.ServerServerInfo.registerNew(ServerServerInfo.java:103) ~[Plan-5.4-build-1366.jar:?]
at com.djrapitops.plan.identification.ServerServerInfo.registerNew(ServerServerInfo.java:98) ~[Plan-5.4-build-1366.jar:?]
at java.util.Optional.orElseGet(Optional.java:364) ~[?:?]
at com.djrapitops.plan.identification.ServerServerInfo.loadServerInfo(ServerServerInfo.java:81) ~[Plan-5.4-build-1366.jar:?]
at com.djrapitops.plan.identification.ServerInfo.enable(ServerInfo.java:59) ~[Plan-5.4-build-1366.jar:?]
at com.djrapitops.plan.PlanSystem.enableSystems(PlanSystem.java:189) ~[Plan-5.4-build-1366.jar:?]
at com.djrapitops.plan.PlanSystem.enable(PlanSystem.java:160) ~[Plan-5.4-build-1366.jar:?]
at com.djrapitops.plan.Plan.onEnable(Plan.java:77) ~[Plan-5.4-build-1366.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-261]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-261]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-261]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:535) ~[patched_1.17.1.jar:git-Paper-261]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:449) ~[patched_1.17.1.jar:git-Paper-261]
at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:725) ~[patched_1.17.1.jar:git-Paper-261]
at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-261]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1212) ~[patched_1.17.1.jar:git-Paper-261]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-261]
at java.lang.Thread.run(Thread.java:831) [?:?]
[12:05:09] [Server thread/ERROR]: [Plan] Plugin Failed to Initialize Correctly. If this issue is caused by config settings you can use /plan reload
[12:05:09] [Server thread/ERROR]: [Plan] This error should be reported at https://github.com/plan-player-analytics/Plan/issues
```

### Exceptions & other logs

[AccessDeniedException-93f76e9e6a.txt](https://github.com/plan-player-analytics/Plan/files/7164525/AccessDeniedException-93f76e9e6a.txt)

### Plugin versions

v5.4 build 1366

### Additional information

Is that permision issue?

**Comment by AuroraLS3** [comment]
Yes, seems like Plan doesn't have read permissions to its own folders

**Comment by OskarKaptacz** [comment]
> Yes, seems like Plan doesn't have read permissions to its own folders

Do you know how can i give it permissions in freeNas?

**Comment by AuroraLS3** [comment]
No idea I'm afraid, try searching the internet 🤔

**Comment by OskarKaptacz** [comment]
I Think i fixed permissions but now I have this error.
Here is logs
[CompletionException-8bb90298d9.txt](https://github.com/plan-player-analytics/Plan/files/7171929/CompletionException-8bb90298d9.txt)
And my config
[config copy.txt](https://github.com/plan-player-analytics/Plan/files/7171937/config.copy.txt)

**Comment by AuroraLS3** [comment]
Error says SQLite is having issues with the OS file system. You could try using mysql if it is available for that OS

**Comment by OskarKaptacz** [comment]
I set up database and now everything work. Thx for help

MySQL tutorial for free nas: [https://www.truenas.com/community/threads/successful-install-of-mysql-in-jail-on-freenas-11-2.87397/](url)
