### ISSUE TITLE
New runtime dependency downloader breaks some Mysql usage.

### ISSUE THREAD

**Issue by Aurelien30000** [plan-player-analytics/Plan#2147]
### Describe the issue

Although the new dependency downloader system is excellent, it seems to cause problems with other plugins using Mysql. Here is the experienced error with another plugin. Notice that all affected plugins are loaded **after** Plan.

Thanks ;)

### Exceptions & other logs

```text
[17:58:30 INFO]: [GadgetsMenu] ------------------------------------------------------
[17:58:31 INFO]: [GadgetsMenu] Connecting to MySQL database...
[17:58:31 INFO]: [GadgetsMenu] --------------------------------------------------
[17:58:31 INFO]: [GadgetsMenu] Failed to connect to MySQL database!
[17:58:31 INFO]: [GadgetsMenu] --------------------------------------------------
[17:58:31 WARN]: java.sql.SQLException: No suitable driver found for jdbc:mysql://172.17.0.1:3306/s1_gadgetsmenu?&autoReconnect=true&wait_timeout=31536000&interactive_timeout=31536000&useUnicode=true&characterEncoding=utf8&useSSL=false
[17:58:31 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702)
[17:58:31 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
[17:58:31 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.database.mysql.MySQLConnection.openConnection(MySQLConnection.java:56)
[17:58:31 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.database.mysql.MySQLManager.init(MySQLManager.java:69)
[17:58:31 WARN]:        at GadgetsMenu.jar//com.yapzhenyie.GadgetsMenu.GadgetsMenu.onEnable(GadgetsMenu.java:352)
[17:58:31 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[17:58:31 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[17:58:31 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[17:58:31 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
[17:58:31 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
[17:58:31 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:730)
[17:58:31 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:317)
[17:58:31 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1217)
[17:58:31 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[17:58:31 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[17:58:31 INFO]: [GadgetsMenu] Disabling GadgetsMenu v5.0.9
```

### Plugin versions

Plan-5.4.1490
Paper-372

**Comment by AuroraLS3** [comment]
Yep looks like Plan unregisters the main MySQL driver due to trying to prevent other plugins using Plan mysql driver which was previously relocated.
I'll get an update out asap tomorrow.

Vankka had some good ideas of the cause so should be pretty simple fix

> Might need to check the classloader here: https://github.com/plan-player-analytics/Plan/blob/efd3b75a2995200785b3a379a86bde803d15e11a/Plan/common/src/main/java/com/djrapitops/plan/storage/database/MySQLDB.java#L156
it was previously relocated so that wasn't a issue before
`&& driver.getClass().getClassLoader() == driverClassLoader` should do the trick
