### ISSUE TITLE
Interrupted during connection acquisition [MySQL]

### ISSUE THREAD

**Issue by ostermine** [plan-player-analytics/Plan#2188]
### Describe the issue

Using WaterfallMC git:cmd_alert:1.18-R0.1-SNAPSHOT, using MySQL, error on start server, on connect to DB 

`com.djrapitops.plan.exceptions.database.DBOpException: SQL Failure: Plan Connection Pool-1 - Interrupted during connection acquisition`

### Exceptions & other logs

```text
3995e6d786 - Last occurred: 2021-12-04 Occurrences: 1
---- Context 1 ----
Plan v5.4 build 1516
BungeeCord 0.6.5
Server v0.6.5

Error code: 0
SELECT * FROM plan_cookies JOIN plan_security on plan_cookies.web_username=plan_security.username LEFT JOIN plan_users on linked_to_uuid=uuid WHERE expires>?
Unknown SQL Error code

---- Stacktrace ----
com.djrapitops.plan.exceptions.database.DBOpException: SQL Failure: Plan Connection Pool-1 - Interrupted during connection acquisition
   com.djrapitops.plan.exceptions.database.DBOpException.forCause(DBOpException.java:135)
   com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:54)
   com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:275)
   com.djrapitops.plan.delivery.webserver.auth.ActiveCookieStore.loadActiveCookies(ActiveCookieStore.java:88)
   com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:78)
   java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
   java.base/java.lang.Thread.run(Thread.java:829)
Caused by:
java.sql.SQLException: Plan Connection Pool-1 - Interrupted during connection acquisition
   plan.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:201)
   plan.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
   plan.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
   com.djrapitops.plan.storage.database.MySQLDB.getConnection(MySQLDB.java:170)
   com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:51)
   com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:275)
   com.djrapitops.plan.delivery.webserver.auth.ActiveCookieStore.loadActiveCookies(ActiveCookieStore.java:88)
   com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:78)
   java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
   java.base/java.lang.Thread.run(Thread.java:829)
Caused by:
java.lang.InterruptedException
   java.base/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:940)
   plan.com.zaxxer.hikari.util.ConcurrentBag.borrow(ConcurrentBag.java:151)
   plan.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:180)
   plan.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
   plan.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
   com.djrapitops.plan.storage.database.MySQLDB.getConnection(MySQLDB.java:170)
   com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:51)
   com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:275)
   com.djrapitops.plan.delivery.webserver.auth.ActiveCookieStore.loadActiveCookies(ActiveCookieStore.java:88)
   com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:78)
   java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
   java.base/java.lang.Thread.run(Thread.java:829)
```

### Plugin versions

Plan-5.4-build-1516

**Comment by AuroraLS3** [comment]
The hikaricp connection pool thread was shutdown for some reason 🤔
I'm a bit unsure why - does this occur every time?

**Comment by ostermine** [comment]
I have no idea -_- , i bought VPS from OVH on ubuntu 18, installed MySQL, created username, password and DB for Plan, tried to log in with login;pass in console, all was succesfully. And then, i started waterfall with Plan, and appeared this error.

**Comment by AuroraLS3** [comment]
Somebody on discord and it seemed to be related to Plan reloads, still investigating further.

**Comment by Pingger** [comment]
I have this (apparently same) issue running 
- Ubuntu Server Core 20.04 
- Waterfall 1.18 `#483`
- Plan 5.4 build 1583

```
7c2a4fb892 - Last occurred: 2022-04-08 Occurrences: 1
---- Context 1 ----
Plan v5.4 build 1583
BungeeCord git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483
Server vgit:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483

Error code: 0
SELECT * FROM plan_cookies JOIN plan_security on plan_cookies.web_username=plan_security.username LEFT JOIN plan_users on linked_to_uuid=uuid WHERE expires>?
Unknown SQL Error code

---- Stacktrace ----
com.djrapitops.plan.exceptions.database.DBOpException: SQL Failure: Plan Connection Pool-1 - Interrupted during connection acquisition
   com.djrapitops.plan.exceptions.database.DBOpException.forCause(DBOpException.java:135)
   com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:54)
   com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:303)
   com.djrapitops.plan.delivery.webserver.auth.ActiveCookieStore.loadActiveCookies(ActiveCookieStore.java:84)
   com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:78)
   java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
   java.base/java.lang.Thread.run(Thread.java:833)
Caused by:
java.sql.SQLException: Plan Connection Pool-1 - Interrupted during connection acquisition
   plan.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:201)
   plan.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
   plan.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
   com.djrapitops.plan.storage.database.MySQLDB.getConnection(MySQLDB.java:170)
   com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:51)
   com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:303)
   com.djrapitops.plan.delivery.webserver.auth.ActiveCookieStore.loadActiveCookies(ActiveCookieStore.java:84)
   com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:78)
   java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
   java.base/java.lang.Thread.run(Thread.java:833)
Caused by:
java.lang.InterruptedException
   java.base/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:906)
   plan.com.zaxxer.hikari.util.ConcurrentBag.borrow(ConcurrentBag.java:151)
   plan.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:180)
   plan.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
   plan.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
   com.djrapitops.plan.storage.database.MySQLDB.getConnection(MySQLDB.java:170)
   com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:51)
   com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:303)
   com.djrapitops.plan.delivery.webserver.auth.ActiveCookieStore.loadActiveCookies(ActiveCookieStore.java:84)
   com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:78)
   java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
   java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by AuroraLS3** [comment]
Does it occur every time or only on first run?

**Comment by AuroraLS3** [comment]
Root cause: Long running query/transaction that is holding all the connections
https://github.com/brettwooldridge/HikariCP/issues/976

**Comment by Pingger** [comment]
Yes it occuring everytime instantly (as in "before full startup even finishes and within a second") on startup. But I just found a fix:  
Changing `Server.IP` from `0.0.0.0` to `10.1.1.103` (the IP of the only network adapter) resolved this ... I have no idea, why this is in any way related to the Database-Connection

**Comment by AuroraLS3** [comment]
Ah the setup was not complete 🤔 https://github.com/plan-player-analytics/Plan/wiki/Bungee-Set-Up#step-1-install

Could you send the full console log for Plan from the time when this error occurred

**Comment by Pingger** [comment]
<details>
<summary>Server - Log</summary>

```

[14:59:20] [main/INFO]: Using mbed TLS based native cipher.
[14:59:20] [main/INFO]: Using zlib based native compressor.
[14:59:20] [main/INFO]: Enabled Waterfall version git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483
[14:59:20] [main/INFO]: Not on Windows, attempting to use enhanced EpollEventLoop
[14:59:20] [main/INFO]: Epoll is working, utilising it!
[14:59:20] [main/INFO]: Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
[14:59:20] [main/INFO]: Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
[14:59:20] [main/INFO]: Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
[14:59:20] [main/INFO]: Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
[14:59:20] [main/INFO]: Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
[14:59:20] [main/INFO]: Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
[14:59:20] [main/INFO]: Loaded plugin reconnect_yaml version git:reconnect_yaml:1.18-R0.1-SNAPSHOT:ba3bbcc:483 by WaterfallMC
[14:59:20] [main/WARN]: Error loading plugin Wartung
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152) ~[waterfall-1.18-483.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66) ~[waterfall-1.18-483.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[waterfall-1.18-483.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:394) ~[waterfall-1.18-483.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483]
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:300) ~[waterfall-1.18-483.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278) ~[waterfall-1.18-483.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall-1.18-483.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.18-483.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483]
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103) ~[waterfall-1.18-483.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[waterfall-1.18-483.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 13 more
[14:59:20] [main/INFO]: Loaded plugin cmd_find version git:cmd_find:1.18-R0.1-SNAPSHOT:ba3bbcc:483 by WaterfallMC
[14:59:20] [main/INFO]: Loaded plugin ViaVersion version 4.2.1 by _MylesC, creeper123123321, Gerrygames, kennytv, Matsv
[14:59:20] [main/INFO]: Loaded plugin AntiBot version 0.6.8 by 2LS
[14:59:20] [main/INFO]: Loaded plugin cmd_server version git:cmd_server:1.18-R0.1-SNAPSHOT:ba3bbcc:483 by WaterfallMC
[14:59:20] [main/INFO]: Loaded plugin cmd_alert version git:cmd_alert:1.18-R0.1-SNAPSHOT:ba3bbcc:483 by WaterfallMC
[14:59:20] [main/INFO]: Loaded plugin Plan version 5.4 build 1583 by AuroraLS3
[14:59:20] [main/INFO]: Loaded plugin cmd_send version git:cmd_send:1.18-R0.1-SNAPSHOT:ba3bbcc:483 by WaterfallMC
[14:59:20] [main/INFO]: Loaded plugin ViaBackwards version 4.2.1 by Matsv, kennytv, Gerrygames, creeper123123321, ForceUpdate1
[14:59:20] [main/INFO]: Loaded plugin cmd_list version git:cmd_list:1.18-R0.1-SNAPSHOT:ba3bbcc:483 by WaterfallMC
[14:59:20] [main/WARN]: Forced host server 1.16 is not defined
[14:59:20] [main/INFO]: Enabled plugin reconnect_yaml version git:reconnect_yaml:1.18-R0.1-SNAPSHOT:ba3bbcc:483 by WaterfallMC
[14:59:20] [main/INFO]: Enabled plugin cmd_find version git:cmd_find:1.18-R0.1-SNAPSHOT:ba3bbcc:483 by WaterfallMC
[14:59:20] [Via-Mappingloader-0/INFO] [ViaVersion]: Loading 1.12 -> 1.13 mappings...
[14:59:20] [Via-Mappingloader-1/INFO] [ViaVersion]: Loading 1.13 -> 1.13.2 mappings...
[14:59:20] [Via-Mappingloader-2/INFO] [ViaVersion]: Loading 1.13.2 -> 1.14 mappings...
[14:59:20] [Via-Mappingloader-3/INFO] [ViaVersion]: Loading 1.14 -> 1.15 mappings...
[14:59:21] [Via-Mappingloader-4/INFO] [ViaVersion]: Loading 1.15 -> 1.16 mappings...
[14:59:21] [Via-Mappingloader-1/INFO] [ViaVersion]: Loading 1.16 -> 1.16.2 mappings...
[14:59:21] [Via-Mappingloader-0/INFO] [ViaVersion]: Loading block connection mappings ...
[14:59:21] [Via-Mappingloader-3/INFO] [ViaVersion]: Loading 1.16.2 -> 1.17 mappings...
[14:59:21] [Via-Mappingloader-2/INFO] [ViaVersion]: Loading 1.17 -> 1.18 mappings...
[14:59:21] [main/INFO] [ViaBackwards]: Loading translations...
[14:59:21] [Via-Mappingloader-1/INFO] [ViaBackwards]: Loading 1.10 -> 1.9.4 mappings...
[14:59:21] [Via-Mappingloader-3/INFO] [ViaBackwards]: Loading 1.11 -> 1.10 mappings...
[14:59:21] [Via-Mappingloader-0/INFO] [ViaBackwards]: Loading 1.12 -> 1.11 mappings...
[14:59:21] [Via-Mappingloader-0/INFO] [ViaBackwards]: Loading 1.13 -> 1.12 mappings...
[14:59:21] [Via-Mappingloader-2/INFO] [ViaBackwards]: Loading 1.13.2 -> 1.13 mappings...
[14:59:21] [Via-Mappingloader-2/INFO] [ViaBackwards]: Loading 1.14 -> 1.13.2 mappings...
[14:59:22] [Via-Mappingloader-0/INFO] [ViaBackwards]: Loading 1.15 -> 1.14 mappings...
[14:59:22] [Via-Mappingloader-0/INFO] [ViaBackwards]: Loading 1.16 -> 1.15 mappings...
[14:59:22] [Via-Mappingloader-2/INFO] [ViaBackwards]: Loading 1.16.2 -> 1.16 mappings...
[14:59:22] [Via-Mappingloader-0/INFO] [ViaBackwards]: Loading 1.17 -> 1.16.2 mappings...
[14:59:22] [Via-Mappingloader-0/INFO] [ViaBackwards]: Loading 1.18 -> 1.17 mappings...
[14:59:22] [ViaVersion Pool Thread #0/INFO] [ViaVersion]: ViaVersion detected lowest supported version by the proxy: 1.8.x (47)
[14:59:22] [ViaVersion Pool Thread #0/INFO] [ViaVersion]: Highest supported version by the proxy: 1.18.2 (758)
[14:59:22] [main/INFO]: Enabled plugin ViaVersion version 4.2.1 by _MylesC, creeper123123321, Gerrygames, kennytv, Matsv
[14:59:22] [main/INFO] [AntiBot]: Configurations successfully created!
[14:59:22] [ViaVersion Pool Thread #2/INFO] [ViaVersion]: Finished mapping loading, shutting down loader executor!
[14:59:22] [main/INFO] [AntiBot]: Modules successfully loaded!
[14:59:22] [main/INFO] [AntiBot]: Listeners successfully registered!
[14:59:22] [main/INFO] [AntiBot]: Commands successfully registered!
[14:59:22] [main/INFO]: Enabled plugin AntiBot version 0.6.8 by 2LS
[14:59:22] [main/INFO]: Enabled plugin cmd_server version git:cmd_server:1.18-R0.1-SNAPSHOT:ba3bbcc:483 by WaterfallMC
[14:59:22] [main/INFO]: Enabled plugin cmd_alert version git:cmd_alert:1.18-R0.1-SNAPSHOT:ba3bbcc:483 by WaterfallMC
[14:59:22] [main/INFO] [Plan]: 
[14:59:22] [main/INFO] [Plan]:            ██▌
[14:59:22] [main/INFO] [Plan]:      ██▌   ██▌
[14:59:22] [main/INFO] [Plan]:   ██▌██▌██▌██▌  Player Analytics
[14:59:22] [main/INFO] [Plan]:   ██▌██▌██▌██▌  v5.4 build 1583
[14:59:22] [main/INFO] [Plan]: 
[14:59:23] [main/INFO] [Plan]: Locale: 'English' by AuroraLS3
[14:59:23] [main/INFO] [Plan]: Downloading MySQL Driver, this may take a while...
[14:59:23] [Plan Pool Thread #1/INFO] [Plan]: You're using the latest version.
[14:59:23] [main/INFO] [Plan]: Database: Making sure schema is up to date..
[14:59:23] [main/INFO] [Plan]: Database: Ready for operation.
[14:59:23] [main/INFO] [Plan]: MySQL-database connection established.
[14:59:23] [main/INFO] [Plan]: WebServer: Proxy-mode HTTPS enabled, make sure that your reverse-proxy is routing using HTTPS and Plan Alternative_IP.Address points to the Proxy
[14:59:23] [main/INFO] [Plan]: Webserver running on PORT 8804 ( https://plan.uedo.eu:443 )
[14:59:23] [main/INFO] [Plan]: Loading server identifying information
[14:59:23] [main/ERROR] [Plan]: IP setting still 0.0.0.0 - Configure Alternative_IP/IP that connects to the Proxy server.
[14:59:23] [main/INFO] [Plan]: Player Analytics partially enabled (Use /planproxy reload to reload config)
[14:59:23] [main/ERROR] [Plan]: ----------------------------------------
[14:59:23] [main/ERROR] [Plan]: Error: IP setting still 0.0.0.0 - Configure Alternative_IP/IP that connects to the Proxy server.
[14:59:23] [main/ERROR] [Plan]: ----------------------------------------
[14:59:23] [main/ERROR] [Plan]: Plugin Failed to Initialize Correctly. If this issue is caused by config settings you can use /planbungee reload
[14:59:23] [main/INFO] [Plan]: Processing complete.
[14:59:23] [main/INFO] [Plan]: Waiting for unfinished transactions to avoid data loss..
[14:59:23] [Plan Non critical-pool-1/WARN] [Plan]: Ran into DBOpException - logged to plugins/Plan/logs/DBOpException-7c2a4fb892.txt
[14:59:23] [Plan Non critical-pool-1/WARN] [Plan]: (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[14:59:23] [Plan Non critical-pool-1/WARN] [Plan]: Error msg: "SQL Failure: Plan Connection Pool-1 - Interrupted during connection acquisition"
[14:59:24] [main/INFO] [Plan]: Transaction queue closed.
[14:59:24] [main/INFO] [Plan]: Webserver has been disabled.
[14:59:24] [main/INFO] [Plan]: Player Analytics Disabled.
[14:59:24] [main/INFO]: Enabled plugin Plan version 5.4 build 1583 by AuroraLS3
[14:59:24] [main/INFO]: Enabled plugin cmd_send version git:cmd_send:1.18-R0.1-SNAPSHOT:ba3bbcc:483 by WaterfallMC
[14:59:24] [main/INFO]: Enabled plugin ViaBackwards version 4.2.1 by Matsv, kennytv, Gerrygames, creeper123123321, ForceUpdate1
[14:59:24] [main/INFO]: Enabled plugin cmd_list version git:cmd_list:1.18-R0.1-SNAPSHOT:ba3bbcc:483 by WaterfallMC
[14:59:24] [Netty Boss IO Thread #0/INFO]: Listening on /0.0.0.0:25565
[14:59:24] [Netty Worker IO Thread #2/INFO]: Started query on /[0:0:0:0:0:0:0:0%0]:25565
[14:59:25] [Netty Worker IO Thread #0/INFO]: [/85.22.100.255:47305] <-> InitialHandler has connected
[14:59:26] [Netty Worker IO Thread #0/INFO]: [GammaCreator|/85.22.100.255:47305] <-> ServerConnector [1.18] has connected
[15:02:35] [main/INFO]: CONSOLE executed command: /end
[15:02:35] [Shutdown Thread/INFO]: Closing listener [id: 0xacb83bd6, L:/[0:0:0:0:0:0:0:0%0]:25565]
[15:02:35] [Shutdown Thread/INFO]: Closing listener [id: 0xa4f4c5a0, L:/[0:0:0:0:0:0:0:0%0]:25565]
[15:02:35] [Shutdown Thread/INFO]: Closing pending connections
[15:02:35] [Shutdown Thread/INFO]: Disconnecting 1 connections
[15:02:35] [Shutdown Thread/INFO]: [GammaCreator] disconnected with: [Proxy] Proxy restarting.
[15:02:35] [Netty Worker IO Thread #0/INFO]: [/85.22.100.255:47305|GammaCreator] -> UpstreamBridge has disconnected
[15:02:35] [Netty Worker IO Thread #0/INFO]: [/85.22.100.255:47305|GammaCreator] <-> DownstreamBridge <-> [1.18] has disconnected
[15:02:35] [Shutdown Thread/INFO]: Saving reconnect locations
[15:02:35] [Shutdown Thread/INFO]: Disabling plugins
[15:02:35] [Shutdown Thread/INFO] [Plan]: Processing complete.
[15:02:35] [Shutdown Thread/INFO] [Plan]: Webserver has been disabled.
[15:02:35] [Shutdown Thread/INFO] [Plan]: Player Analytics Disabled.
[15:02:35] [Shutdown Thread/INFO]: Closing IO threads
[15:02:37] [Shutdown Thread/INFO]: Thank you and goodbye


```

</details>

**Comment by AuroraLS3** [comment]
I see yep, the connection pool closed due to plugin disable but a query tried to execute anyway.

**Comment by AuroraLS3** [comment]
Thanks this has been very useful for figuring out how to deal with this exception
