### ISSUE TITLE
Config error | Exception when players leave the server

### ISSUE THREAD

**Issue by Jarco-dev** [plan-player-analytics/Plan#2193]
### Describe the issue

When a player leaves the server it throws the error below, while in the config it's actually set to `1` and not -1 as it's saying is a bad value

### Exceptions & other logs

```text
[20:08:14] [Craft Scheduler Thread - 56/WARN]: [Plan] Plugin Plan v5.4 build 1516 generated an exception while executing task 27
java.lang.IllegalStateException: Config value for Time.Thresholds.Remove_inactive_player_data_after has a bad value: '-1'
at com.djrapitops.plan.settings.config.PlanConfig.get(PlanConfig.java:81) ~[?:?]
at com.djrapitops.plan.storage.upkeep.DBCleanTask.cleanOldPlayers(DBCleanTask.java:161) ~[?:?]
at com.djrapitops.plan.storage.upkeep.DBCleanTask.run(DBCleanTask.java:113) ~[?:?]
at net.playeranalytics.plugin.scheduling.UnscheduledBukkitTask.run(UnscheduledBukkitTask.java:22) ~[?:?]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3339-Spigot-3c40a6c-581df18]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.18-R0.1-SNAPSHOT.jar:3339-Spigot-3c40a6c-581df18]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
at java.lang.Thread.run(Thread.java:833) [?:?]
[20:33:01] [Server thread/INFO]: Ila1973 lost connection: Disconnected
[20:33:01] [Server thread/INFO]: Ila1973 left the game
[21:08:14] [Craft Scheduler Thread - 62/WARN]: [Plan] Plugin Plan v5.4 build 1516 generated an exception while executing task 27
java.lang.IllegalStateException: Config value for Time.Thresholds.Remove_inactive_player_data_after has a bad value: '-1'
at com.djrapitops.plan.settings.config.PlanConfig.get(PlanConfig.java:81) ~[?:?]
at com.djrapitops.plan.storage.upkeep.DBCleanTask.cleanOldPlayers(DBCleanTask.java:161) ~[?:?]
at com.djrapitops.plan.storage.upkeep.DBCleanTask.run(DBCleanTask.java:113) ~[?:?]
at net.playeranalytics.plugin.scheduling.UnscheduledBukkitTask.run(UnscheduledBukkitTask.java:22) ~[?:?]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3339-Spigot-3c40a6c-581df18]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.18-R0.1-SNAPSHOT.jar:3339-Spigot-3c40a6c-581df18]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
at java.lang.Thread.run(Thread.java:833) [?:?]
```

### Plugin versions

**Plan:** v5.4 build 1516

### Additional information

The line in my config that it's referring to
```
Remove_inactive_player_data_after: 1
```

**Comment by AuroraLS3** [comment]
```
        } catch (IllegalArgumentException e) {
            return -1L;
        }
```

The given `.Unit` is not supported - It only supports `MILLISECONDS, SECONDS, MINUTES, HOURS, DAYS` (case insensitive)
I guess I should throw different error instead
