### ISSUE TITLE
Restart Error 1.18 [Shutdown hook thread runs after class unloading]

### ISSUE THREAD

**Issue by IceWaffles** [plan-player-analytics/Plan#2198]
### Describe the issue

This happens whenever restarting the server. Error attached below.

### Exceptions & other logs

```text
[19:22:54 WARN]: Exception in thread "Thread-14" java.lang.BootstrapMethodError: java.lang.IllegalStateException: zip file closed
[19:22:54 WARN]:        at Plan-5.4-build-1516.jar//com.djrapitops.plan.gathering.domain.PlayerKills.toJson(PlayerKills.java:87)
[19:22:54 WARN]:        at Plan-5.4-build-1516.jar//com.djrapitops.plan.gathering.domain.FinishedSession.serializeCSV(FinishedSession.java:200)
[19:22:54 WARN]:        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[19:22:54 WARN]:        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[19:22:54 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[19:22:54 WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[19:22:54 WARN]:        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[19:22:54 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[19:22:54 WARN]:        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[19:22:54 WARN]:        at Plan-5.4-build-1516.jar//com.djrapitops.plan.gathering.ShutdownDataPreservation.storeFinishedSessions(ShutdownDataPreservation.java:148)
[19:22:54 WARN]:        at Plan-5.4-build-1516.jar//com.djrapitops.plan.gathering.ShutdownDataPreservation.preserveSessionsInCache(ShutdownDataPreservation.java:139)
[19:22:54 WARN]:        at Plan-5.4-build-1516.jar//com.djrapitops.plan.gathering.ShutdownHook.run(ShutdownHook.java:67)
[19:22:54 WARN]: Caused by: java.lang.IllegalStateException: zip file closed
[19:22:54 WARN]:        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
[19:22:54 WARN]:        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
[19:22:54 WARN]:        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
[19:22:54 WARN]:        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
[19:22:54 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163)
[19:22:54 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[19:22:54 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
```

### Plugin versions

Latest build from SpigotMC, latest PaperMC 1.18 build (#64)

**Comment by AuroraLS3** [comment]
Looks like class unloading is even more aggressive than before causing the shutdown session csv write to fail.

I'm unsure if this breaks everything, since the sessions are attempted to be saved when plugin shutdowns during server shutdown, but this breaks shutdown session saving if that is broken.

Could you check if sessions that are active (player logged in) while you shutdown are stored?

**Comment by IceWaffles** [comment]
How/where should I find if the active sessions are stored upon restarting/shutting down?

**Comment by AuroraLS3** [comment]
Look at `/server/<name>` > Sessions for the list of sessions before shutdown and then compare after restarting to see if the sessions are still there or if they went missing

**Comment by IceWaffles** [comment]
I'm confused; in which directory/server file is that in?

**Comment by AuroraLS3** [comment]
`<plan address>/server/<server name>` > Online Activity > Sessions on the website

**Comment by AuroraLS3** [comment]
I could not reproduce the issue with Paper or Spigot 1.18.1.
Zip closed suggests that the jar file was replaced while the server was running.

The issue could have been during enable, if the issue persists please open a new ticket

**Comment by AuroraLS3** [comment]
Another user reported this on discord so I have reopened the issue.
https://pastebin.com/raw/wisqBk08

Paper Jar: paper-1.18.1-175.jar
/version output: This server is running Paper version git-Paper-175 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 9490475)
Java Version: Java 17 (Linux, running in a container from a Pterodactyl panel instance)

Their server was successfully saving sessions on shutdown despite the error so this is not a super critical bug

**Comment by Vankka** [comment]
Bukkit unloads the plugin jar once `onDisable` has been called. So since ShutdownHook is a asynchronous task, if it needs to load a class it will fail because the plugin jar has already been unloaded when it runs

**Comment by AuroraLS3** [comment]
I wonder if adding a static variable to hold one instance of the object being saved could keep the necessary classes loaded until JVM shutdown, since the shutdown hook seems to have some of the classes loaded regardless.

(gets all the way to [here](https://github.com/plan-player-analytics/Plan/blob/ecff80978538c20c643070bb4a6716bf85a7e088/Plan/common/src/main/java/com/djrapitops/plan/gathering/ShutdownDataPreservation.java#L148) before needing to re-load a class (I think either FinishedSession or PlayerKill))

**Comment by Vankka** [comment]
Any class that is already loaded before onDisable wouldn't be a issue, since garbage controller won't clear those until that Thread is no longer referenced anywhere

**Comment by AuroraLS3** [comment]
I kinda now realized that if garbage collector manages to run before the shutdown thread the sessions it's about to save would likely be wiped out after SessionCache class and it's static variable holding the sessions are cleaned
