### ISSUE TITLE
Crash on startup 

### ISSUE THREAD

**Issue by SnowBlitzz** [plan-player-analytics/Plan#2202]
### Describe the issue

The server crashes on startup with the crash log attached below

### Exceptions & other logs

```text
https://pastebin.com/6ze3gQN7
```

### Plugin versions

SpongeForge 7.4.2
Forge 2860
Plan-5.4-build-1516

**Comment by AuroraLS3** [comment]
Seems like forge class was loaded wrong somehow 🤔
I don't know how Plan could have caused that

**Comment by JoeyEamigh** [comment]
+1 - no crash without Plan and crashes with plan - same exeption

**Comment by AuroraLS3** [comment]
Okay it is probably some META-INF class thing again..

**Comment by AuroraLS3** [comment]
Reproduced the issue with just 
```
SpongeForge 7.4.7 2838
Forge 14.23.5.2860
Plan 5.4 build 1563
```
```
2022-02-01 16:47:10,201 main WARN Disabling terminal, you're running in an unsupported environment.
[16:47:10] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[16:47:10] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[16:47:10] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
[16:47:10] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[16:47:10] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_241, running on Windows 10:amd64:10.0, installed at S:\Programming Env Tools\Java\jdk8_u241\jre
[16:47:10] [main/INFO] [FML]: Searching D:\Minecraft Servers\SpongeForge-2860\.\mods for mods
[16:47:10] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from spongeforge-1.12.2-2838-7.4.7.jar
[16:47:10] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:47:10] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[16:47:10] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/D:/Minecraft%20Servers/SpongeForge-2860/./mods/spongeforge-1.12.2-2838-7.4.7.jar Service=LaunchWrapper Env=SERVER
[16:47:10] [main/WARN] [FML]: The coremod SpongeCoremod (org.spongepowered.mod.SpongeCoremod) is not signed!
[16:47:10] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[16:47:10] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[16:47:10] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:47:10] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:47:10] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:47:11] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[16:47:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:47:11] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[16:47:11] [main/INFO] [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@5942ee04
[16:47:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[16:47:12] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[16:47:12] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[16:47:12] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[16:47:12] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[16:47:13] [main/WARN] [mixin]: @Mixin target net/minecraft/block/state/BlockStateContainer$StateImplementation is public in mixins.common.api.json:mcp.block.state.StateImplementationMixin_API and should be specified in value
[16:47:15] [main/WARN] [mixin]: Static binding violation: PRIVATE @Overwrite method func_189509_E in mixins.common.core.json:world.WorldMixin cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.
[16:47:16] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[16:47:21] [Server thread/INFO] [minecraft/DedicatedServer]: Starting minecraft server version 1.12.2
[16:47:21] [Server thread/INFO] [FML]: MinecraftForge v14.23.5.2860 Initialized
[16:47:21] [Server thread/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[16:47:21] [Server thread/INFO] [FML]: Invalid recipe found with multiple oredict ingredients in the same ingredient...
[16:47:21] [Server thread/INFO] [FML]: Replaced 1227 ore ingredients
[16:47:21] [Server thread/INFO] [Sponge]: Found mcmod.info at jar:file:/D:/Minecraft%20Servers/SpongeForge-2860/./mods/spongeforge-1.12.2-2838-7.4.7.jar!/mcmod.info
[16:47:21] [Server thread/INFO] [Sponge]: Creating injector in stage 'PRODUCTION'
[16:47:24] [Server thread/INFO] [FML]: Searching D:\Minecraft Servers\SpongeForge-2860\.\mods for mods
[16:47:24] [Server thread/INFO] [FML]: Forge Mod Loader has identified 8 mods to load
[16:47:24] [Server thread/WARN] [FML]: Missing English translation for FML: assets/fml/lang/en_us.lang
[16:47:24] [Server thread/WARN] [FML]: Missing English translation for spongeapi: assets/spongeapi/lang/en_us.lang
[16:47:24] [Server thread/WARN] [FML]: Missing English translation for spongeforge: assets/spongeforge/lang/en_us.lang
[16:47:24] [Server thread/WARN] [FML]: Missing English translation for plan: assets/plan/lang/en_us.lang
[16:47:24] [Server thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, spongeapi, sponge, spongeforge, plan] at CLIENT
[16:47:24] [Server thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, spongeapi, sponge, spongeforge, plan] at SERVER
[16:47:25] [Server thread/WARN] [Sponge]: There's no certificate fingerprint available
[16:47:25] [Server thread/INFO] [FML]: Processing ObjectHolder annotations
[16:47:25] [Server thread/INFO] [FML]: Found 1168 ObjectHolder annotations
[16:47:25] [Server thread/INFO] [FML]: Identifying ItemStackHolder annotations
[16:47:25] [Server thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[16:47:25] [Server thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[16:47:25] [Forge Version Check/INFO] [forge.VersionCheck]: [spongeforge] Starting version check at https://files.minecraftforge.net/maven/org/spongepowered/spongeforge/promotions_slim.json
[16:47:25] [Server thread/INFO] [org.spongepowered.mod.SpongeMod]: Log test
[16:47:26] [Server thread/INFO] [plan]:
Plugin Plan is using bStats Metrics  but currently has data sending disabled.
To change the enabled/disabled state of any bStats use in a plugin, visit the Sponge config!
[16:47:26] [Server thread/INFO] [FML]: Applying holder lookups
[16:47:26] [Server thread/INFO] [FML]: Holder lookups applied
[16:47:26] [Server thread/INFO] [FML]: Applying holder lookups
[16:47:26] [Server thread/INFO] [FML]: Holder lookups applied
[16:47:26] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `sponge` for name `human`, expected `spongeforge`. This could be a intended override, but in most cases indicates a broken mod.
[16:47:26] [Server thread/INFO] [FML]: Applying holder lookups
[16:47:26] [Server thread/INFO] [FML]: Holder lookups applied
[16:47:26] [Server thread/INFO] [FML]: Applying holder lookups
[16:47:26] [Server thread/INFO] [FML]: Holder lookups applied
[16:47:26] [Server thread/INFO] [FML]: Injecting itemstacks
[16:47:26] [Server thread/INFO] [FML]: Itemstack injection complete
[16:47:26] [Server thread/INFO] [minecraft/DedicatedServer]: Loading properties
[16:47:26] [Server thread/INFO] [minecraft/DedicatedServer]: Default game type: SURVIVAL
[16:47:26] [Server thread/INFO] [minecraft/DedicatedServer]: Generating keypair
[16:47:26] [Server thread/INFO] [minecraft/DedicatedServer]: Starting Minecraft server on *:25565
[16:47:26] [Server thread/INFO] [minecraft/NetworkSystem]: Using default channel type
[16:47:26] [Server thread/INFO] [FML]: Applying holder lookups
[16:47:26] [Server thread/INFO] [FML]: Holder lookups applied
[16:47:27] [Server thread/INFO] [FML]: Injecting itemstacks
[16:47:27] [Server thread/INFO] [FML]: Itemstack injection complete
[16:47:27] [Forge Version Check/INFO] [forge.VersionCheck]: [spongeforge] Found status: OUTDATED Target: 7.1.2
[16:47:27] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[16:47:27] [Server thread/INFO] [FML]: Forge Mod Loader has successfully loaded 8 mods
[16:47:27] [Server thread/INFO] [minecraft/DedicatedServer]: Preparing level "world"
[16:47:27] [Server thread/INFO] [Sponge]: Checking for worlds that need to be migrated...
[16:47:27] [Server thread/INFO] [Sponge]: No worlds were found in need of migration.
[16:47:27] [Server thread/INFO] [FML]: Injecting existing registry data into this server instance
[16:47:27] [Server thread/INFO] [FML]: Applying holder lookups
[16:47:27] [Server thread/INFO] [FML]: Holder lookups applied
[16:47:27] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Found status: AHEAD Target: null
[16:47:27] [Server thread/INFO] [minecraft/AdvancementList]: Loaded 488 advancements
[16:47:27] [Server thread/INFO] [minecraft/AdvancementList]: Loaded 6 advancement trees
[16:47:28] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing start region for world world (minecraft:overworld/0)
[16:47:29] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 25%
[16:47:30] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 51%
[16:47:31] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 85%
[16:47:31] [Server thread/INFO] [Sponge]: Loading world [world] (minecraft:overworld/0)
[16:47:31] [Server thread/INFO] [minecraft/AdvancementList]: Loaded 488 advancements
[16:47:31] [Server thread/INFO] [minecraft/AdvancementList]: Loaded 6 advancement trees
[16:47:31] [Server thread/INFO] [Sponge]: Loading world [DIM-1] (minecraft:nether/-1)
[16:47:31] [Server thread/INFO] [minecraft/AdvancementList]: Loaded 488 advancements
[16:47:31] [Server thread/INFO] [minecraft/AdvancementList]: Loaded 6 advancement trees
[16:47:31] [Server thread/INFO] [Sponge]: Loading world [DIM1] (minecraft:the_end/1)
[16:47:31] [Server thread/INFO] [minecraft/DedicatedServer]: Done (4,386s)! For help, type "help" or "?"
[16:47:32] [Server thread/INFO] [plan]:
[16:47:32] [Server thread/INFO] [plan]:            ██?
[16:47:32] [Server thread/INFO] [plan]:      ██?   ██?
[16:47:32] [Server thread/INFO] [plan]:   ██?██?██?██?  Player Analytics
[16:47:32] [Server thread/INFO] [plan]:   ██?██?██?██?  v5.4 build 1563
[16:47:32] [Server thread/INFO] [plan]:
[16:47:32] [Server thread/WARN] [plan]: ! ------- Deprecation warning ------- !
[16:47:32] [Server thread/WARN] [plan]: Plan version 5.5 will require Java 11 or newer,
[16:47:32] [Server thread/WARN] [plan]: consider updating your JVM as soon as possible.
[16:47:32] [Server thread/WARN] [plan]: ! ----------------------------------- !
[16:47:32] [Server thread/INFO] [plan]: Locale: 'English' by AuroraLS3
[16:47:32] [Server thread/INFO] [plan]: Downloading SQLite Driver, this may take a while...
[16:47:33] [pool-2-thread-1/INFO] [plan]: You're using the latest version.
[16:47:34] [Server thread/INFO] [plan]: SQLite-database connection established.
[16:47:34] [Server thread/INFO] [plan]: WebServer: Certificate KeyStore File not Found: D:\Minecraft Servers\SpongeForge-2860\.\config\plan\Cert.jks
[16:47:34] [Server thread/INFO] [plan]: WebServer: No Certificate -> Using HTTP-server for Visualization.
[16:47:34] [Server thread/INFO] [plan]: WebServer: User Authorization Disabled! (Not secure over HTTP)
[16:47:34] [Server thread/INFO] [plan]: Webserver running on PORT 8804 ( http://127.0.0.1:8804 )
[16:47:34] [Server thread/INFO] [plan]: Loading server identifying information
[16:47:34] [pool-2-thread-2/WARN] [plan]: Downloading GeoLite2 requires accepting GeoLite2 EULA - see 'Data_gathering.Accept_GeoLite2_EULA' in the config.
[16:47:34] [pool-2-thread-2/ERROR] [plan]: Failed to enable geolocation.
[16:47:34] [Server thread/INFO] [plan]: Player Analytics Enabled.
[16:47:34] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/gameevent/TickEvent$Type
        at net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent.<init>(TickEvent.java:49) ~[TickEvent$ServerTickEvent.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.common.gameevent.TickEvent$Type
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_241]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_241]
        ... 5 more
Caused by: java.lang.SecurityException: class "net.minecraftforge.fml.common.gameevent.TickEvent$Type"'s signer information does not match signer information of other classes in the same package
        at java.lang.ClassLoader.checkCerts(ClassLoader.java:891) ~[?:1.8.0_241]
        at java.lang.ClassLoader.preDefineClass(ClassLoader.java:661) ~[?:1.8.0_241]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:754) ~[?:1.8.0_241]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_241]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_241]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_241]
        ... 5 more
[16:47:35] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: D:\Minecraft Servers\SpongeForge-2860\.\crash-reports\crash-2022-02-01_16.47.35-server.txt
[16:47:35] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[16:47:35] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[16:47:35] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[16:47:35] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.world.WorldEvent$Unload@19e7666c:
java.lang.NoClassDefFoundError: net/minecraftforge/common/util/FakePlayerFactory
        at net.minecraftforge.common.ForgeInternalHandler.onDimensionUnload(ForgeInternalHandler.java:84) ~[ForgeInternalHandler.class:14.23.5.2860]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_4_ForgeInternalHandler_onDimensionUnload_Unload.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:756) [EventBus.class:?]
        at org.spongepowered.mod.event.SpongeToForgeEventFactory.createAndPostWorldUnloadEvent(SpongeToForgeEventFactory.java:957) [SpongeToForgeEventFactory.class:1.12.2-2838-7.4.7]
        at org.spongepowered.mod.event.SpongeToForgeEventFactory.createAndPostForgeEvent(SpongeToForgeEventFactory.java:282) [SpongeToForgeEventFactory.class:1.12.2-2838-7.4.7]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:339) [SpongeModEventManager.class:1.12.2-2838-7.4.7]
        at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:450) [SpongeModEventManager.class:1.12.2-2838-7.4.7]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:419) [SpongeModEventManager.class:1.12.2-2838-7.4.7]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:467) [SpongeEventManager.class:1.12.2-2838-7.4.7]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:249) [SpongeImpl.class:1.12.2-2838-7.4.7]
        at org.spongepowered.common.world.WorldManager.unloadWorld(WorldManager.java:544) [WorldManager.class:1.12.2-2838-7.4.7]
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:7421) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:579) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.common.util.FakePlayerFactory
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_241]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_241]
        ... 15 more
Caused by: java.lang.SecurityException: class "net.minecraftforge.common.util.FakePlayerFactory"'s signer information does not match signer information of other classes in the same package
        at java.lang.ClassLoader.checkCerts(ClassLoader.java:891) ~[?:1.8.0_241]
        at java.lang.ClassLoader.preDefineClass(ClassLoader.java:661) ~[?:1.8.0_241]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:754) ~[?:1.8.0_241]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_241]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_241]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_241]
        ... 15 more
[16:47:35] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[16:47:35] [Server thread/ERROR] [FML]: 0: HIGHEST
[16:47:35] [Server thread/ERROR] [FML]: 1: ASM: net.minecraftforge.common.ForgeInternalHandler@7c8179b0 onDimensionUnload(Lnet/minecraftforge/event/world/WorldEvent$Unload;)V
[16:47:35] [Server thread/ERROR] [minecraft/MinecraftServer]: Exception stopping the server
java.lang.NoClassDefFoundError: net/minecraftforge/common/util/FakePlayerFactory
        at net.minecraftforge.common.ForgeInternalHandler.onDimensionUnload(ForgeInternalHandler.java:84) ~[ForgeInternalHandler.class:14.23.5.2860]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_4_ForgeInternalHandler_onDimensionUnload_Unload.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:756) ~[EventBus.class:?]
        at org.spongepowered.mod.event.SpongeToForgeEventFactory.createAndPostWorldUnloadEvent(SpongeToForgeEventFactory.java:957) ~[SpongeToForgeEventFactory.class:1.12.2-2838-7.4.7]
        at org.spongepowered.mod.event.SpongeToForgeEventFactory.createAndPostForgeEvent(SpongeToForgeEventFactory.java:282) ~[SpongeToForgeEventFactory.class:1.12.2-2838-7.4.7]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:339) ~[SpongeModEventManager.class:1.12.2-2838-7.4.7]
        at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:450) ~[SpongeModEventManager.class:1.12.2-2838-7.4.7]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:419) ~[SpongeModEventManager.class:1.12.2-2838-7.4.7]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:467) ~[SpongeEventManager.class:1.12.2-2838-7.4.7]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:249) ~[SpongeImpl.class:1.12.2-2838-7.4.7]
        at org.spongepowered.common.world.WorldManager.unloadWorld(WorldManager.java:544) ~[WorldManager.class:1.12.2-2838-7.4.7]
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:7421) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:579) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.common.util.FakePlayerFactory
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_241]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_241]
        ... 15 more
Caused by: java.lang.SecurityException: class "net.minecraftforge.common.util.FakePlayerFactory"'s signer information does not match signer information of other classes in the same package
        at java.lang.ClassLoader.checkCerts(ClassLoader.java:891) ~[?:1.8.0_241]
        at java.lang.ClassLoader.preDefineClass(ClassLoader.java:661) ~[?:1.8.0_241]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:754) ~[?:1.8.0_241]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_241]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_241]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_241]
        ... 15 more
[16:47:35] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[16:47:35] [Server Shutdown Thread/INFO] [minecraft/MinecraftServer]: Stopping server
Exception in thread "Server Shutdown Thread"
```

**Comment by AuroraLS3** [comment]
The issue has been isolated to SQLite driver loading

**Comment by AuroraLS3** [comment]
This line causes the crash
```java
// Earlier
Class<?> connectionClass = driverClassLoader.loadClass("org.sqlite.jdbc4.JDBC4Connection");
connectionConstructor = connectionClass.getConstructor(String.class, String.class, Properties.class);
        
// This crashes shortly after, when classloaders fail to load next class
return (Connection) connectionConstructor.newInstance("jdbc:sqlite:" + dbFilePath, dbFilePath, properties);
```
Old version used
```java
return DriverManager.getConnection("jdbc:sqlite:" + dbFilePath + "?journal_mode=WAL");
```
Reverting the line stops the crashing

**Comment by Vankka** [comment]
From my testing, this seems to be caused by https://github.com/xerial/sqlite-jdbc/issues/656, should be able to downgrade to <3.35.0 of the sqlite driver to fix for the time being
