### ISSUE TITLE
BungeeCord Errors Duplicating: `io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)`

### ISSUE THREAD

**Issue by BredyAK** [plan-player-analytics/Plan#2215]
### Describe the issue

When player connects/disconnects with BungeeCord, lines of errors will show on BungeeCord, they are in this format:
```
00:46:21 [INFO] [BredyAK] <-> DownstreamBridge <-> [survival-1] has disconnected
20:47:42 [SEVERE] io.netty.channel.StacklessClosedChannelException
20:47:42 [SEVERE] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
20:47:42 [SEVERE] Caused by: io.netty.channel.unix.Errors$NativeIoException: writeAddress(..) failed: Broken pipe
20:47:42 [SEVERE] io.netty.channel.StacklessClosedChannelException
20:47:42 [SEVERE] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
20:47:42 [SEVERE] Caused by: io.netty.channel.unix.Errors$NativeIoException: writeAddress(..) failed: Broken pipe
20:47:42 [SEVERE] io.netty.channel.StacklessClosedChannelException
20:47:42 [SEVERE] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
20:47:42 [SEVERE] Caused by: io.netty.channel.unix.Errors$NativeIoException: writeAddress(..) failed: Broken pipe
20:47:42 [SEVERE] io.netty.channel.StacklessClosedChannelException
20:47:42 [SEVERE] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
20:47:42 [SEVERE] Caused by: io.netty.channel.unix.Errors$NativeIoException: writeAddress(..) failed: Broken pipe
20:47:42 [SEVERE] io.netty.channel.StacklessClosedChannelException
20:47:42 [SEVERE] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
20:47:42 [SEVERE] Caused by: io.netty.channel.unix.Errors$NativeIoException: writeAddress(..) failed: Broken pipe
20:47:42 [SEVERE] io.netty.channel.StacklessClosedChannelException
20:47:42 [SEVERE] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
20:47:42 [SEVERE] io.netty.channel.StacklessClosedChannelException
20:47:42 [SEVERE] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
20:47:42 [SEVERE] Caused by: io.netty.channel.unix.Errors$NativeIoException: writeAddress(..) failed: Broken pipe
20:47:42 [SEVERE] io.netty.channel.StacklessClosedChannelException
20:47:42 [SEVERE] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
20:47:42 [SEVERE] io.netty.channel.StacklessClosedChannelException
20:47:42 [SEVERE] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
20:47:42 [SEVERE] Caused by: io.netty.channel.unix.Errors$NativeIoException: writeAddress(..) failed: Broken pipe
20:47:42 [SEVERE] io.netty.channel.StacklessClosedChannelException
20:47:42 [SEVERE] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
20:47:42 [SEVERE] Caused by: io.netty.channel.unix.Errors$NativeIoException: writeAddress(..) failed: Broken pipe
20:47:42 [SEVERE] io.netty.channel.StacklessClosedChannelException
20:47:42 [SEVERE] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
20:47:42 [SEVERE] Caused by: io.netty.channel.unix.Errors$NativeIoException: writeAddress(..) failed: Broken pipe
20:47:42 [SEVERE] io.netty.channel.StacklessClosedChannelException
20:47:42 [SEVERE] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
20:47:42 [SEVERE] Caused by: io.netty.channel.unix.Errors$NativeIoException: writeAddress(..) failed: Broken pipe
20:47:42 [SEVERE] io.netty.channel.StacklessClosedChannelException
20:47:42 [SEVERE] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
20:47:42 [SEVERE] Caused by: io.netty.channel.unix.Errors$NativeIoException: writeAddress(..) failed: Broken pipe
20:47:42 [SEVERE] io.netty.channel.StacklessClosedChannelException
20:47:42 [SEVERE] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
20:47:42 [SEVERE] Caused by: io.netty.channel.unix.Errors$NativeIoException: writeAddress(..) failed: Broken pipe
20:47:42 [SEVERE] io.netty.channel.StacklessClosedChannelException
20:47:42 [SEVERE] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
20:47:42 [SEVERE] Caused by: io.netty.channel.unix.Errors$NativeIoException: writeAddress(..) failed: Broken pipe
20:47:42 [SEVERE] io.netty.channel.StacklessClosedChannelException
20:47:42 [SEVERE] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
20:47:42 [SEVERE] Caused by: io.netty.channel.unix.Errors$NativeIoException: writeAddress(..) failed: Broken pipe
20:47:42 [SEVERE] io.netty.channel.StacklessClosedChannelException
20:47:42 [SEVERE] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
20:47:42 [SEVERE] Caused by: io.netty.channel.unix.Errors$NativeIoException: writeAddress(..) failed: Broken pipe
20:47:42 [SEVERE] io.netty.channel.StacklessClosedChannelException
20:47:42 [SEVERE] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
20:47:42 [SEVERE] Caused by: io.netty.channel.unix.Errors$NativeIoException: writeAddress(..) failed: Broken pipe
20:47:42 [SEVERE] io.netty.channel.StacklessClosedChannelException
20:47:42 [SEVERE] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
20:47:42 [SEVERE] Caused by: io.netty.channel.unix.Errors$NativeIoException: writeAddress(..) failed: Broken pipe
20:47:42 [SEVERE] io.netty.channel.StacklessClosedChannelException
20:47:42 [SEVERE] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
20:47:42 [SEVERE] Caused by: io.netty.channel.unix.Errors$NativeIoException: writeAddress(..) failed: Broken pipe
20:47:42 [SEVERE] io.netty.channel.StacklessClosedChannelException
20:47:42 [SEVERE] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
20:47:42 [SEVERE] Caused by: io.netty.channel.unix.Errors$NativeIoException: writeAddress(..) failed: Broken pipe
20:47:42 [SEVERE] io.netty.channel.StacklessClosedChannelException
20:47:42 [SEVERE] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
20:47:42 [SEVERE] Caused by: io.netty.channel.unix.Errors$NativeIoException: writeAddress(..) failed: Broken pipe
20:47:42 [SEVERE] io.netty.channel.StacklessClosedChannelException
20:47:42 [SEVERE] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
20:47:42 [SEVERE] Caused by: io.netty.channel.unix.Errors$NativeIoException: writeAddress(..) failed: Broken pipe
20:47:42 [SEVERE] io.netty.channel.StacklessClosedChannelException
20:47:42 [SEVERE] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
20:47:42 [SEVERE] Caused by: io.netty.channel.unix.Errors$NativeIoException: writeAddress(..) failed: Broken pipe
```
All errors above start to duplicate when this error occured (the start point of all errors):
```
20:47:42 [SEVERE] [Da_hao_yin] -> UpstreamBridge - encountered exception
io.netty.handler.codec.EncoderException: java.lang.OutOfMemoryError: Java heap space
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:104)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
	at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:57)
	at net.md_5.bungee.UserConnection.sendPacket(UserConnection.java:173)
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:128)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:122)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.OutOfMemoryError: Java heap space
20:47:42 [WARNING] [Plan] Ran into IllegalStateException - logged to plugins/Plan/logs/IllegalStateException-c5595e57dc.txt
```

### Plugin versions

5.4 build 1516

### Additional information

I dropped Plan months ago because of this issue, and then errors are gone. Days ago, I download back Plan and use it again, and these annoying errors come back again. Fix this please!

**Comment by AuroraLS3** [comment]
How much memory do you have allocated to Bungeecord?

**Comment by BredyAK** [comment]
> 
512M

**Comment by BredyAK** [comment]
> How much memory do you have allocated to Bungeecord?

512M

**Comment by AuroraLS3** [comment]
Suggested allocating more memory. This issue will be resolved by https://github.com/plan-player-analytics/Plan/issues/1991 eventually, but giving more memory is a good idea if this happens.
