### ISSUE TITLE
Test fail in Github Actions due to Docker networking or something

### ISSUE THREAD

**Issue by AuroraLS3** [plan-player-analytics/Plan#2317]
### Describe the issue

Something is causing `ERR_NETWORK_CHANGED` in `ExportJSErrorRegressionTest` during tests in Github Actions.
This probably never happens in the real world, but it will be annoying if this becomes another flaky test.

----

From what I read is it may be caused by docker failing to create network - This test uses TestContainers to create an nginx container that serves the exported html files, so it that's why docker is related.

Something to try would be to clean docker stuff before and after pipeline runs.

### Exceptions & other logs

```text
ExportJSErrorRegressionTest > exportedWebpageDoesNotHaveErrors(ChromeDriver) > com.djrapitops.plan.delivery.export.ExportJSErrorRegressionTest.exportedWebpageDoesNotHaveErrors(ChromeDriver)[1] FAILED
    org.opentest4j.AssertionFailedError: Browser console included 1 logs: [
    SEVERE https://crafatar.com/avatars/45b0dfdb-f71d-4cf3-8c21-27c9d4c651db?size=120&default=MHF_Steve&overlay - Failed to load resource: net::ERR_NETWORK_CHANGED] ==> expected: <true> but was: <false>
        at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:46)
        at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:187)
        at com.djrapitops.plan.delivery.export.ExportJSErrorRegressionTest.assertNoLogs(ExportJSErrorRegressionTest.java:191)
        at com.djrapitops.plan.delivery.export.ExportJSErrorRegressionTest.lambda$exportedWebpageDoesNotHaveErrors$0(ExportJSErrorRegressionTest.java:181)
```

### Plugin versions

-

### Additional information

-

**Comment by AuroraLS3** [comment]
Doesn't seem to happen anymore
