### ISSUE TITLE
LuckPerms extension complains about invalid SQL syntax

### ISSUE THREAD

**Issue by Kopo942** [plan-player-analytics/Plan#2318]
### Describe the issue

Exact cause not found, but happens sometimes when executing LP commands?

### Exceptions & other logs

```text
[16:35:03] [Server thread/INFO]: NATroutter issued server command: /lp deletegroup *
[16:35:03] [ForkJoinPool-1-worker-11/INFO]: [LuckPerms] [Messaging] Sending log with id: d3ce8f0b-70bb-4fc6-b890-9a65878b93dc
[16:35:03] [luckperms-command-executor/INFO]: [LP] LOG > (NATroutter@survival) [G] (*)
[16:35:03] [luckperms-command-executor/INFO]: [LP] LOG > delete
[16:35:03] [ForkJoinPool-1-worker-12/WARN]: [LuckPerms] Unable to pass event GroupDeleteEvent to handler com.djrapitops.extension.LuckPermsExtension$$Lambda$7927/0x0000000802603968
com.djrapitops.plan.exceptions.database.DBOpException: SQL Failure: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'plan_extension_plugins pl on pl.id=pr.plugin_idWHERE g.group='*' AND pl.name=...' at line 1
	at com.djrapitops.plan.exceptions.database.DBOpException.forCause(DBOpException.java:135) ~[Plan-5.4-build-1583.jar:?]
	at com.djrapitops.plan.storage.database.queries.QueryAPIQuery.executeWithConnection(QueryAPIQuery.java:58) ~[Plan-5.4-build-1583.jar:?]
	at com.djrapitops.plan.storage.database.queries.QueryAPIQuery.executeQuery(QueryAPIQuery.java:46) ~[Plan-5.4-build-1583.jar:?]
	at com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:303) ~[Plan-5.4-build-1583.jar:?]
	at com.djrapitops.plan.query.QuerySvc.query(QuerySvc.java:81) ~[Plan-5.4-build-1583.jar:?]
	at com.djrapitops.extension.LuckPermsExtension.updatePlayersInGroup(LuckPermsExtension.java:79) ~[Plan-5.4-build-1583.jar:?]
	at com.djrapitops.extension.LuckPermsExtension.lambda$registerListeners$1(LuckPermsExtension.java:65) ~[Plan-5.4-build-1583.jar:?]
	at me.lucko.luckperms.common.event.LuckPermsEventSubscription.invoke(LuckPermsEventSubscription.java:95) ~[?:?]
	at me.lucko.luckperms.common.event.LuckPermsEventSubscription.invoke(LuckPermsEventSubscription.java:43) ~[?:?]
	at me.lucko.luckperms.lib.eventbus.SimpleEventBus.post(SimpleEventBus.java:107) ~[?:?]
	at me.lucko.luckperms.common.event.AbstractEventBus.post(AbstractEventBus.java:84) ~[?:?]
	at me.lucko.luckperms.common.event.EventDispatcher.post(EventDispatcher.java:128) ~[?:?]
	at me.lucko.luckperms.common.event.EventDispatcher.lambda$postAsync$0(EventDispatcher.java:143) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'plan_extension_plugins pl on pl.id=pr.plugin_idWHERE g.group='*' AND pl.name=...' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at plan.com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[Plan-5.4-build-1583.jar:?]
	at plan.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[Plan-5.4-build-1583.jar:?]
	at com.djrapitops.extension.LuckPermsExtension.lambda$updatePlayersInGroup$2(LuckPermsExtension.java:86) ~[Plan-5.4-build-1583.jar:?]
	at com.djrapitops.plan.storage.database.queries.QueryAPIQuery.executeWithConnection(QueryAPIQuery.java:56) ~[Plan-5.4-build-1583.jar:?]
	... 17 more
```

### Plugin versions

Plan 5.4 b1583, LP 5.4.9

**Comment by AuroraLS3** [comment]
Missing space before `WHERE` 🤦
