### ISSUE TITLE
Update from 1583 to 1628 fails

### ISSUE THREAD

**Issue by Pingger** [plan-player-analytics/Plan#2333]
### Describe the issue

I'm trying to update from 5.4-1583 to 5.4-1628, but startup fails during the database patching

### Exceptions & other logs

<details>
    <summary>CompletionException-7c2cd62c94.txt</summary>

```

7c2cd62c94 - Last occurred: 2022-04-16 Occurrences: 3
---- Context 3 ----
Plan v5.4 build 1628
BungeeCord git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483
Server vgit:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483

Transaction: class com.djrapitops.plan.storage.database.SQLDB$1
DB State: CLOSED

---- Context 2 ----
Plan v5.4 build 1628
BungeeCord git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483
Server vgit:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483

Transaction: class com.djrapitops.plan.storage.database.SQLDB$1
DB State: CLOSED

---- Context 1 ----
Plan v5.4 build 1628
BungeeCord git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483
Server vgit:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483

Transaction: class com.djrapitops.plan.storage.database.SQLDB$1
DB State: CLOSED

---- Stacktrace ----
java.util.concurrent.CompletionException: com.djrapitops.plan.exceptions.database.FatalDBException: com.djrapitops.plan.storage.database.SQLDB$1 failed to execute and database could not be opened:  initialization failed: HikariDataSource HikariDataSource (Plan Connection Pool-1) has been closed.
   java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
   java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
   java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
   java.base/java.lang.Thread.run(Thread.java:833)
Caused by:
com.djrapitops.plan.exceptions.database.FatalDBException: com.djrapitops.plan.storage.database.SQLDB$1 failed to execute and database could not be opened:  initialization failed: HikariDataSource HikariDataSource (Plan Connection Pool-1) has been closed.
   com.djrapitops.plan.storage.database.transactions.init.OperationCriticalTransaction.executeTransaction(OperationCriticalTransaction.java:41)
   com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$2(SQLDB.java:320)
   java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
   java.base/java.lang.Thread.run(Thread.java:833)
Caused by:
java.sql.SQLException: HikariDataSource HikariDataSource (Plan Connection Pool-1) has been closed.
   plan.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96)
   com.djrapitops.plan.storage.database.MySQLDB.getConnection(MySQLDB.java:170)
   com.djrapitops.plan.storage.database.transactions.Transaction.initializeConnection(Transaction.java:168)
   com.djrapitops.plan.storage.database.transactions.Transaction.executeTransaction(Transaction.java:81)
   com.djrapitops.plan.storage.database.transactions.init.OperationCriticalTransaction.executeTransaction(OperationCriticalTransaction.java:36)
   com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$2(SQLDB.java:320)
   java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
   java.base/java.lang.Thread.run(Thread.java:833)
   com.djrapitops.plan.storage.database.SQLDB.executeTransaction(SQLDB.java:316)
   com.djrapitops.plan.storage.database.SQLDB.setupDatabase(SQLDB.java:240)
   com.djrapitops.plan.storage.database.SQLDB.init(SQLDB.java:146)
   com.djrapitops.plan.storage.database.DBSystem.enable(DBSystem.java:92)
   com.djrapitops.plan.PlanSystem.enableSystems(PlanSystem.java:201)
   com.djrapitops.plan.PlanSystem.enable(PlanSystem.java:172)
   com.djrapitops.plan.PlanBungee.onEnable(PlanBungee.java:66)
   net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:315)
   net.md_5.bungee.BungeeCord.start(BungeeCord.java:290)
   net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
   net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)


```

</details>

<details>
    <summary>EnableException-e06831a9fe.txt</summary>

```

e06831a9fe - Last occurred: 2022-04-16 Occurrences: 1
---- Context 1 ----
Plan v5.4 build 1628
BungeeCord git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483
Server vgit:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483


---- Stacktrace ----
com.djrapitops.plan.exceptions.EnableException: Database failed to open, Query has failed. (This exception is necessary to not keep query threads waiting)
   com.djrapitops.plan.storage.database.DBAccessLock.checkAccess(DBAccessLock.java:61)
   com.djrapitops.plan.storage.database.DBAccessLock.checkAccess(DBAccessLock.java:43)
   com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:306)
   com.djrapitops.plan.delivery.webserver.auth.ActiveCookieStore.loadActiveCookies(ActiveCookieStore.java:84)
   com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:78)
   java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
   java.base/java.lang.Thread.run(Thread.java:833)


```

</details>

<details>
    <summary>latest.log</summary>

```

[10:05:45] [main/INFO]: Using mbed TLS based native cipher.
[10:05:45] [main/INFO]: Using zlib based native compressor.
[10:05:45] [main/INFO]: Enabled Waterfall version git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483
[10:05:45] [main/INFO]: Not on Windows, attempting to use enhanced EpollEventLoop
[10:05:45] [main/INFO]: Epoll is working, utilising it!
[10:05:45] [main/INFO]: Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
[10:05:45] [main/INFO]: Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
[10:05:45] [main/INFO]: Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
[10:05:45] [main/INFO]: Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
[10:05:45] [main/INFO]: Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
[10:05:45] [main/INFO]: Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
[10:05:45] [main/INFO]: Loaded plugin Reconnect version 1.5.3 by TauCubed (Development, commands & overhaul), 5zig (Initial Development), Krymonota (Contribution), Terrobility (Addition Config), dallasxfulcanelly (dynamic localization)
[10:05:45] [main/INFO]: Loaded plugin reconnect_yaml version git:reconnect_yaml:1.18-R0.1-SNAPSHOT:ba3bbcc:483 by WaterfallMC
[10:05:45] [main/INFO]: Loaded plugin cmd_find version git:cmd_find:1.18-R0.1-SNAPSHOT:ba3bbcc:483 by WaterfallMC
[10:05:45] [main/INFO]: Loaded plugin ViaVersion version 4.2.1 by _MylesC, creeper123123321, Gerrygames, kennytv, Matsv
[10:05:45] [main/INFO]: Loaded plugin cmd_server version git:cmd_server:1.18-R0.1-SNAPSHOT:ba3bbcc:483 by WaterfallMC
[10:05:45] [main/INFO]: Loaded plugin cmd_alert version git:cmd_alert:1.18-R0.1-SNAPSHOT:ba3bbcc:483 by WaterfallMC
[10:05:45] [main/INFO]: Loaded plugin Maintenance version 4.0.0 by kennytv
[10:05:45] [main/INFO]: Loaded plugin Plan version 5.4 build 1628 by AuroraLS3
[10:05:45] [main/INFO]: Loaded plugin cmd_send version git:cmd_send:1.18-R0.1-SNAPSHOT:ba3bbcc:483 by WaterfallMC
[10:05:45] [main/INFO]: Loaded plugin ViaBackwards version 4.2.1 by Matsv, kennytv, Gerrygames, creeper123123321, ForceUpdate1
[10:05:45] [main/INFO]: Loaded plugin cmd_list version git:cmd_list:1.18-R0.1-SNAPSHOT:ba3bbcc:483 by WaterfallMC
[10:05:45] [main/INFO]: Enabled plugin Reconnect version 1.5.3 by TauCubed (Development, commands & overhaul), 5zig (Initial Development), Krymonota (Contribution), Terrobility (Addition Config), dallasxfulcanelly (dynamic localization)
[10:05:45] [main/INFO]: Enabled plugin reconnect_yaml version git:reconnect_yaml:1.18-R0.1-SNAPSHOT:ba3bbcc:483 by WaterfallMC
[10:05:45] [main/INFO]: Enabled plugin cmd_find version git:cmd_find:1.18-R0.1-SNAPSHOT:ba3bbcc:483 by WaterfallMC
[10:05:46] [Via-Mappingloader-0/INFO] [ViaVersion]: Loading 1.12 -> 1.13 mappings...
[10:05:46] [Via-Mappingloader-1/INFO] [ViaVersion]: Loading 1.13 -> 1.13.2 mappings...
[10:05:46] [Via-Mappingloader-2/INFO] [ViaVersion]: Loading 1.13.2 -> 1.14 mappings...
[10:05:46] [Via-Mappingloader-3/INFO] [ViaVersion]: Loading 1.14 -> 1.15 mappings...
[10:05:46] [Via-Mappingloader-4/INFO] [ViaVersion]: Loading 1.15 -> 1.16 mappings...
[10:05:46] [Via-Mappingloader-1/INFO] [ViaVersion]: Loading 1.16 -> 1.16.2 mappings...
[10:05:46] [Via-Mappingloader-0/INFO] [ViaVersion]: Loading block connection mappings ...
[10:05:46] [Via-Mappingloader-5/INFO] [ViaVersion]: Loading 1.16.2 -> 1.17 mappings...
[10:05:46] [Via-Mappingloader-3/INFO] [ViaVersion]: Loading 1.17 -> 1.18 mappings...
[10:05:46] [main/INFO] [ViaBackwards]: Loading translations...
[10:05:47] [Via-Mappingloader-3/INFO] [ViaBackwards]: Loading 1.10 -> 1.9.4 mappings...
[10:05:47] [Via-Mappingloader-3/INFO] [ViaBackwards]: Loading 1.11 -> 1.10 mappings...
[10:05:47] [Via-Mappingloader-3/INFO] [ViaBackwards]: Loading 1.12 -> 1.11 mappings...
[10:05:47] [Via-Mappingloader-3/INFO] [ViaBackwards]: Loading 1.13 -> 1.12 mappings...
[10:05:47] [Via-Mappingloader-0/INFO] [ViaBackwards]: Loading 1.13.2 -> 1.13 mappings...
[10:05:47] [Via-Mappingloader-0/INFO] [ViaBackwards]: Loading 1.14 -> 1.13.2 mappings...
[10:05:47] [Via-Mappingloader-3/INFO] [ViaBackwards]: Loading 1.15 -> 1.14 mappings...
[10:05:47] [Via-Mappingloader-3/INFO] [ViaBackwards]: Loading 1.16 -> 1.15 mappings...
[10:05:47] [Via-Mappingloader-0/INFO] [ViaBackwards]: Loading 1.16.2 -> 1.16 mappings...
[10:05:47] [Via-Mappingloader-0/INFO] [ViaBackwards]: Loading 1.17 -> 1.16.2 mappings...
[10:05:47] [Via-Mappingloader-0/INFO] [ViaBackwards]: Loading 1.18 -> 1.17 mappings...
[10:05:47] [main/INFO]: Enabled plugin ViaVersion version 4.2.1 by _MylesC, creeper123123321, Gerrygames, kennytv, Matsv
[10:05:47] [ViaVersion Pool Thread #0/INFO] [ViaVersion]: ViaVersion detected lowest supported version by the proxy: 1.8.x (47)
[10:05:47] [main/INFO]: Enabled plugin cmd_server version git:cmd_server:1.18-R0.1-SNAPSHOT:ba3bbcc:483 by WaterfallMC
[10:05:47] [ViaVersion Pool Thread #0/INFO] [ViaVersion]: Highest supported version by the proxy: 1.18.2 (758)
[10:05:47] [main/INFO]: Enabled plugin cmd_alert version git:cmd_alert:1.18-R0.1-SNAPSHOT:ba3bbcc:483 by WaterfallMC
[10:05:47] [ViaVersion Pool Thread #2/INFO] [ViaVersion]: Finished mapping loading, shutting down loader executor!
[10:05:47] [main/INFO]: Enabled plugin Maintenance version 4.0.0 by kennytv
[10:05:48] [main/INFO] [Plan]: 
[10:05:48] [main/INFO] [Plan]:            ██▌
[10:05:48] [main/INFO] [Plan]:      ██▌   ██▌
[10:05:48] [main/INFO] [Plan]:   ██▌██▌██▌██▌  Player Analytics
[10:05:48] [main/INFO] [Plan]:   ██▌██▌██▌██▌  v5.4 build 1628
[10:05:48] [main/INFO] [Plan]: 
[10:05:48] [main/INFO] [Plan]: Locale: 'English' by AuroraLS3
[10:05:48] [main/INFO] [Plan]: Downloading MySQL Driver, this may take a while...
[10:05:48] [Plan Pool Thread #1/INFO] [Plan]: You're using the latest version.
[10:05:48] [main/INFO] [Plan]: Database: Making sure schema is up to date..
[10:05:48] [main/INFO] [Plan]: MySQL-database connection established.
[10:05:48] [main/INFO] [Plan]: WebServer: Proxy-mode HTTPS enabled, make sure that your reverse-proxy is routing using HTTPS and Plan Alternative_IP.Address points to the Proxy
[10:05:48] [main/INFO] [Plan]: Webserver running on PORT 8804 ( https://plan.uedo.eu:443 )
[10:05:48] [main/INFO] [Plan]: Loading server identifying information
[10:05:48] [Plan MySQLDB-transaction-thread-1/INFO] [Plan]: Applying Patch: PingOptimizationPatch..
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: Database failed to open, com.djrapitops.plan.storage.database.transactions.patches.PingOptimizationPatch failed to be executed.
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: Error msg: com.djrapitops.plan.storage.database.transactions.patches.PingOptimizationPatch failed to execute and database could not be opened: PingOptimizationPatch failed.
[10:05:50] [main/ERROR] [Plan]: ----------------------------------------
[10:05:50] [main/ERROR] [Plan]: Error: Database failed to open, Query has failed. (This exception is necessary to not keep query threads waiting)
[10:05:50] [main/ERROR] [Plan]: ----------------------------------------
[10:05:50] [main/ERROR] [Plan]: Plugin Failed to Initialize Correctly. If this issue is caused by config settings you can use /planbungee reload
[10:05:50] [main/INFO] [Plan]: Processing complete.
[10:05:50] [main/INFO] [Plan]: Waiting for unfinished transactions to avoid data loss..
[10:05:50] [Plan Pool Thread #2/ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@670ce331, id=9, owner=com.djrapitops.plan.PlanBungee@3d512652, task=com.djrapitops.plan.delivery.export.ExportScheduler@4b343b6d, delay=0, period=0, running=false) encountered an exception
com.djrapitops.plan.exceptions.EnableException: Database failed to open, Query has failed. (This exception is necessary to not keep query threads waiting)
	at com.djrapitops.plan.storage.database.DBAccessLock.checkAccess(DBAccessLock.java:61) ~[?:?]
	at com.djrapitops.plan.storage.database.DBAccessLock.checkAccess(DBAccessLock.java:43) ~[?:?]
	at com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:306) ~[?:?]
	at com.djrapitops.plan.delivery.export.ExportScheduler.scheduleExport(ExportScheduler.java:77) ~[?:?]
	at com.djrapitops.plan.delivery.export.ExportScheduler.run(ExportScheduler.java:72) ~[?:?]
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[waterfall-1.18-483.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[10:05:50] [Plan Non critical-pool-1/ERROR] [Plan]: Failed to read plugins/Plan/logs/EnableException-e06831a9fe.txt deleting file
[10:05:50] [Plan Non critical-pool-1/WARN] [Plan]: Ran into EnableException - logged to plugins/Plan/logs/EnableException-e06831a9fe.txt
[10:05:50] [Plan Non critical-pool-1/WARN] [Plan]: (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[10:05:50] [Plan Non critical-pool-1/WARN] [Plan]: Error msg: "Database failed to open, Query has failed. (This exception is necessary to not keep query threads waiting)"
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: Ran into CompletionException - logged to plugins/Plan/logs/CompletionException-67698732f5.txt
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: What to do: Report this error. NOT NULL constraint violation occurred.
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: CRITICAL error triggered a plugin shutdown.
[10:05:50] [Plan MySQLDB-transaction-thread-1/INFO] [Plan]: Processing complete.
[10:05:50] [Plan MySQLDB-transaction-thread-1/INFO] [Plan]: Webserver has been disabled.
[10:05:50] [Plan MySQLDB-transaction-thread-1/INFO] [Plan]: Player Analytics Disabled.
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: Database failed to open, com.djrapitops.plan.storage.database.transactions.patches.UserInfoOptimizationPatch failed to be executed.
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: Error msg: com.djrapitops.plan.storage.database.transactions.patches.UserInfoOptimizationPatch failed to execute and database could not be opened: UserInfoOptimizationPatch initialization failed: HikariDataSource HikariDataSource (Plan Connection Pool-1) has been closed.
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: Ran into CompletionException - logged to plugins/Plan/logs/CompletionException-7951a90349.txt
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: Error msg: "com.djrapitops.plan.exceptions.database.FatalDBException: com.djrapitops.plan.storage.database.transactions.patches.UserInfoOptimizationPatch failed to execute and database could not be opened: UserInfoOptimizationPatch initialization failed: HikariDataSource HikariDataSource (Plan Connection Pool-1) has been closed."
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: CRITICAL error triggered a plugin shutdown.
[10:05:50] [Plan MySQLDB-transaction-thread-1/INFO] [Plan]: Processing complete.
[10:05:50] [Plan MySQLDB-transaction-thread-1/INFO] [Plan]: Webserver has been disabled.
[10:05:50] [Plan MySQLDB-transaction-thread-1/INFO] [Plan]: Player Analytics Disabled.
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: Database failed to open, com.djrapitops.plan.storage.database.transactions.patches.WorldTimesOptimizationPatch failed to be executed.
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: Error msg: com.djrapitops.plan.storage.database.transactions.patches.WorldTimesOptimizationPatch failed to execute and database could not be opened: WorldTimesOptimizationPatch initialization failed: HikariDataSource HikariDataSource (Plan Connection Pool-1) has been closed.
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: Ran into CompletionException - logged to plugins/Plan/logs/CompletionException-7951a90349.txt
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: Error msg: "com.djrapitops.plan.exceptions.database.FatalDBException: com.djrapitops.plan.storage.database.transactions.patches.WorldTimesOptimizationPatch failed to execute and database could not be opened: WorldTimesOptimizationPatch initialization failed: HikariDataSource HikariDataSource (Plan Connection Pool-1) has been closed."
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: CRITICAL error triggered a plugin shutdown.
[10:05:50] [Plan MySQLDB-transaction-thread-1/INFO] [Plan]: Processing complete.
[10:05:50] [Plan MySQLDB-transaction-thread-1/INFO] [Plan]: Webserver has been disabled.
[10:05:50] [Plan MySQLDB-transaction-thread-1/INFO] [Plan]: Player Analytics Disabled.
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: Database failed to open, com.djrapitops.plan.storage.database.transactions.patches.SessionsOptimizationPatch failed to be executed.
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: Error msg: com.djrapitops.plan.storage.database.transactions.patches.SessionsOptimizationPatch failed to execute and database could not be opened: SessionsOptimizationPatch initialization failed: HikariDataSource HikariDataSource (Plan Connection Pool-1) has been closed.
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: Ran into CompletionException - logged to plugins/Plan/logs/CompletionException-7951a90349.txt
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: Error msg: "com.djrapitops.plan.exceptions.database.FatalDBException: com.djrapitops.plan.storage.database.transactions.patches.SessionsOptimizationPatch failed to execute and database could not be opened: SessionsOptimizationPatch initialization failed: HikariDataSource HikariDataSource (Plan Connection Pool-1) has been closed."
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: CRITICAL error triggered a plugin shutdown.
[10:05:50] [Plan MySQLDB-transaction-thread-1/INFO] [Plan]: Processing complete.
[10:05:50] [Plan MySQLDB-transaction-thread-1/INFO] [Plan]: Webserver has been disabled.
[10:05:50] [Plan MySQLDB-transaction-thread-1/INFO] [Plan]: Player Analytics Disabled.
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: Database failed to open, com.djrapitops.plan.storage.database.transactions.patches.UserInfoHostnameAllowNullPatch failed to be executed.
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: Error msg: com.djrapitops.plan.storage.database.transactions.patches.UserInfoHostnameAllowNullPatch failed to execute and database could not be opened: UserInfoHostnameAllowNullPatch initialization failed: HikariDataSource HikariDataSource (Plan Connection Pool-1) has been closed.
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: Ran into CompletionException - logged to plugins/Plan/logs/CompletionException-7951a90349.txt
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: Error msg: "com.djrapitops.plan.exceptions.database.FatalDBException: com.djrapitops.plan.storage.database.transactions.patches.UserInfoHostnameAllowNullPatch failed to execute and database could not be opened: UserInfoHostnameAllowNullPatch initialization failed: HikariDataSource HikariDataSource (Plan Connection Pool-1) has been closed."
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: CRITICAL error triggered a plugin shutdown.
[10:05:50] [Plan MySQLDB-transaction-thread-1/INFO] [Plan]: Processing complete.
[10:05:50] [Plan MySQLDB-transaction-thread-1/INFO] [Plan]: Webserver has been disabled.
[10:05:50] [Plan MySQLDB-transaction-thread-1/INFO] [Plan]: Player Analytics Disabled.
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: Database failed to open, com.djrapitops.plan.storage.database.transactions.patches.RegisterDateMinimizationPatch failed to be executed.
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: Error msg: com.djrapitops.plan.storage.database.transactions.patches.RegisterDateMinimizationPatch failed to execute and database could not be opened: RegisterDateMinimizationPatch initialization failed: HikariDataSource HikariDataSource (Plan Connection Pool-1) has been closed.
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: Ran into CompletionException - logged to plugins/Plan/logs/CompletionException-7951a90349.txt
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: Error msg: "com.djrapitops.plan.exceptions.database.FatalDBException: com.djrapitops.plan.storage.database.transactions.patches.RegisterDateMinimizationPatch failed to execute and database could not be opened: RegisterDateMinimizationPatch initialization failed: HikariDataSource HikariDataSource (Plan Connection Pool-1) has been closed."
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: CRITICAL error triggered a plugin shutdown.
[10:05:50] [Plan MySQLDB-transaction-thread-1/INFO] [Plan]: Processing complete.
[10:05:50] [Plan MySQLDB-transaction-thread-1/INFO] [Plan]: Webserver has been disabled.
[10:05:50] [Plan MySQLDB-transaction-thread-1/INFO] [Plan]: Player Analytics Disabled.
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: Database failed to open, com.djrapitops.plan.storage.database.SQLDB$1 failed to be executed.
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: Error msg: com.djrapitops.plan.storage.database.SQLDB$1 failed to execute and database could not be opened:  initialization failed: HikariDataSource HikariDataSource (Plan Connection Pool-1) has been closed.
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: Ran into CompletionException - logged to plugins/Plan/logs/CompletionException-7c2cd62c94.txt
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: Error msg: "com.djrapitops.plan.exceptions.database.FatalDBException: com.djrapitops.plan.storage.database.SQLDB$1 failed to execute and database could not be opened:  initialization failed: HikariDataSource HikariDataSource (Plan Connection Pool-1) has been closed."
[10:05:50] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: CRITICAL error triggered a plugin shutdown.
[10:05:50] [Plan MySQLDB-transaction-thread-1/INFO] [Plan]: Processing complete.
[10:05:50] [Plan MySQLDB-transaction-thread-1/INFO] [Plan]: Webserver has been disabled.
[10:05:50] [Plan MySQLDB-transaction-thread-1/INFO] [Plan]: Player Analytics Disabled.


```

</details>

### Plugin versions

Waterfall: git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483
Plan: 5.4-1628
ViaVersion: v443043
ViaBackwards: v445618
BungeeReconnect: 1.5.3
Maintenance: 4.0.0

### Additional information

I have a database dump from before the attempted update.

Applying the backup and using the old version works for the moment. Updating still fails.

_PS: The Template for your logfiles is very bad, because it prevents properly attaching multiple logfiles_

**Comment by AuroraLS3** [comment]
Somebody had same issue on discord yesterday so luckily there's a cure. The main issue is that some rows are missing (Someone may have manually deleted them)

----

- Run this in your MySQL and copy all uuids that come up:
```sql
SELECT u.uuid, g.uuid FROM temp_ping g 
LEFT JOIN plan_users u on u.uuid=g.uuid
WHERE u.uuid IS NULL;
```
- Then run
```sql
INSERT into plan_users (uuid, registered, name, times_kicked) 
VALUES 
('uuid here', 1650023218067, 'delete_me_later', 0);
```
- Reload Plan
- After patches complete run `/plan db remove delete_me_later` to delete the user properly.

----

If the first query didn't give any uuids, it's a server row that is missing, do these:
- Run this in your MySQL and copy all uuids that come up:
```sql
SELECT u.uuid, g.uuid FROM temp_ping g 
LEFT JOIN plan_servers u on u.uuid=g.server_uuid
WHERE u.uuid IS NULL;
```
- Then run
```sql
INSERT into plan_servers (uuid, name) 
VALUES 
('uuid here', 'delete_me_later');
```
- Reload Plan
- After patches complete run `/plan db uninstalled delete_me_later` to mark the server as uninstalled.

**Comment by AuroraLS3** [comment]
I agree with the template for log files since it doesn't support files yet. https://github.com/github/feedback/discussions/4291 - I'll put the bug report back to the old format..

**Comment by Pingger** [comment]
Both a User and 2 Servers were missing. Now I ran into the next exception...

[CompletionException-537d35cc29.txt](https://github.com/plan-player-analytics/Plan/files/8499732/CompletionException-537d35cc29.txt)
[CompletionException-5f7d6f2028.txt](https://github.com/plan-player-analytics/Plan/files/8499733/CompletionException-5f7d6f2028.txt)
[CompletionException-c169a306ac.txt](https://github.com/plan-player-analytics/Plan/files/8499734/CompletionException-c169a306ac.txt)
[CompletionException-ec7aa802ec.txt](https://github.com/plan-player-analytics/Plan/files/8499735/CompletionException-ec7aa802ec.txt)
[EnableException-e06831a9fe.txt](https://github.com/plan-player-analytics/Plan/files/8499736/EnableException-e06831a9fe.txt)
[latest.log](https://github.com/plan-player-analytics/Plan/files/8499742/latest.log)

**Comment by Pingger** [comment]
OK ... I worked around the issue, be manually removing all occurences of the UUID of the player and the 2 servers and now the update succeeded

**Comment by AuroraLS3** [comment]
That works too

**Comment by Pingger** [comment]
no idea, where those partial entries came from but I guess, that at somepoint the server crashed mid user join or mid query and did weird stuff.
Thx for the help.

**Comment by AuroraLS3** [comment]
Nice that you got it working.

My main hypothesis is that manual delete was run in order to hide a server or user from the panel, but it could be some other weird transaction order thing since the auto commit was (incorrectly) enabled before this update.
