### ISSUE TITLE
Error when signing in without authorization in xbox

### ISSUE THREAD

**Issue by Toper9636** [plan-player-analytics/Plan#2436]
### Describe the issue
When I try to log in without authorization in the xbox, this error occurs:
2022-06-18 17:22:31.609 [main] FATAL - Could not pass event 'cn.nukkit.event.player.PlayerQuitEvent' to 'Plan v5.4 build 1722': null on com.djrapitops.plan.gathering.timed.NukkitPingCounter
2022-06-18 17:22:31.609 [main] ERROR - Throwing
cn.nukkit.utils.EventException: null
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:7) ~[server.jar:?]
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:7) ~[server.jar:?]
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:248) ~[server.jar:?]
	at cn.nukkit.Player.close(Player.java:2310) ~[server.jar:?]
	at cn.nukkit.Player.close(Player.java:3171) ~[server.jar:?]
	at cn.nukkit.Player.close(Player.java:3429) ~[server.jar:?]
	at cn.nukkit.Player.handleDataPacket(Player.java:2447) ~[server.jar:?]
	at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(NukkitCheatPlayer.kt:74) ~[?:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_202]
	at cn.nukkit.network.Network.processPackets(Network.java:155) ~[server.jar:?]
	at cn.nukkit.network.Network.processBatch(Network.java:211) ~[server.jar:?]
	at cn.nukkit.Player.handleDataPacket(Player.java:322) ~[server.jar:?]
	at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(NukkitCheatPlayer.kt:74) ~[?:?]
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:84) ~[server.jar:?]
	at cn.nukkit.network.Network.processInterfaces(Network.java:231) ~[server.jar:?]
	at cn.nukkit.Server.d(Server.java:1) ~[server.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:16) ~[server.jar:?]
	at cn.nukkit.Server.start(Server.java:100) ~[server.jar:?]
	at cn.nukkit.Server.<init>(Server.java:229) ~[server.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:10) ~[server.jar:?]
Caused by: java.lang.NullPointerException
2022-06-18 17:22:31.609 [main] FATAL - Could not pass event 'cn.nukkit.event.player.PlayerQuitEvent' to 'Plan v5.4 build 1722': null on com.djrapitops.plan.gathering.listeners.nukkit.NukkitAFKListener
2022-06-18 17:22:31.609 [main] ERROR - Throwing
cn.nukkit.utils.EventException: null
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:7) ~[server.jar:?]
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:7) ~[server.jar:?]
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:248) ~[server.jar:?]
	at cn.nukkit.Player.close(Player.java:2310) ~[server.jar:?]
	at cn.nukkit.Player.close(Player.java:3171) ~[server.jar:?]
	at cn.nukkit.Player.close(Player.java:3429) ~[server.jar:?]
	at cn.nukkit.Player.handleDataPacket(Player.java:2447) ~[server.jar:?]
	at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(NukkitCheatPlayer.kt:74) ~[?:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_202]
	at cn.nukkit.network.Network.processPackets(Network.java:155) ~[server.jar:?]
	at cn.nukkit.network.Network.processBatch(Network.java:211) ~[server.jar:?]
	at cn.nukkit.Player.handleDataPacket(Player.java:322) ~[server.jar:?]
	at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(NukkitCheatPlayer.kt:74) ~[?:?]
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:84) ~[server.jar:?]
	at cn.nukkit.network.Network.processInterfaces(Network.java:231) ~[server.jar:?]
	at cn.nukkit.Server.d(Server.java:1) ~[server.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:16) ~[server.jar:?]
	at cn.nukkit.Server.start(Server.java:100) ~[server.jar:?]
	at cn.nukkit.Server.<init>(Server.java:229) ~[server.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:10) ~[server.jar:?]
Caused by: java.lang.NullPointerException
2022-06-18 17:22:31.609 [main] INFO  - §bSqPersona§f[/**.**.***.***:21898] logged out due to Not authenticated!

### Exceptions & Other Logs
none

```
none
```

### Plugin versions
Plan v5.4 build 1722

### Additional information
none

**Comment by AuroraLS3** [comment]
The error seems to occur in Nukkit code instead of Plan code even though Plan listeners are mentioned.

The listeners in question have logic that can only error if the event is called with a `null` player (At which point it doesn't make sense for nukkit to do that)

Please try updating your nukkit version and if that doesn't help report this to nukkit
