### ISSUE TITLE
com.djrapitops.plan.exceptions.EnableException: Database failed to open, Query has failed.

### ISSUE THREAD

**Issue by Futodama** [plan-player-analytics/Plan#2454]
### Describe the issue
The database is available and works normally. However, Plan says this is not the case.

### Exceptions & Other Logs
[13:25:20 WARN]: [Plan] Ran into EnableException - logged to plugins/Plan/logs/EnableException-ef79dac831.txt
[13:25:20 WARN]: [Plan] (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[13:25:20 ERROR]: [global] Failed to log Plan error, see suppressed.
com.djrapitops.plan.exceptions.EnableException: Database failed to open, Query has failed. (This exception is necessary to not keep query threads waiting)
        at com.djrapitops.plan.storage.database.DBAccessLock.checkAccess(DBAccessLock.java:61) ~[Plan-5.4-build-1722.jar:?]
        at com.djrapitops.plan.storage.database.DBAccessLock.checkAccess(DBAccessLock.java:43) ~[Plan-5.4-build-1722.jar:?]
        at com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:315) ~[Plan-5.4-build-1722.jar:?]
        at com.djrapitops.plan.delivery.webserver.Addresses.getProxyServerAddress(Addresses.java:101) ~[Plan-5.4-build-1722.jar:?]
        at com.djrapitops.plan.delivery.webserver.Addresses.getMainAddress(Addresses.java:72) ~[Plan-5.4-build-1722.jar:?]
        at com.djrapitops.plan.commands.subcommands.LinkCommands.getAddress(LinkCommands.java:75) ~[Plan-5.4-build-1722.jar:?]
        at com.djrapitops.plan.commands.subcommands.LinkCommands.onNetworkCommand(LinkCommands.java:192) ~[Plan-5.4-build-1722.jar:?]
        at com.djrapitops.plan.commands.use.CommandWithSubcommands.executeCommand(CommandWithSubcommands.java:121) ~[Plan-5.4-build-1722.jar:?]
        at com.djrapitops.plan.commands.use.CommandWithSubcommands.onCommand(CommandWithSubcommands.java:98) ~[Plan-5.4-build-1722.jar:?]
        at com.djrapitops.plan.commands.use.BukkitCommand.lambda$onCommand$0(BukkitCommand.java:60) ~[Plan-5.4-build-1722.jar:?]
        at net.playeranalytics.plugin.scheduling.UnscheduledBukkitTask.run(UnscheduledBukkitTask.java:22) ~[Plan-5.4-build-1722.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-386]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-386]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-386]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        Suppressed: java.nio.file.FileAlreadyExistsException: plugins/Plan/logs/EnableException-ef79dac831.txt
                at sun.nio.fs.UnixException.translateToIOException(UnixException.java:94) ~[?:?]
                at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
                at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
                at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218) ~[?:?]
                at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484) ~[?:?]
                at java.nio.file.Files.newOutputStream(Files.java:228) ~[?:?]
                at java.nio.file.Files.write(Files.java:3582) ~[?:?]
                at java.nio.file.Files.write(Files.java:3634) ~[?:?]
                at com.djrapitops.plan.utilities.logging.PluginErrorLogger.writeNew(PluginErrorLogger.java:229) ~[Plan-5.4-build-1722.jar:?]
                at com.djrapitops.plan.utilities.logging.PluginErrorLogger.logNew(PluginErrorLogger.java:222) ~[Plan-5.4-build-1722.jar:?]
                at com.djrapitops.plan.utilities.logging.PluginErrorLogger.logToFile(PluginErrorLogger.java:112) ~[Plan-5.4-build-1722.jar:?]
                at com.djrapitops.plan.utilities.logging.PluginErrorLogger.log(PluginErrorLogger.java:102) ~[Plan-5.4-build-1722.jar:?]
                at com.djrapitops.plan.utilities.logging.PluginErrorLogger.warn(PluginErrorLogger.java:91) ~[Plan-5.4-build-1722.jar:?]
                at com.djrapitops.plan.commands.PlanCommand.handleException(PlanCommand.java:91) ~[Plan-5.4-build-1722.jar:?]
                at com.djrapitops.plan.commands.use.CommandWithSubcommands.onCommand(CommandWithSubcommands.java:100) ~[Plan-5.4-build-1722.jar:?]
                at com.djrapitops.plan.commands.use.BukkitCommand.lambda$onCommand$0(BukkitCommand.java:60) ~[Plan-5.4-build-1722.jar:?]
                at net.playeranalytics.plugin.scheduling.UnscheduledBukkitTask.run(UnscheduledBukkitTask.java:22) ~[Plan-5.4-build-1722.jar:?]
                at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-386]
                at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-386]
                at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-386]
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
                at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:25:20 WARN]: [Plan] Ran into EnableException - logged to plugins/Plan/logs/EnableException-ef79dac831.txt
[13:25:20 WARN]: [Plan] (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[13:25:20 WARN]: [Plan] Error msg: "Database failed to open, Query has failed. (This exception is necessary to not keep query threads waiting)"
[13:25:20 WARN]: [Plan] Error msg: "Database failed to open, Query has failed. (This exception is necessary to not keep query threads waiting)"

### Plugin versions
[13:27:24 INFO]:   Версия: 5.4 build 1722
[13:27:24 INFO]:   Доступно обновление: Нет
[13:27:24 INFO]:   Текущая база данных: MySQL (OPEN)
[13:27:24 INFO]:   Подключен к прокси: Нет

### Additional information
paper 1.18.2

**Comment by Kopo942** [comment]
@Futodama Can you provide the contents of EnableException-ef79dac831.txt

**Comment by Futodama** [comment]
ef79dac831 - Last occurred: 2022-06-28 Occurrences: 1
---- Context 1 ----
Plan v5.4 build 1722
Paper git-Paper-386 (MC: 1.18.2)
Server v1.18.2-R0.1-SNAPSHOT

com.djrapitops.plan.commands.use.BukkitCMDSender@4629d163
Arguments{args=[network]}

---- Stacktrace ----
com.djrapitops.plan.exceptions.EnableException: Database failed to open, Query has failed. (This exception is necessary to not keep query threads waiting)
   Plan-5.4-build-1722.jar//com.djrapitops.plan.storage.database.DBAccessLock.checkAccess(DBAccessLock.java:61)
   Plan-5.4-build-1722.jar//com.djrapitops.plan.storage.database.DBAccessLock.checkAccess(DBAccessLock.java:43)
   Plan-5.4-build-1722.jar//com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:315)
   Plan-5.4-build-1722.jar//com.djrapitops.plan.delivery.webserver.Addresses.getProxyServerAddress(Addresses.java:101)
   Plan-5.4-build-1722.jar//com.djrapitops.plan.delivery.webserver.Addresses.getMainAddress(Addresses.java:72)
   Plan-5.4-build-1722.jar//com.djrapitops.plan.commands.subcommands.LinkCommands.getAddress(LinkCommands.java:75)
   Plan-5.4-build-1722.jar//com.djrapitops.plan.commands.subcommands.LinkCommands.onNetworkCommand(LinkCommands.java:192)
   Plan-5.4-build-1722.jar//com.djrapitops.plan.commands.use.CommandWithSubcommands.executeCommand(CommandWithSubcommands.java:121)
   Plan-5.4-build-1722.jar//com.djrapitops.plan.commands.use.CommandWithSubcommands.onCommand(CommandWithSubcommands.java:98)
   Plan-5.4-build-1722.jar//com.djrapitops.plan.commands.use.BukkitCommand.lambda$onCommand$0(BukkitCommand.java:60)
   Plan-5.4-build-1722.jar//net.playeranalytics.plugin.scheduling.UnscheduledBukkitTask.run(UnscheduledBukkitTask.java:22)
   org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
   org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
   com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
   java.base/java.lang.Thread.run(Thread.java:833)

**Comment by AuroraLS3** [comment]
This error is indicator that another error occurred earlier that caused the database to fail to open.

Please send the log contents from Plan logo to end of errors, and logs for any mentioned CompletionExceptions

**Comment by Futodama** [comment]
> This error is indicator that another error occurred earlier that caused the database to fail to open.
> 
> Please send the log contents from Plan logo to end of errors, and logs for any mentioned CompletionExceptions

Easy to say, hard to do. Tell me what you need more precisely?

**Comment by Kopo942** [comment]
Post the full `latest.log` for example. Also go through all recent files in `/plugins/Plan/logs/` and check if any of them have CompletionExceptions; if do, post the log file here.

**Comment by AuroraLS3** [comment]
Yes what Kopo said

**Comment by AuroraLS3** [comment]
Closing as stale. Reply with the necessary logs to reopen

**Comment by iVillager** [comment]
I'm getting the same error 

`f1fe77c434 - Last occurred: 2022-07-23 Occurrences: 1
---- Context 1 ----
Plan v5.4 build 1722
BungeeCord git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496
Server vgit:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496


---- Stacktrace ----
com.djrapitops.plan.exceptions.EnableException: Database failed to open, Query has failed. (This exception is necessary to not keep query threads waiting)
   com.djrapitops.plan.storage.database.DBAccessLock.checkAccess(DBAccessLock.java:61)
   com.djrapitops.plan.storage.database.DBAccessLock.checkAccess(DBAccessLock.java:43)
   com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:315)
   com.djrapitops.plan.identification.UUIDUtility.getNameOf(UUIDUtility.java:71)
   com.djrapitops.plan.extension.ExtensionSvc.updatePlayerValues(ExtensionSvc.java:169)
   com.djrapitops.plan.extension.implementation.CallerImplementation.lambda$updatePlayerData$0(CallerImplementation.java:53)
   com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:78)
   java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
   java.base/java.lang.Thread.run(Thread.java:831)
`
