### ISSUE TITLE
Velocity proxy server throws error on startup.

### ISSUE THREAD

**Issue by ItsRainingHP** [plan-player-analytics/Plan#2497]
### Describe the issue
Successfully got the Plan plugin to work on a game server. Placing the Plan.jar inside plugins folder on Velocity immediately throws a Logger error.

### Exceptions & Other Logs
1) [Guice/MissingImplementation]: No implementation for org.slf4j.Logger was bound.

```
[10:02:23] [main/INFO]: Booting up Velocity 3.1.2-SNAPSHOT (git-6be344d9-b162)...
[10:02:23] [main/INFO]: Loading localizations...
[10:02:24] [main/INFO]: Connections will use epoll channels, libdeflate (Linux x86_64) compression, OpenSSL 1.1.x (Linux x86_64) ciphers
[10:02:24] [main/INFO]: Loading plugins...
[10:02:24] [main/INFO]: Loaded plugin luckperms 5.4.33 by Luck
[10:02:24] [main/ERROR]: Can't create plugin plan
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) [Guice/MissingImplementation]: No implementation for org.slf4j.Logger was bound.

Did you mean?
org.slf4j.Logger bound at VelocityPluginModule.configure(VelocityPluginModule.java:50)

Requested by:
1 : PlanVelocity.<init>(PlanVelocity.java:84)
\_ for 2nd parameter
at VelocityPluginModule.configure(VelocityPluginModule.java:48)
2 : Metrics$Factory.<init>(Metrics.java:49)
\_ for 2nd parameter
at PlanVelocity.<init>(PlanVelocity.java:84)
\_ for 4th parameter
at VelocityPluginModule.configure(VelocityPluginModule.java:48)

Learn more:
https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION

1 error

======================
Full classname legend:
======================
Metrics$Factory: "plan.org.bstats.velocity.Metrics$Factory"
PlanVelocity: "com.djrapitops.plan.PlanVelocity"
VelocityPluginModule: "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
org.slf4j.Logger: "plan.org.slf4j.Logger"
========================
End of classname legend:
========================

at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:568) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:163) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
at com.google.inject.Guice.createInjector(Guice.java:87) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
at com.google.inject.Guice.createInjector(Guice.java:69) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
at com.google.inject.Guice.createInjector(Guice.java:59) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:119) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:151) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:346) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:224) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
at com.velocitypowered.proxy.Velocity.main(Velocity.java:64) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
[10:02:24] [main/INFO]: Loaded 1 plugins
[10:02:24] [Velocity Async Event Executor - #0/INFO]: __
[10:02:24] [Velocity Async Event Executor - #0/INFO]: | |__) LuckPerms v5.4.33
[10:02:24] [Velocity Async Event Executor - #0/INFO]: |___ | Running on Velocity - Velocity
[10:02:24] [Velocity Async Event Executor - #0/INFO]:
[10:02:24] [Velocity Async Event Executor - #0/INFO]: Loading configuration...
[10:02:24] [Velocity Async Event Executor - #0/INFO]: Loading storage provider... [MYSQL]
[10:02:24] [Velocity Async Event Executor - #0/INFO]: luckperms-hikari - Starting...
[10:02:24] [Velocity Async Event Executor - #0/INFO]: luckperms-hikari - Start completed.
[10:02:24] [Velocity Async Event Executor - #0/INFO]: Loading messaging service... [SQL]
[10:02:24] [Velocity Async Event Executor - #0/INFO]: Loading internal permission managers...
[10:02:24] [Velocity Async Event Executor - #0/INFO]: Performing initial data load...
[10:02:24] [Velocity Async Event Executor - #0/INFO]: Successfully enabled. (took 720ms)
[10:02:25] [Netty epoll Boss #0/INFO]: Listening on /0.0.0.0:25577
[10:02:25] [main/INFO]: Done (1.48s)!
```

### Plugin versions
Plan 5.5 Dev Build 1791
MC 1.19
LP Velocity 5.4.33

**Comment by AuroraLS3** [comment]
You can use this build until it's fixed https://github.com/plan-player-analytics/Plan/actions/runs/2668170724

**Comment by ItsRainingHP** [comment]
This worked thank you!
