### ISSUE TITLE
Dev Build 1791 no longer Quilt Compatible

### ISSUE THREAD

**Issue by SulpherStaer** [plan-player-analytics/Plan#2517]
### Describe the issue
The 1791 dev build prevents server bootup on quilt, where the previous devbuild 1740 does not.

### Exceptions & Other Logs

```
[15:21:14] [main/WARN]: Mixin transformation of org.quiltmc.loader.impl.launch.knot.UnusedEmptyTargetClass failed
java.util.ServiceConfigurationError: org.slf4j.spi.SLF4JServiceProvider: Provider org.slf4j.nop.NOPServiceProvider not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:593) ~[?:?]
	at java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219) ~[?:?]
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228) ~[?:?]
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273) ~[?:?]
	at java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309) ~[?:?]
	at java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393) ~[?:?]
	at org.slf4j.LoggerFactory.findServiceProviders(LoggerFactory.java:106) ~[slf4j-api-1.8.0-beta4.jar:?]
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:149) ~[slf4j-api-1.8.0-beta4.jar:?]
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:141) ~[slf4j-api-1.8.0-beta4.jar:?]
	at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:419) ~[slf4j-api-1.8.0-beta4.jar:?]
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:405) ~[slf4j-api-1.8.0-beta4.jar:?]
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:354) ~[slf4j-api-1.8.0-beta4.jar:?]
	at eu.pb4.polymer.impl.PolymerImpl.<clinit>(PolymerImpl.java:32) ~[polymer-0.2.10+1.19.1.jar-ce308686-62b3-43fb-ad91-60200c49c283-nested.jar:?]
	at eu.pb4.polymer.mixin.PolymerMixinConfigPlugin.shouldApplyMixin(PolymerMixinConfigPlugin.java:30) ~[polymer-0.2.10+1.19.1.jar-ce308686-62b3-43fb-ad91-60200c49c283-nested.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.shouldApplyMixin(PluginHandle.java:132) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.shouldApplyMixin(MixinInfo.java:988) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:953) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:882) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:243) [quilt-loader-0.17.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:146) [quilt-loader-0.17.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadIntoTarget(KnotClassLoader.java:182) [quilt-loader-0.17.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:161) [quilt-loader-0.17.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:70) [quilt-loader-0.17.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:31) [quilt-loader-0.17.1.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.quiltmc.loader.impl.launch.server.QuiltServerLauncher.main(QuiltServerLauncher.java:63) [quilt-loader-0.17.1.jar:?]
[15:21:15] [main/ERROR]: Uncaught exception in thread "main"
java.lang.RuntimeException: An exception occurred when launching the server!
	at org.quiltmc.loader.impl.launch.server.QuiltServerLauncher.main(QuiltServerLauncher.java:65) ~[quilt-loader-0.17.1.jar:?]
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.quiltmc.loader.impl.launch.server.QuiltServerLauncher.main(QuiltServerLauncher.java:63) ~[quilt-loader-0.17.1.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of org.quiltmc.loader.impl.launch.knot.UnusedEmptyTargetClass failed
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:248) ~[quilt-loader-0.17.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:146) ~[quilt-loader-0.17.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadIntoTarget(KnotClassLoader.java:182) ~[quilt-loader-0.17.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:161) ~[quilt-loader-0.17.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:70) ~[quilt-loader-0.17.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:31) ~[quilt-loader-0.17.1.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.quiltmc.loader.impl.launch.server.QuiltServerLauncher.main(QuiltServerLauncher.java:63) ~[quilt-loader-0.17.1.jar:?]
Caused by: java.util.ServiceConfigurationError: org.slf4j.spi.SLF4JServiceProvider: Provider org.slf4j.nop.NOPServiceProvider not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:593) ~[?:?]
	at java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219) ~[?:?]
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228) ~[?:?]
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273) ~[?:?]
	at java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309) ~[?:?]
	at java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393) ~[?:?]
	at org.slf4j.LoggerFactory.findServiceProviders(LoggerFactory.java:106) ~[slf4j-api-1.8.0-beta4.jar:?]
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:149) ~[slf4j-api-1.8.0-beta4.jar:?]
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:141) ~[slf4j-api-1.8.0-beta4.jar:?]
	at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:419) ~[slf4j-api-1.8.0-beta4.jar:?]
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:405) ~[slf4j-api-1.8.0-beta4.jar:?]
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:354) ~[slf4j-api-1.8.0-beta4.jar:?]
	at eu.pb4.polymer.impl.PolymerImpl.<clinit>(PolymerImpl.java:32) ~[polymer-0.2.10+1.19.1.jar-ce308686-62b3-43fb-ad91-60200c49c283-nested.jar:?]
	at eu.pb4.polymer.mixin.PolymerMixinConfigPlugin.shouldApplyMixin(PolymerMixinConfigPlugin.java:30) ~[polymer-0.2.10+1.19.1.jar-ce308686-62b3-43fb-ad91-60200c49c283-nested.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.shouldApplyMixin(PluginHandle.java:132) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.shouldApplyMixin(MixinInfo.java:988) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:953) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:882) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:243) ~[quilt-loader-0.17.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:146) ~[quilt-loader-0.17.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadIntoTarget(KnotClassLoader.java:182) ~[quilt-loader-0.17.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:161) ~[quilt-loader-0.17.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:70) ~[quilt-loader-0.17.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:31) ~[quilt-loader-0.17.1.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.quiltmc.loader.impl.launch.server.QuiltServerLauncher.main(QuiltServerLauncher.java:63) ~[quilt-loader-0.17.1.jar:?]
```

### Plugin versions

Quilt Loader 0.17.1
qfapi-4.0.0-beta.1_qsl-3.0.0-beta.2_fapi-0.58.5_mc-1.19.1
PlanFabric-5.5-dev-build-1791

### Additional information
This was tested with no other mods installed & confirmed to be a plan/quilt incompatibility issue that was introduced in 1791 that does not exist in 1740.

**Comment by SulpherStaer** [comment]
[latest.log](https://github.com/plan-player-analytics/Plan/files/9235222/latest.log)

**Comment by AuroraLS3** [comment]
Missing ALPN processor not being loaded by ServiceLoader seems to have something to do with relocations not being applied in META-INF/services for fabric jar
![image](https://user-images.githubusercontent.com/24460436/185095023-bbf558b1-1a57-4056-870c-6a9e48727328.png)
