### ISSUE TITLE
Error with plugin

### ISSUE THREAD

**Issue by Foxius** [plan-player-analytics/Plan#2564]
java.lang.NullPointerException: Cannot invoke "com.djrapitops.plan.identification.Server.isProxy()" because "server" is null | Failed to get a response
    com.djrapitops.plan.delivery.webserver.resolver.RootPageResolver.getResponse(RootPageResolver.java:63)
    com.djrapitops.plan.delivery.webserver.resolver.RootPageResolver.resolve(RootPageResolver.java:57)
    com.djrapitops.plan.delivery.webserver.ResponseResolver.tryToGetResponse(ResponseResolver.java:199)
    com.djrapitops.plan.delivery.webserver.ResponseResolver.getResponse(ResponseResolver.java:150)
    com.djrapitops.plan.delivery.webserver.RequestHandler.getResponse(RequestHandler.java:137)
    com.djrapitops.plan.delivery.webserver.RequestHandler.handle(RequestHandler.java:100)
    jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
    jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
    jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
    jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:733)
    jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
    jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:700)
    java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    java.base/java.lang.Thread.run(Thread.java:833)

**Comment by AuroraLS3** [comment]
Happens when webserver is accessed before Plan has fully enabled

**Comment by Foxius** [comment]
How to fix?

**Comment by AuroraLS3** [comment]
What does Plan say on the console during enable?

**Comment by Foxius** [comment]
[05:58:27] [main/INFO]: Booting up Velocity 3.1.2-SNAPSHOT (git-cae41c33-b177)...
[05:58:27] [main/INFO]: Loading localizations...
[05:58:27] [main/INFO]: Connections will use epoll channels, libdeflate (Linux aarch64) compression, OpenSSL (Linux aarch64) ciphers
[05:58:27] [main/WARN]: You are currently using a deprecated configuration version. The "forwarding-secret" parameter has been recognized as a security concern and has been removed in config version 2.0. It's recommended you rename your current "velocity.toml" to something else to allow Velocity to generate a config file of the new version. You may then configure that file as you normally would. The only differences are the config-version and "forwarding-secret" has been replaced by "forwarding-secret-file".
[05:58:27] [main/WARN]: The proxy is running in offline mode! This is a security risk and you will NOT receive any support!
[05:58:27] [main/WARN]: Player info forwarding is disabled! All players will appear to be connecting from the proxy and will have offline-mode UUIDs.
[05:58:28] [main/INFO]: Loading plugins...
[05:58:28] [main/INFO]: Loaded plugin authmevelocity 3.0.1 by xQuickGlare, 4drian3d
[05:58:28] [main/INFO]: Loaded plugin minimotd-velocity 2.0.8 by jmp
[05:58:28] [main/INFO]: Loaded plugin plan 5.4 build 1722 by AuroraLS3
[05:58:28] [main/INFO]: Loaded plugin skinsrestorer 14.2.3 by knat, AlexProgrammerDE, Blackfire62, McLive
[05:58:28] [main/INFO]: Loaded 4 plugins
[05:58:28] [Velocity Async Event Executor - #0/INFO]:  --- AuthMeVelocity ---
[05:58:28] [Velocity Async Event Executor - #0/INFO]: AuthServers: [auth1, auth2]
[05:58:29] [Velocity Async Event Executor - #0/INFO]: 
[05:58:29] [Velocity Async Event Executor - #0/INFO]:            ██▌
[05:58:29] [Velocity Async Event Executor - #0/INFO]:      ██▌   ██▌
[05:58:29] [Velocity Async Event Executor - #0/INFO]:   ██▌██▌██▌██▌  Player Analytics
[05:58:29] [Velocity Async Event Executor - #0/INFO]:   ██▌██▌██▌██▌  v5.4 build 1722
[05:58:29] [Velocity Async Event Executor - #0/INFO]: 
[05:58:29] [Velocity Async Event Executor - #0/INFO]: Locale: 'English' by AuroraLS3
[05:58:29] [Velocity Async Event Executor - #0/INFO]: Downloading MySQL Driver, this may take a while...
[05:58:29] [Velocity Task Scheduler - #1/INFO]: You're using the latest version.
[05:58:29] [Plan MySQLDB-transaction-thread-1/INFO]: Database: Making sure schema is up to date..
[05:58:29] [Velocity Async Event Executor - #0/INFO]: MySQL-database connection established.
[05:58:29] [Velocity Async Event Executor - #0/INFO]: WebServer: Certificate KeyStore File not Found: plugins/plan/Cert.jks
[05:58:29] [Velocity Async Event Executor - #0/INFO]: WebServer: No Certificate -> Using HTTP-server for Visualization.
[05:58:29] [Velocity Async Event Executor - #0/INFO]: WebServer: User Authorization Disabled! (Not secure over HTTP)
[05:58:29] [Velocity Async Event Executor - #0/INFO]: Webserver running on PORT 26656 ( http://138.3.246.184:26656 )
[05:58:29] [Velocity Async Event Executor - #0/INFO]: Loading server identifying information
[05:58:29] [Plan MySQLDB-transaction-thread-1/ERROR]: Database failed to open, com.djrapitops.plan.storage.database.transactions.init.CreateTablesTransaction failed to be executed.
[05:58:29] [Plan MySQLDB-transaction-thread-1/ERROR]: Error msg: com.djrapitops.plan.storage.database.transactions.init.CreateTablesTransaction failed to execute and database could not be opened: SQL Failure: Specified key was too long; max key length is 767 bytes
[05:58:29] [Velocity Async Event Executor - #0/ERROR]: ----------------------------------------
[05:58:29] [Velocity Async Event Executor - #0/ERROR]: Error: Database failed to open, Query has failed. (This exception is necessary to not keep query threads waiting)
[05:58:29] [Velocity Async Event Executor - #0/ERROR]: ----------------------------------------
[05:58:29] [Velocity Async Event Executor - #0/ERROR]: Plugin Failed to Initialize Correctly. If this issue is caused by config settings you can use /planvelocity reload
[05:58:29] [Velocity Async Event Executor - #0/INFO]: Processing complete.
[05:58:29] [Velocity Async Event Executor - #0/INFO]: Waiting for unfinished transactions to avoid data loss..
[05:58:29] [Plan Non critical-pool-1/ERROR]: Failed to read plugins/plan/logs/EnableException-88d20bd3d7.txt deleting file
[05:58:29] [Plan Non critical-pool-1/WARN]: Ran into EnableException - logged to plugins/plan/logs/EnableException-88d20bd3d7.txt
[05:58:29] [Plan Non critical-pool-1/WARN]: (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[05:58:29] [Plan Non critical-pool-1/WARN]: Error msg: "Database failed to open, Query has failed. (This exception is necessary to not keep query threads waiting)"
[05:58:29] [Plan MySQLDB-transaction-thread-1/ERROR]: Ran into CompletionException - logged to plugins/plan/logs/CompletionException-1e4d405ed2.txt
[05:58:29] [Plan MySQLDB-transaction-thread-1/ERROR]: (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[05:58:29] [Plan MySQLDB-transaction-thread-1/ERROR]: Error msg: "com.djrapitops.plan.exceptions.database.FatalDBException: com.djrapitops.plan.storage.database.transactions.init.CreateTablesTransaction failed to execute and database could not be opened: SQL Failure: Specified key was too long; max key length is 767 bytes"
[05:58:29] [Plan MySQLDB-transaction-thread-1/ERROR]: CRITICAL error triggered a plugin shutdown.
[05:58:29] [Plan MySQLDB-transaction-thread-1/INFO]: Processing complete.
[05:58:29] [Plan MySQLDB-transaction-thread-1/INFO]: Webserver has been disabled.
[05:58:29] [Plan MySQLDB-transaction-thread-1/INFO]: Player Analytics Disabled.
[05:58:29] [Velocity Async Event Executor - #0/INFO]: Transaction queue closed.
[05:58:29] [Velocity Async Event Executor - #0/INFO]: Webserver has been disabled.
[05:58:29] [Velocity Async Event Executor - #0/INFO]: Player Analytics Disabled.
[05:58:29] [Velocity Task Scheduler - #0/INFO]: [32;1m----------------------------------------------[0;39m
[05:58:29] [Velocity Task Scheduler - #0/INFO]: [32;1m    +==================+[0;39m
[05:58:29] [Velocity Task Scheduler - #0/INFO]: [32;1m    |   SkinsRestorer  |[0;39m
[05:58:29] [Velocity Task Scheduler - #0/INFO]: [32;1m    +==================+[0;39m
[05:58:29] [Velocity Task Scheduler - #0/INFO]: [32;1m----------------------------------------------[0;39m
[05:58:29] [Velocity Task Scheduler - #0/INFO]: [36;1m    Current version: [32;1m14.2.3[0;39m
[05:58:29] [Velocity Task Scheduler - #0/INFO]: [32;1m    This is the latest version![0;39m
[05:58:29] [Velocity Task Scheduler - #0/INFO]: [32;1m----------------------------------------------[0;39m
[05:58:29] [Velocity Async Event Executor - #0/INFO]: Enabled SkinsRestorer v14.2.3[0;39m
[05:58:29] [Netty epoll Boss #0/INFO]: Listening on /[0:0:0:0:0:0:0:0%0]:25565
[05:58:29] [main/INFO]: Done (2.64s)!
[05:59:13] [Shutdown thread/INFO]: Shutting down the proxy...
[05:59:13] [SIGCONT handler/ERROR]: Exception in thread "SIGCONT handler" java.io.IOError: java.io.IOException: Error executing 'stty -a': stty: 'standard input': Input/output error
[05:59:13] [SIGCONT handler/ERROR]: 	at org.jline.terminal.impl.AbstractPosixTerminal.getAttributes(AbstractPosixTerminal.java:46)
[05:59:13] [SIGCONT handler/ERROR]: 	at org.jline.terminal.impl.AbstractTerminal.enterRawMode(AbstractTerminal.java:135)
[05:59:13] [SIGCONT handler/ERROR]: 	at org.jline.reader.impl.LineReaderImpl.handleSignal(LineReaderImpl.java:1043)
[05:59:13] [SIGCONT handler/ERROR]: 	at org.jline.terminal.impl.AbstractTerminal.raise(AbstractTerminal.java:89)
[05:59:13] [SIGCONT handler/ERROR]: 	at org.jline.terminal.impl.PosixSysTerminal.lambda$handle$1(PosixSysTerminal.java:65)
[05:59:13] [SIGCONT handler/ERROR]: 	at org.jline.utils.Signals.lambda$register$1(Signals.java:53)
[05:59:13] [SIGCONT handler/ERROR]: 	at jdk.proxy2/jdk.proxy2.$Proxy50.handle(Unknown Source)
[05:59:13] [SIGCONT handler/ERROR]: 	at jdk.unsupported/sun.misc.Signal$InternalMiscHandler.handle(Signal.java:198)
[05:59:13] [SIGCONT handler/ERROR]: 	at java.base/jdk.internal.misc.Signal$1.run(Signal.java:219)
[05:59:13] [SIGCONT handler/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[05:59:13] [SIGCONT handler/ERROR]: Caused by: java.io.IOException: Error executing 'stty -a': stty: 'standard input': Input/output error
[05:59:13] [SIGCONT handler/ERROR]: 	at org.jline.utils.ExecHelper.exec(ExecHelper.java:42)
[05:59:13] [SIGCONT handler/ERROR]: 	at org.jline.terminal.impl.ExecPty.doGetConfig(ExecPty.java:175)
[05:59:13] [SIGCONT handler/ERROR]: 	at org.jline.terminal.impl.ExecPty.getAttr(ExecPty.java:87)
[05:59:13] [SIGCONT handler/ERROR]: 	at org.jline.terminal.impl.AbstractPosixTerminal.getAttributes(AbstractPosixTerminal.java:44)
[05:59:13] [SIGCONT handler/ERROR]: 	... 9 more
[05:59:13] [Shutdown thread/INFO]: Closing endpoint /0.0.0.0:25565
[05:59:13] [main/ERROR]: Exception in thread "main" java.io.IOError: java.io.IOException: Error executing 'stty -a': stty: 'standard input': Input/output error
[05:59:13] [main/ERROR]: 	at org.jline.terminal.impl.AbstractPosixTerminal.setAttributes(AbstractPosixTerminal.java:54)
[05:59:13] [main/ERROR]: 	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:650)
[05:59:13] [main/ERROR]: 	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:418)
[05:59:13] [main/ERROR]: 	at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:158)
[05:59:13] [main/ERROR]: 	at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141)
[05:59:13] [main/ERROR]: 	at com.velocitypowered.proxy.Velocity.main(Velocity.java:70)
[05:59:13] [JLine Shutdown Hook/WARN]: Task failed
java.io.IOException: Error executing 'stty -a': stty: 'standard input': Input/output error
	at org.jline.utils.ExecHelper.exec(ExecHelper.java:42) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at org.jline.terminal.impl.ExecPty.doGetConfig(ExecPty.java:175) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at org.jline.terminal.impl.ExecPty.getAttr(ExecPty.java:87) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at org.jline.terminal.impl.ExecPty.doSetAttr(ExecPty.java:93) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at org.jline.terminal.impl.AbstractPty.setAttr(AbstractPty.java:29) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at org.jline.terminal.impl.AbstractPosixTerminal.doClose(AbstractPosixTerminal.java:76) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at org.jline.terminal.impl.PosixSysTerminal.doClose(PosixSysTerminal.java:95) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at org.jline.terminal.impl.AbstractTerminal.close(AbstractTerminal.java:98) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at org.jline.utils.ShutdownHooks.runTasks(ShutdownHooks.java:55) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at org.jline.utils.ShutdownHooks.access$000(ShutdownHooks.java:21) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
	at org.jline.utils.ShutdownHooks$1.run(ShutdownHooks.java:36) ~[velocity-3.1.2-SNAPSHOT-177.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
[05:59:13] [main/ERROR]: Caused by: java.io.IOException: Error executing 'stty -a': stty: 'standard input': Input/output error
[05:59:13] [main/ERROR]: 	at org.jline.utils.ExecHelper.exec(ExecHelper.java:42)
[05:59:13] [main/ERROR]: 	at org.jline.terminal.impl.ExecPty.doGetConfig(ExecPty.java:175)
[05:59:13] [main/ERROR]: 	at org.jline.terminal.impl.ExecPty.getAttr(ExecPty.java:87)
[05:59:13] [main/ERROR]: 	at org.jline.terminal.impl.ExecPty.doSetAttr(ExecPty.java:93)
[05:59:13] [main/ERROR]: 	at org.jline.terminal.impl.AbstractPty.setAttr(AbstractPty.java:29)
[05:59:13] [main/ERROR]: 	at org.jline.terminal.impl.AbstractPosixTerminal.setAttributes(AbstractPosixTerminal.java:52)
[05:59:13] [main/ERROR]: 	... 5 more

**Comment by AuroraLS3** [comment]
Aha, I see - your issue is the same as https://github.com/plan-player-analytics/Plan/issues/2477

- You can update to the latest dev release https://github.com/plan-player-analytics/Plan/releases, that has this fixed
- You can also update your MySQL, that has this fixed
