### ISSUE TITLE
Could Not Load Plan in the plugins folder.

### ISSUE THREAD

**Issue by KaneHart** [plan-player-analytics/Plan#2838]
### Describe the issue
For some reason Plan does not load up.

### Exceptions & Other Logs

```
[06:13:26] [Server thread/ERROR]: Could not load 'plugins/Plan-5.5-build-2172.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `com.djrapitops.plan.Plan'
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:192) ~[PluginClassLoader.class:1.7.10-5.3]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:144) ~[JavaPluginLoader.class:1.7.10-5.3]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:333) ~[SimplePluginManager.class:1.7.10-5.3]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:256) [SimplePluginManager.class:1.7.10-5.3]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:307) [CraftServer.class:1.7.10-5.3]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:462) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:354) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:162) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:369) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0-builds.shipilev.net-openjdk-shenandoah-jdk8-b1-20220109]
Caused by: java.lang.ClassNotFoundException: Failed to remap class com.djrapitops.plan.Plan
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:535) ~[PluginClassLoader.class:1.7.10-5.3]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:456) ~[PluginClassLoader.class:1.7.10-5.3]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:212) ~[PluginClassLoader.class:1.7.10-5.3]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0-builds.shipilev.net-openjdk-shenandoah-jdk8-b1-20220109]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0-builds.shipilev.net-openjdk-shenandoah-jdk8-b1-20220109]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0-builds.shipilev.net-openjdk-shenandoah-jdk8-b1-20220109]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0-builds.shipilev.net-openjdk-shenandoah-jdk8-b1-20220109]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:190) ~[PluginClassLoader.class:1.7.10-5.3]
	... 12 more
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at net.md_5.specialsource.RemapperProcessor.process(RemapperProcessor.java:83) ~[RemapperProcessor.class:?]
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:491) ~[PluginClassLoader.class:1.7.10-5.3]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:456) ~[PluginClassLoader.class:1.7.10-5.3]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:212) ~[PluginClassLoader.class:1.7.10-5.3]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0-builds.shipilev.net-openjdk-shenandoah-jdk8-b1-20220109]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0-builds.shipilev.net-openjdk-shenandoah-jdk8-b1-20220109]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0-builds.shipilev.net-openjdk-shenandoah-jdk8-b1-20220109]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0-builds.shipilev.net-openjdk-shenandoah-jdk8-b1-20220109]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:190) ~[PluginClassLoader.class:1.7.10-5.3]
	... 12 more
```

### Plugin versions

5.5 build 2172
### Additional information

This is version 1.7.10 of Minecraft. It's worked before so I think this might be a new issue.

**Comment by AnttiMK** [comment]
Plan builds after 5.4 build 1722.1 require Java 11 or newer.

**Comment by AuroraLS3** [comment]
Use https://github.com/plan-player-analytics/Plan/releases/tag/5.4.1722.1 for 1.17.10

5.5 requires Java 11 and 1.17.10 does not support the newer version of Java.
