### ISSUE TITLE
issue loading plan waterfall

### ISSUE THREAD

**Issue by Nbgreen** [plan-player-analytics/Plan#2851]
### Describe the issue

plan doesn't load on my water fall server.

### Exceptions & Other Logs

java.lang.UnsupportedClassVersionError: com/djrapitops/plan/PlanBungee has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_352]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_352]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_352]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473) ~[?:1.8.0_352]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_352]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_352]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_352]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_352]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_352]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_352]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:44) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:37) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_352]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:270) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:276) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]

```
[latest.log](https://github.com/plan-player-analytics/Plan/files/10523997/latest.log)

```

### Plugin versions

Plan-5.5-build-2172

**Comment by AuroraLS3** [comment]
Plan 5.5 requires Java 11 to run

**Comment by Cyanoure** [comment]
Same problem. I cannot change java version at my hosting. BungeeCord uses Java 8.

**Comment by AuroraLS3** [comment]
https://github.com/plan-player-analytics/Plan/releases/tag/5.4.1722.1 is the last version to support Java 8
