### ISSUE TITLE
Folia support

### ISSUE THREAD

**Issue by qbasty** [plan-player-analytics/Plan#2962]
### I would like to be able to..

Add support to Folia (https://github.com/PaperMC/Folia)

### Is your feature request related to a problem? Please describe.

There's no problem.

**Comment by AuroraLS3** [comment]
Does everything work okay if you manually open up Plan.jar and edit plugin.yml to have line `folia-supported: true`?

**Comment by Kam471** [comment]
> Does everything work okay if you manually open up Plan.jar and edit plugin.yml to have line `folia-supported: true`?

Doesn't work for me

**Comment by SageSphinx63920** [comment]
Im going to test this after school too

**Comment by AuroraLS3** [comment]
> > Does everything work okay if you manually open up Plan.jar and edit plugin.yml to have line `folia-supported: true`?
> 
> Doesn't work for me

What happens instead?

**Comment by Kam471** [comment]
The plugin simply doesn't load, no errors or anything. Just like it is not there.

**Comment by AuroraLS3** [comment]
Interesting 🤔

**Comment by xiaoluofa** [comment]
[17:36:25 ERROR]: [Plan] Plan-v5.6 build 2703
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.handle(CraftScheduler.java:533) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:257) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:244) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.scheduler.BukkitRunnable.runTaskTimerAsynchronously(BukkitRunnable.java:140) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at net.playeranalytics.plugin.scheduling.UnscheduledBukkitTask.runTaskTimerAsynchronously(UnscheduledBukkitTask.java:41) ~[Plan-5.6-dev-build-2703.jar:?]
        at com.djrapitops.plan.settings.network.ServerSettingsManager.scheduleDBCheckTask(ServerSettingsManager.java:127) ~[Plan-5.6-dev-build-2703.jar:?]
        at com.djrapitops.plan.settings.network.ServerSettingsManager.enable(ServerSettingsManager.java:92) ~[Plan-5.6-dev-build-2703.jar:?]
        at com.djrapitops.plan.settings.BukkitConfigSystem.enable(BukkitConfigSystem.java:65) ~[Plan-5.6-dev-build-2703.jar:?]
        at com.djrapitops.plan.PlanSystem.enableSystems(PlanSystem.java:217) ~[Plan-5.6-dev-build-2703.jar:?]
        at com.djrapitops.plan.PlanSystem.enableForCommands(PlanSystem.java:158) ~[Plan-5.6-dev-build-2703.jar:?]
        at com.djrapitops.plan.PlanSystem.enable(PlanSystem.java:211) ~[Plan-5.6-dev-build-2703.jar:?]
        at com.djrapitops.plan.Plan.onEnable(Plan.java:82) ~[Plan-5.6-dev-build-2703.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:652) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:563) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:343) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[17:36:25 ERROR]: [Plan] Plugin Failed to Initialize Correctly. If this issue is caused by config settings you can use /plan reload
[17:36:25 ERROR]: [Plan] This error should be reported at https://github.com/plan-player-analytics/Plan/issues
[17:36:25 ERROR]: Error occurred while enabling Plan v5.6 build 2703 (Is it up to date?)
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.handle(CraftScheduler.java:533) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.cancelTasks(CraftScheduler.java:346) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at net.playeranalytics.plugin.scheduling.BukkitRunnableFactory.cancelAllKnownTasks(BukkitRunnableFactory.java:25) ~[Plan-5.6-dev-build-2703.jar:?]
        at com.djrapitops.plan.Plan.cancelAllTasks(Plan.java:169) ~[Plan-5.6-dev-build-2703.jar:?]
        at com.djrapitops.plan.Plan.onDisable(Plan.java:138) ~[Plan-5.6-dev-build-2703.jar:?]
        at com.djrapitops.plan.Plan.onEnable(Plan.java:101) ~[Plan-5.6-dev-build-2703.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:652) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:563) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:343) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[17:36:25 INFO]: [Plan] Disabling Plan v5.6 build 2703
[17:36:25 ERROR]: Error occurred (in the plugin loader) while disabling Plan v5.6 build 2703 (Is it up to date?)
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.handle(CraftScheduler.java:533) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.cancelTasks(CraftScheduler.java:346) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at net.playeranalytics.plugin.scheduling.BukkitRunnableFactory.cancelAllKnownTasks(BukkitRunnableFactory.java:25) ~[Plan-5.6-dev-build-2703.jar:?]
        at com.djrapitops.plan.Plan.cancelAllTasks(Plan.java:169) ~[Plan-5.6-dev-build-2703.jar:?]
        at com.djrapitops.plan.Plan.onDisable(Plan.java:138) ~[Plan-5.6-dev-build-2703.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:652) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:563) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:343) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by AuroraLS3** [comment]
There is not enough documentation for me to add support for it currently, and support would need some complex trickery in how the plugin is put together to avoid increasing Java version requirement. This might be reconsidered if the Folia project matures or documentation improves.

**Comment by ColdeZhang** [comment]
@AuroraLS3 
Hi I have added support for folia
#3617

**Comment by xiaoluofa** [comment]
> @AuroraLS3
> 
> Hi everyone, I have added support for folia
> 
> ![79dd6cb28399d93bbbd1af27f74c0764](https://private-user-images.githubusercontent.com/29792376/330354342-007a1702-df16-4366-8a7d-a55c41b4dffc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NTc3NjMsIm5iZiI6MTcxNTg1NzQ2MywicGF0aCI6Ii8yOTc5MjM3Ni8zMzAzNTQzNDItMDA3YTE3MDItZGYxNi00MzY2LThhN2QtYTU1YzQxYjRkZmZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDExMDQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlYjMzNmZjMGNkOGM0YmIwOTc3MTEwMDA2NGUxNzU4MWIyNzJkODZkYzRlN2U3MWU4YzZlNmMxMDA4MzJhYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C0hPNllWP7B8_hjwn1_1mzL0mzy8w3v14i0xxVitUc0)
> 
> #3617

可以提供一个构建好的版本来测试吗？

**Comment by ColdeZhang** [comment]
> > @AuroraLS3
> > Hi everyone, I have added support for folia
> > ![79dd6cb28399d93bbbd1af27f74c0764](https://private-user-images.githubusercontent.com/29792376/330354342-007a1702-df16-4366-8a7d-a55c41b4dffc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NTc3NjMsIm5iZiI6MTcxNTg1NzQ2MywicGF0aCI6Ii8yOTc5MjM3Ni8zMzAzNTQzNDItMDA3YTE3MDItZGYxNi00MzY2LThhN2QtYTU1YzQxYjRkZmZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDExMDQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlYjMzNmZjMGNkOGM0YmIwOTc3MTEwMDA2NGUxNzU4MWIyNzJkODZkYzRlN2U3MWU4YzZlNmMxMDA4MzJhYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C0hPNllWP7B8_hjwn1_1mzL0mzy8w3v14i0xxVitUc0)
> > #3617
> 
> 可以提供一个构建好的版本来测试吗？

sure, but...

**BE AWARE: THIS SHOULD NOT BE USED IN PROD-ENV BEFORE IT IS REVIEWED BY MAINTAINER.**

[Folia-support Plan 5.7](https://github.com/DeerGiteaMirror/Plan/releases/tag/release)

**Comment by 404forever1** [comment]
> > > @AuroraLS3
> > > 大家好，我添加了对 folia [#3617的支持](https://github.com/plan-player-analytics/Plan/pull/3617)
> > > ![79dd6cb28399d93bbbd1af27f74c0764](https://private-user-images.githubusercontent.com/29792376/330354342-007a1702-df16-4366-8a7d-a55c41b4dffc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NTc3NjMsIm5iZiI6MTcxNTg1NzQ2MywicGF0aCI6Ii8yOTc5MjM3Ni8zMzAzNTQzNDItMDA3YTE3MDItZGYxNi00MzY2LThhN2QtYTU1YzQxYjRkZmZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDExMDQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlYjMzNmZjMGNkOGM0YmIwOTc3MTEwMDA2NGUxNzU4MWIyNzJkODZkYzRlN2U3MWU4YzZlNmMxMDA4MzJhYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C0hPNllWP7B8_hjwn1_1mzL0mzy8w3v14i0xxVitUc0)
> > > [](https://github.com/plan-player-analytics/Plan/pull/3617)
> > 
> > 
> > 可以提供一个构建好的版本来测试吗？
> 
> 当然，但是……
> 
> **请注意：在维护人员审核之前，不应在 PROD-ENV 中使用它。**
> 
> [Folia 支持计划 5.7](https://github.com/DeerGiteaMirror/Plan/releases/tag/release)

404

**Comment by 404forever1** [comment]
> > > @AuroraLS3
> > > 大家好，我添加了对 folia [#3617 的支持](https://github.com/plan-player-analytics/Plan/pull/3617)
> > > ![79dd6cb28399d93bbbd1af27f74c0764](https://private-user-images.githubusercontent.com/29792376/330354342-007a1702-df16-4366-8a7d-a55c41b4dffc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NTc3NjMsIm5iZiI6MTcxNTg1NzQ2MywicGF0aCI6Ii8yOTc5MjM3Ni8zMzAzNTQzNDItMDA3YTE3MDItZGYxNi00MzY2LThhN2QtYTU1YzQxYjRkZmZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDExMDQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlYjMzNmZjMGNkOGM0YmIwOTc3MTEwMDA2NGUxNzU4MWIyNzJkODZkYzRlN2U3MWU4YzZlNmMxMDA4MzJhYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C0hPNllWP7B8_hjwn1_1mzL0mzy8w3v14i0xxVitUc0)
> > > [](https://github.com/plan-player-analytics/Plan/pull/3617)
> > 
> > 
> > 可以提供一个构建好的版本来测试吗？
> 
> 当然，但是……
> 
> **请注意：在维护人员审核之前，不宜在 PROD-ENV 中使用它。**
> 
> [Folia 支持计划 5.7](https://github.com/DeerGiteaMirror/Plan/releases/tag/release)

以前其实也有一个folia的fork但是那个不支持huskhome的hook，启动就冲突了

**Comment by ColdeZhang** [comment]
[download link](https://github.com/DeerGiteaMirror/Plan/releases/tag/untagged-891d7d6418b5090df423)

**Comment by 404forever1** [comment]
> [下载链接](https://github.com/DeerGiteaMirror/Plan/releases/tag/untagged-891d7d6418b5090df423)

虽然但是还是404
![image](https://github.com/plan-player-analytics/Plan/assets/168977890/f916b0c7-1800-44f9-a347-2d87514a31d4)

**Comment by ColdeZhang** [comment]
sry my bad, wait for a miniute

![image](https://github.com/plan-player-analytics/Plan/assets/29792376/4982172b-b898-4adf-b429-3546129e23ec)

**Comment by ColdeZhang** [comment]
[https://github.com/DeerGiteaMirror/Plan/releases/tag/folia-support-test-only](https://github.com/DeerGiteaMirror/Plan/releases/tag/folia-support-test-only)

**Comment by 404forever1** [comment]
> https://github.com/DeerGiteaMirror/Plan/releases/tag/folia-support-test-only

热加载不上，等炸服了

**Comment by 404forever1** [comment]
> https://github.com/DeerGiteaMirror/Plan/releases/tag/folia-support-test-only

实测，加载不上，红的。

**Comment by ColdeZhang** [comment]
> > https://github.com/DeerGiteaMirror/Plan/releases/tag/folia-support-test-only
> 
> 实测，加载不上，红的。 喜闻乐见，同样把其他插件的HOOK全部干碎了



> > https://github.com/DeerGiteaMirror/Plan/releases/tag/folia-support-test-only
> 
> 实测，加载不上，红的。 喜闻乐见，同样把其他插件的HOOK全部干碎了

Could you please post err logs here.

**Comment by ColdeZhang** [comment]
> > https://github.com/DeerGiteaMirror/Plan/releases/tag/folia-support-test-only
> 
> 实测，加载不上，红的。 喜闻乐见，同样把其他插件的HOOK全部干碎了

try about this [https://github.com/DeerGiteaMirror/Plan/releases/tag/folia-support-test-only](https://github.com/DeerGiteaMirror/Plan/releases/tag/folia-support-test-only)
