### ISSUE TITLE
Wrong version of `fabric-networking` used in `fabric.mod.json`

### ISSUE THREAD

**Issue by RubixDev** [plan-player-analytics/Plan#2969]
### Describe the issue
I wanted to investigate an incompatibility between this mod and Rug over at https://github.com/RubixDev/Rug/issues/35. However, when launching the game, the fabric mod resolution fails as seen below.

### Exceptions & Other Logs

```
[21:30:28] [main/ERROR] (FabricLoader) Incompatible mod set!
 net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
         - Install fabric-networking-v0, any version.
Unmet dependency listing:
         - Mod 'Plan' (plan) 5.5 build 2307 requires any version of fabric-networking-v0, which is missing!
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[?:?]
```

### Plugin versions
5.5.2307

### Additional information
It seems at some point you switched from `fabric-networking-v0` to `fabric-networking-api-v1` but forgot to mirror this change in the `fabric.mod.json` file.

`build.gradle` specifies `v1`:
https://github.com/plan-player-analytics/Plan/blob/a63313ba52928893c1a9557853b297c5c48f1b6e/Plan/fabric/build.gradle#L17-L24

`fabric.mod.json` specifies `v0`:
https://github.com/plan-player-analytics/Plan/blob/a63313ba52928893c1a9557853b297c5c48f1b6e/Plan/fabric/src/main/resources/fabric.mod.json#L15-L24

**Comment by AnttiMK** [comment]
JAR from PR branch available at https://github.com/plan-player-analytics/Plan/suites/12143930110/artifacts/640446401
