### ISSUE TITLE
Player Dog Crashes The Server

### ISSUE THREAD

**Issue by tropicdev** [plan-player-analytics/Plan#2991]
### Describe the issue

When one of our users gets a dog after some time, plan seems to crash the server instance.

### Exceptions & Other Logs

```
---- Minecraft Crash Report ----
// There are four lights!

Time: 2023-04-26 16:06:23
Description: Ticking entity

java.lang.NoSuchMethodError: 'net.minecraft.class_1309 net.minecraft.class_1321.method_6177()'
	at net.playeranalytics.plan.gathering.listeners.fabric.DeathEventListener.getOwner(DeathEventListener.java:136)
	at net.playeranalytics.plan.gathering.listeners.fabric.DeathEventListener.getCause(DeathEventListener.java:105)
	at net.playeranalytics.plan.gathering.listeners.fabric.DeathEventListener.lambda$register$1(DeathEventListener.java:76)
	at net.playeranalytics.plan.gathering.listeners.events.PlanFabricEvents.lambda$static$0(PlanFabricEvents.java:42)
	at net.playeranalytics.plan.gathering.listeners.fabric.DeathEventListener.lambda$register$0(DeathEventListener.java:63)
	at net.fabricmc.fabric.api.entity.event.v1.ServerEntityCombatEvents.lambda$static$0(ServerEntityCombatEvents.java:37)
	at net.minecraft.class_1309.handler$zcd000$fabric-entity-events-v1$onEntityKilledOther(class_1309.java:4156)
	at net.minecraft.class_1309.method_6078(class_1309.java:1328)
	at net.minecraft.class_1309.method_5643(class_1309.java:1186)
	at net.minecraft.class_1429.method_5643(class_1429.java:80)
	at net.minecraft.class_1493.method_6121(class_1493.java:338)
	at net.minecraft.class_1366.method_6288(class_1366.java:152)
	at net.minecraft.class_1366.method_6268(class_1366.java:144)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:120)
	at net.minecraft.class_1308.method_6023(class_1308.java:773)
	at net.minecraft.class_1309.method_6007(class_1309.java:2654)
	at net.minecraft.class_1308.method_6007(class_1308.java:544)
	at net.minecraft.class_1296.method_6007(class_1296.java:128)
	at net.minecraft.class_1429.method_6007(class_1429.java:57)
	at net.minecraft.class_1493.method_6007(class_1493.java:202)
	at net.minecraft.class_1309.method_5773(class_1309.java:2400)
	at net.minecraft.class_1308.method_5773(class_1308.java:344)
	at net.minecraft.class_1493.method_5773(class_1493.java:217)
	at net.minecraft.class_3218.method_18762(class_3218.java:722)
	at net.minecraft.class_1937.method_18472(class_1937.java:488)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:828)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.playeranalytics.plan.gathering.listeners.fabric.DeathEventListener.getOwner(DeathEventListener.java:136)
	at net.playeranalytics.plan.gathering.listeners.fabric.DeathEventListener.getCause(DeathEventListener.java:105)
	at net.playeranalytics.plan.gathering.listeners.fabric.DeathEventListener.lambda$register$1(DeathEventListener.java:76)
	at net.playeranalytics.plan.gathering.listeners.events.PlanFabricEvents.lambda$static$0(PlanFabricEvents.java:42)
	at net.playeranalytics.plan.gathering.listeners.fabric.DeathEventListener.lambda$register$0(DeathEventListener.java:63)
	at net.fabricmc.fabric.api.entity.event.v1.ServerEntityCombatEvents.lambda$static$0(ServerEntityCombatEvents.java:37)
	at net.minecraft.class_1309.handler$zcd000$fabric-entity-events-v1$onEntityKilledOther(class_1309.java:4156)
	at net.minecraft.class_1309.method_6078(class_1309.java:1328)
	at net.minecraft.class_1309.method_5643(class_1309.java:1186)
	at net.minecraft.class_1429.method_5643(class_1429.java:80)
	at net.minecraft.class_1493.method_6121(class_1493.java:338)
	at net.minecraft.class_1366.method_6288(class_1366.java:152)
	at net.minecraft.class_1366.method_6268(class_1366.java:144)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:120)
	at net.minecraft.class_1308.method_6023(class_1308.java:773)
	at net.minecraft.class_1309.method_6007(class_1309.java:2654)
	at net.minecraft.class_1308.method_6007(class_1308.java:544)
	at net.minecraft.class_1296.method_6007(class_1296.java:128)
	at net.minecraft.class_1429.method_6007(class_1429.java:57)
	at net.minecraft.class_1493.method_6007(class_1493.java:202)
	at net.minecraft.class_1309.method_5773(class_1309.java:2400)
	at net.minecraft.class_1308.method_5773(class_1308.java:344)
	at net.minecraft.class_1493.method_5773(class_1493.java:217)
	at net.minecraft.class_3218.method_18762(class_3218.java:722)
	at net.minecraft.class_1937.method_18472(class_1937.java:488)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)

-- Entity being ticked --
Details:
	Entity Type: minecraft:wolf (net.minecraft.class_1493)
	Entity ID: 196
	Entity Name: Wolf
	Entity's Exact location: 4401.09, 62.85, -11702.39
	Entity's Block location: World: (4401,62,-11703), Section: (at 1,14,9 in 275,3,-732; chunk contains blocks 4400,-64,-11712 to 4415,319,-11697), Region: (8,-23; contains chunks 256,-736 to 287,-705, blocks 4096,-64,-11776 to 4607,319,-11265)
	Entity's Momentum: -0.07, -0.45, 0.02
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:488)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:828)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 4 total; [class_3222['HaniBanani'/165, l='ServerLevel[world]', x=4400.68, y=62.00, z=-11703.70], class_3222['DinccDoncc'/342, l='ServerLevel[world]', x=6287.03, y=86.00, z=-2491.02], class_3222['PookMe'/1393, l='ServerLevel[world]', x=-5295.18, y=67.00, z=726.16], class_3222['Aikeko'/3399, l='ServerLevel[world]', x=-5296.40, y=67.00, z=727.64]]
	Chunk stats: 26040
	Level dimension: minecraft:overworld
	Level spawn location: World: (-3201,73,1163), Section: (at 15,9,11 in -201,4,72; chunk contains blocks -3216,-64,1152 to -3201,319,1167), Region: (-7,2; contains chunks -224,64 to -193,95, blocks -3584,-64,1024 to -3073,319,1535)
	Level time: 861864171 game time, 153443416 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 111820 (now: false), thunder time: 84978 (now: false)
	Known server brands: vanilla, fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:828)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Linux (aarch64) version 5.15.0-1027-oracle
	Java Version: 17.0.6, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 4163782240 bytes (3970 MiB) / 12884901888 bytes (12288 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 4
	Processor Vendor: aarch64
	Processor Name: 
	Identifier: aarch64 Family 8 Model 0xd0c Stepping r0x3p1
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 11994.09
	Virtual memory used (MB): 10909.25
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 19 total; -Xmx12288M -Xms12288M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:G1NewSizePercent=40 -XX:G1MaxNewSizePercent=50 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=15 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=20 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	Fabric Mods: 
		antixray: AntiXray 1.3.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		bluemap: BlueMap 3.12
		bluemapadvancedmarker: BlueMap Advanced Marker Addon 2022.10.1
		elder-daemon: Elder Daemon 1.0.0-1.19.4
		fabric-api: Fabric API 0.76.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.23+9ff28bcef4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.24+49abcf7ef4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.6+348a9c64f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d1f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.25+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.4+ae0966baf4
			fabric-commands-v0: Fabric Commands (v0) 0.2.42+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.52+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.7+ae0966baf4
			fabric-convention-tags-v1: Fabric Convention Tags 1.4.0+9a7c5daaf4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.3.5+5da15ca1f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.44+7f87f8faf4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.12+e45f7c65f4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.42+a1ccd7bff4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.51+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.32+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.16+09a3510cf4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.3+043f9acff4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.14+5da15ca1f4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.25+75e98211f4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.29+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.0+1ee8be40f4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.37+49abcf7ef4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.22+ca5f59aaf4
			fabric-networking-v0: Fabric Networking (v0) 0.3.39+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.1+63b515f4f4
			fabric-particles-v1: Fabric Particles (v1) 1.0.22+f1e4495bf4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.6+a1ccd7bff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.1.2+a383ab97f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.27+afca2f3ef4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.20+f1e4495bf4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.0+e6c7d4eef4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.0+938a1d56f4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.18+5da15ca1f4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.0.1+9003cbe9f4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.0.2+63b515f4f4
		fabric-language-kotlin: Fabric Language Kotlin 1.9.2+kotlin.1.8.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.0
		fabricloader: Fabric Loader 0.14.19
		ferritecore: FerriteCore 5.2.0
		invview: InvView 1.4.10-1.19.3+
			sgui: sgui 1.2.0+1.19.3
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.2.2
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		ledger: Ledger 1.2.7
			server_translations_api: Server Translations API 2.0.0-beta.2+1.19.4-pre2
				packet_tweaker: Packet Tweaker 0.3.1+23w06a
		ledger-databases: Ledger Databases 1.1.1
			com_h2database_h2: h2 1.4.200
			mysql_mysql-connector-java: mysql-connector-java 8.0.19
			org_postgresql_postgresql: postgresql 42.3.0
		lithium: Lithium 0.11.1
		mcdiscordchat: MCDiscordChat 2.1.3
			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.14.2
			com_fasterxml_jackson_core_jackson-core: jackson-core 2.14.2
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.14.2
			com_google_code_gson_gson: gson 2.10.1
			com_neovisionaries_nv-websocket-client: nv-websocket-client 2.14
			com_squareup_okhttp3_okhttp: okhttp 4.10.0
			com_squareup_okio_okio: okio 2.10.0
			com_vdurmont_emoji-java: emoji-java 5.1.1
			mcdiscordchat-1_19_4: MCDiscordChat 2.1.3
			net_dv8tion_jda: JDA 5.0.0-beta.5
			net_sf_trove4j_trove4j: trove4j 3.0.3
			org_apache_commons_commons-collections4: commons-collections4 4.4
			org_json_json: json 20230227
			org_slf4j_slf4j-api: slf4j-api 2.0.6
		memoryleakfix: Memory Leak Fix 1.0.0
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.6
		minecraft: Minecraft 1.19.4
		multiworldborders: Multi World Borders 1.6.0-fabric-1.19.4
		nochatreports: No Chat Reports 1.19.4-v2.1.0
		plan: Plan 5.5 build 2307
		servercore: ServerCore 1.3.5-1.19.4
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			placeholder-api: Placeholder API 2.0.0-rc.1+1.19.3
		spark: spark 1.10.34
		starlight: Starlight 1.1.1+fabric.ae22326
		timeoutout: TimeOut Out 1.0.3+1.19.1
		voicechat: Simple Voice Chat 1.19.4-2.4.1
		worldedit: WorldEdit 7.2.14+6360-094b734
	Server Running: true
	Player Count: 4 / 50; [class_3222['HaniBanani'/165, l='ServerLevel[world]', x=4400.68, y=62.00, z=-11703.70], class_3222['DinccDoncc'/342, l='ServerLevel[world]', x=6287.03, y=86.00, z=-2491.02], class_3222['PookMe'/1393, l='ServerLevel[world]', x=-5295.18, y=67.00, z=726.16], class_3222['Aikeko'/3399, l='ServerLevel[world]', x=-5296.40, y=67.00, z=727.64]]
	Data Packs: vanilla, file/Mendfinity_1.3.zip (incompatible), file/MobMuffler_1.4.zip (incompatible), file/horse-breeding-stat-fix.zip (incompatible), file/mining.zip (incompatible), file/donkey-and-mule-stat-fix.zip (incompatible), file/World_Pregen_1.3.zip (incompatible), file/CatCraft_V6.1.zip (incompatible), fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)


```

### Plugin versions

5.5-build-2307

### Additional information

We killed the original dog but when they got another one the server crashed after a bit

**Comment by AuroraLS3** [comment]
I did a quick fix for now that should prevent the server crashing and instead logs the error
https://github.com/plan-player-analytics/Plan/actions/runs/4819795073

**Comment by tropicdev** [comment]
AIght I have pushed it to my server and will be looking out for the error the last time it took 3 days I think

> I did a quick fix for now that should prevent the server crashing and instead logs the error https://github.com/plan-player-analytics/Plan/actions/runs/4819795073

**Comment by AnttiMK** [comment]
@tropicdev You're using an outdated version (`plan: Plan 5.5 build 2307`) which isn't compatible with fabric 1.19.4. Updating to the latest dev build (https://github.com/plan-player-analytics/Plan/releases/tag/5.5.2335) should fix the issue (unfortunately we don't ship with stricter version requirements/nags since more often than not, minor versions don't break Plan).

cc @AuroraLS3 NoSuchMethodErrors on fabric are 99% of time indicative of incompatible plugin versions so idk if the change on master is needed

**Comment by tropicdev** [comment]
> @tropicdev You are (or well, were..) using an outdated version (`plan: Plan 5.5 build 2307`) which isn't compatible with fabric 1.19.4 due to outdated mappings. ~Updating to the latest dev build (https://github.com/plan-player-analytics/Plan/releases/tag/5.5.2335) or just~ staying with the build you have now should fix the issue (unfortunately we don't ship with stricter version requirements/nags since more often than not, minor versions don't break Plan).
> 
> cc @AuroraLS3 NoSuchMethodErrors on fabric are 99% of time indicative of incompatible plugin versions so idk if the change on master is needed

Thank you for the update, will keep that in mind for future version updates.
