### ISSUE TITLE
Issue with MariaDB

### ISSUE THREAD

**Issue by starrider346** [plan-player-analytics/Plan#3192]
### Describe the issue

When starting the server, plan throws an error to do with MariaDB. I am not techy enough to know what the error means though.

### Exceptions & Other Logs

Plan has not generated any logs.

```
[14:47:07 ERROR] [global]: PlanBungee-v5.5 build 2461
java.lang.RuntimeException: Failed to load driver class org.mariadb.jdbc.Driver in either of HikariConfig class loader or Thread context classloader
        at plan.com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:488) ~[?:?]
        at com.djrapitops.plan.storage.database.MySQLDB.loadDataSource(MySQLDB.java:136) ~[?:?]
        at com.djrapitops.plan.storage.database.MySQLDB.setupDataSource(MySQLDB.java:115) ~[?:?]
        at com.djrapitops.plan.storage.database.SQLDB.init(SQLDB.java:156) ~[?:?]
        at com.djrapitops.plan.storage.database.DBSystem.enable(DBSystem.java:103) ~[?:?]
        at com.djrapitops.plan.PlanSystem.enableSystems(PlanSystem.java:225) ~[?:?]
        at com.djrapitops.plan.PlanSystem.enableOtherThanCommands(PlanSystem.java:182) ~[?:?]
        at com.djrapitops.plan.PlanSystem.enable(PlanSystem.java:220) ~[?:?]
        at com.djrapitops.plan.PlanBungee.onEnable(PlanBungee.java:70) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:316) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:299) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
```

### Plugin versions

5.5 2461

**Comment by AuroraLS3** [comment]
I would guess either the firewall blocked mariadb driver download, or you're using wrong version of MariaDB (version 10 and above 11.1 are supported, 11.0.2 is not supported.)

**Comment by starrider346** [comment]
thank you

**Comment by AuroraLS3** [comment]
I'll assume this solved it / will solve it, if it doesn't reply to this again.
