### ISSUE TITLE
NPE after right-click on button

### ISSUE THREAD

**Issue by SlimeDog** [plan-player-analytics/Plan#3228]
### Describe the issue

When I right-clicked on a button (tied to CommandSigns), the following error was generated every two seconds
```
[18:51:55 WARN]: [Plan] Task #97 for Plan v5.6 build 2542 generated an exception
java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "this.reasonForUnavailability" is null
        at com.djrapitops.plan.gathering.timed.SpigotPingMethod.getPing(SpigotPingMethod.java:49) ~[Plan-5.6-b2542.jar:?]
        at com.djrapitops.plan.gathering.timed.BukkitPingCounter.getPing(BukkitPingCounter.java:189) ~[Plan-5.6-b2542.jar:?]
        at com.djrapitops.plan.gathering.timed.BukkitPingCounter.run(BukkitPingCounter.java:160) ~[Plan-5.6-b2542.jar:?]
        at net.playeranalytics.plugin.scheduling.UnscheduledBukkitTask.run(UnscheduledBukkitTask.java:22) ~[Plan-5.6-b2542.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-201]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.2.jar:git-Paper-201]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1470) ~[paper-1.20.2.jar:git-Paper-201]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.2.jar:git-Paper-201]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-201]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-201]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-201]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
The error was not generated when I left-clicked on the same button, or left-clicked or right-clicked on a "free" button (ie., not associated with CommandSigns).

### Exceptions & Other Logs

No Plan logs. Do I need to configure something?

### Plugin versions

paper-1.20.2.jar:git-Paper-201
Plan-5.6-b2542

**Comment by AuroraLS3** [comment]
Fixed in https://github.com/plan-player-analytics/Plan/actions/runs/6295193047

**Comment by SlimeDog** [comment]
Confirmed fixed with build 2544 (linked above). Thanks.
