### ISSUE TITLE
Console flooded with: "Task #51 for Plan v5.6 build 2542 generated an exception"

### ISSUE THREAD

**Issue by Paulito91** [plan-player-analytics/Plan#3237]
### Describe the issue

Newest version floods console with same errors

### Exceptions & Other Logs
```
! [Sat 21:18:02 WARN  Plan] Task #51 for Plan v5.6 build 2542 generated an exception
java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "this.reasonForUnavailability" is null
    at Plan-5.6-dev-build-2542.jar//com.djrapitops.plan.gathering.timed.SpigotPingMethod.getPing(SpigotPingMethod.java:49)
    at Plan-5.6-dev-build-2542.jar//com.djrapitops.plan.gathering.timed.BukkitPingCounter.getPing(BukkitPingCounter.java:189)
    at Plan-5.6-dev-build-2542.jar//com.djrapitops.plan.gathering.timed.BukkitPingCounter.run(BukkitPingCounter.java:160)
    at Plan-5.6-dev-build-2542.jar//net.playeranalytics.plugin.scheduling.UnscheduledBukkitTask.run(UnscheduledBukkitTask.java:22)
    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run()
    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat()
    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java)
    at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java)
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

### Plugin versions

version 5.6 build 2542

**Comment by AuroraLS3** [comment]
This has been fixed, I guess I'll release another dev release today but in the meantime you can download one from here https://github.com/plan-player-analytics/Plan/actions/runs/6363438297
