### ISSUE TITLE
Plugin couldn’t start

### ISSUE THREAD

**Issue by grinheckerdev** [plan-player-analytics/Plan#3402]
### Describe the issue

When the plugin is enabled on the start of the server it throws an error.

### Exceptions & Other Logs

I can’t paste here the exception from the /plugins/Plan/logs because it doesn’t even exist. I am pasting the error from the console.

```

[08:35:43] [Server thread/ERROR]: Could not load 'plugins/Plan-5.6-build-2614.jar' in 
folder 'plugins'                                                                      org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml                     
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:178) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]                                 
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:
144) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]                                         
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:428) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3996-Spigot-e7ce55a-53ebb05]                     
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3996-Spigot-e7ce55a-53ebb05]                        
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1000) ~[spigot-
1.20.4-R0.1-SNAPSHOT.jar:3996-Spigot-e7ce55a-53ebb05]                                         at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[s
pigot-1.20.4-R0.1-SNAPSHOT.jar:3996-Spigot-e7ce55a-53ebb05]                           
        at java.lang.Thread.run(Thread.java:840) ~[?:?]                               Caused by: java.util.zip.ZipException: zip END header not found                       
        at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1633) ~[?:?]             
        at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1641) ~[?:?]                     at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1479) ~[?:?]              
        at java.util.zip.ZipFile$Source.get(ZipFile.java:1441) ~[?:?]                         at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:718) ~[?:?]            at java.util.zip.ZipFile.<init>(ZipFile.java:252) ~[?:?]                      
        at java.util.zip.ZipFile.<init>(ZipFile.java:181) ~[?:?]                              at java.util.jar.JarFile.<init>(JarFile.java:346) ~[?:?]                      
        at java.util.jar.JarFile.<init>(JarFile.java:317) ~[?:?]                              at java.util.jar.JarFile.<init>(JarFile.java:283) ~[?:?]                      
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:166) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]                                 
        ... 6 more

```

### Plugin versions

Latest version

**Comment by AuroraLS3** [comment]
Try re-downloading the jar, sounds like it is corrupt.

**Comment by grinheckerdev** [comment]
Ok

**Comment by grinheckerdev** [comment]
So I found the problem: the version from the GitHub releases page worked but the same version downloaded from the spigot web page is broken :/
