### ISSUE TITLE
DiscordSRV - Plan issues

### ISSUE THREAD

**Issue by SadLittleOctopus** [plan-player-analytics/Plan#3440]
### Describe the issue
I use DiscordSRV alongside Plan in my server. When the server starts and when some actions happen on Discord, Plan throws errors regarding DiscordSRV. It seems like Plan might be trying to obtain data regarding account linkage between MC and Discord. If this is the wrong place for this, let me know.

### Exceptions & Other Logs

```fd6bf6b175 - Last occurred: 2024-01-29 Occurrences: 4
---- Context 4 ----
Plan v5.6 build 2614
Purpur git-Purpur-2128 (MC: 1.20.4)
Server v1.20.4-R0.1-SNAPSHOT

Report and/or disable DiscordSRV extension in the Plan config.
DiscordSRV
Method:accountsLinked

---- Context 3 ----
Plan v5.6 build 2614
Purpur git-Purpur-2128 (MC: 1.20.4)
Server v1.20.4-R0.1-SNAPSHOT

Report and/or disable DiscordSRV extension in the Plan config.
DiscordSRV
Method:accountsLinked

---- Context 2 ----
Plan v5.6 build 2614
Purpur git-Purpur-2128 (MC: 1.20.4)
Server v1.20.4-R0.1-SNAPSHOT

Report and/or disable DiscordSRV extension in the Plan config.
DiscordSRV
Method:accountsLinked

---- Context 1 ----
Plan v5.6 build 2614
Purpur git-Purpur-2128 (MC: 1.20.4)
Server v1.20.4-R0.1-SNAPSHOT

Report and/or disable DiscordSRV extension in the Plan config.
DiscordSRV
Method:accountsLinked

---- Stacktrace ----
com.djrapitops.plan.exceptions.DataExtensionMethodCallException: DiscordSRV.accountsLinked errored: java.lang.IncompatibleClassChangeError: Found interface github.scarsz.discordsrv.objects.managers.AccountLinkManager, but class was expected
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:56)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.callMethod(DataValueGatherer.java:322)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.lambda$tryToBuildNumber$4(DataValueGatherer.java:246)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.builder.BuiltDataValue.getValue(BuiltDataValue.java:48)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.getValue(DataValueGatherer.java:452)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.storeNumber(DataValueGatherer.java:483)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.lambda$gather$25(DataValueGatherer.java:400)
   java.base/java.util.Optional.ifPresent(Optional.java:178)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.gather(DataValueGatherer.java:400)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.tryToUpdateValues(DataValueGatherer.java:363)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.updateValues(DataValueGatherer.java:351)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.ExtensionSvc.updateServerValues(ExtensionSvc.java:195)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.ExtensionSvc.updateServerValues(ExtensionSvc.java:187)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.ExtensionServerDataUpdater.run(ExtensionServerDataUpdater.java:51)
   Plan-5.6-build-2614.jar//net.playeranalytics.plugin.scheduling.UnscheduledBukkitTask.run(UnscheduledBukkitTask.java:22)
   org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
   org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
   com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
   java.base/java.lang.Thread.run(Thread.java:1583)
Caused by:
java.lang.reflect.InvocationTargetException
   java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
   java.base/java.lang.reflect.Method.invoke(Method.java:580)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.providers.Parameters$ServerParameters.usingOn(Parameters.java:64)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:50)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.callMethod(DataValueGatherer.java:322)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.lambda$tryToBuildNumber$4(DataValueGatherer.java:246)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.builder.BuiltDataValue.getValue(BuiltDataValue.java:48)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.getValue(DataValueGatherer.java:452)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.storeNumber(DataValueGatherer.java:483)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.lambda$gather$25(DataValueGatherer.java:400)
   java.base/java.util.Optional.ifPresent(Optional.java:178)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.gather(DataValueGatherer.java:400)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.tryToUpdateValues(DataValueGatherer.java:363)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.updateValues(DataValueGatherer.java:351)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.ExtensionSvc.updateServerValues(ExtensionSvc.java:195)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.ExtensionSvc.updateServerValues(ExtensionSvc.java:187)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.ExtensionServerDataUpdater.run(ExtensionServerDataUpdater.java:51)
   Plan-5.6-build-2614.jar//net.playeranalytics.plugin.scheduling.UnscheduledBukkitTask.run(UnscheduledBukkitTask.java:22)
   org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
   org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
   com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
   java.base/java.lang.Thread.run(Thread.java:1583)
Caused by:
java.lang.IncompatibleClassChangeError: Found interface github.scarsz.discordsrv.objects.managers.AccountLinkManager, but class was expected
   Plan-5.6-build-2614.jar//net.playeranalytics.extension.discordsrv.DiscordSRVExtension.getLinkedAccountCount(DiscordSRVExtension.java:86)
   Plan-5.6-build-2614.jar//net.playeranalytics.extension.discordsrv.DiscordSRVExtension.accountsLinked(DiscordSRVExtension.java:214)
   java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
   java.base/java.lang.reflect.Method.invoke(Method.java:580)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.providers.Parameters$ServerParameters.usingOn(Parameters.java:64)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:50)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.callMethod(DataValueGatherer.java:322)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.lambda$tryToBuildNumber$4(DataValueGatherer.java:246)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.builder.BuiltDataValue.getValue(BuiltDataValue.java:48)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.getValue(DataValueGatherer.java:452)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.storeNumber(DataValueGatherer.java:483)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.lambda$gather$25(DataValueGatherer.java:400)
   java.base/java.util.Optional.ifPresent(Optional.java:178)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.gather(DataValueGatherer.java:400)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.tryToUpdateValues(DataValueGatherer.java:363)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.updateValues(DataValueGatherer.java:351)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.ExtensionSvc.updateServerValues(ExtensionSvc.java:195)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.ExtensionSvc.updateServerValues(ExtensionSvc.java:187)
   Plan-5.6-build-2614.jar//com.djrapitops.plan.extension.ExtensionServerDataUpdater.run(ExtensionServerDataUpdater.java:51)
   Plan-5.6-build-2614.jar//net.playeranalytics.plugin.scheduling.UnscheduledBukkitTask.run(UnscheduledBukkitTask.java:22)
   org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
   org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
   com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
   java.base/java.lang.Thread.run(Thread.java:1583)
```

What happens soon after startup:
```
[08:46:45 WARN]: [Plan] Ran into DataExtensionMethodCallException - logged to plugins\Plan\logs\DataExtensionMethodCallException-b5eee4f695.txt
[08:46:45 WARN]: [Plan] (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[08:46:45 WARN]: [Plan] What to do: Report and/or disable DiscordSRV extension in the Plan config.
```
What happens seemingly randomly:
```
[23:15:10] [JDA MainWS-ReadThread/ERROR]: [DiscordSRV] [JDA] One of the EventListeners had an uncaught exception
java.lang.IncompatibleClassChangeError: Found interface github.scarsz.discordsrv.objects.managers.AccountLinkManager, but class was expected
	at Plan-5.6-build-2614.jar//net.playeranalytics.extension.discordsrv.DiscordSRVListener.updateUser(DiscordSRVListener.java:71)
	at Plan-5.6-build-2614.jar//net.playeranalytics.extension.discordsrv.DiscordSRVListener.onGuildMemberJoin(DiscordSRVListener.java:116)
	at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:483)
	at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
	at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
	at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
	at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.handleEvent(JDAImpl.java:159)
	at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.GuildMemberAddHandler.handleInternally(GuildMemberAddHandler.java:52)
	at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
	at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952)
	at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839)
	at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817)
	at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:991)
	at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
	at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
	at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
	at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
	at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.main(ReadingThread.java:108)
	at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

### Plugin versions

Plan: Version 5.6 build 2614
DiscordSRV: v1.27.0

**Comment by AuroraLS3** [comment]
See the pinned ticket at the top of issues
