### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by HazeWorksOnFiveMServer** [plan-player-analytics/Plan#3441]
### Describe the issue

Crashes my Fabric Server

### Exceptions & Other Logs

```
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3073 failed
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
        at net.minecraft.server.Main.main(Main.java:209) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.6.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3073 failed
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.6.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at net.minecraft.class_2170.<init>(class_2170.java:192) ~[server-intermediary.jar:?]
        at net.minecraft.class_5350.<init>(class_5350.java:43) ~[server-intermediary.jar:?]
        at net.minecraft.class_5350.method_29466(class_5350.java:73) ~[server-intermediary.jar:?]
        at net.minecraft.class_7237.method_42098(class_7237.java:50) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.method_43612(Main.java:162) ~[server-intermediary.jar:?]
        at net.minecraft.class_156.method_43498(class_156.java:944) ~[server-intermediary.jar:?]
        at net.minecraft.class_156.method_43499(class_156.java:938) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
        ... 4 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.6.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at net.minecraft.class_2170.<init>(class_2170.java:192) ~[server-intermediary.jar:?]
        at net.minecraft.class_5350.<init>(class_5350.java:43) ~[server-intermediary.jar:?]
        at net.minecraft.class_5350.method_29466(class_5350.java:73) ~[server-intermediary.jar:?]
        at net.minecraft.class_7237.method_42098(class_7237.java:50) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.method_43612(Main.java:162) ~[server-intermediary.jar:?]
        at net.minecraft.class_156.method_43498(class_156.java:944) ~[server-intermediary.jar:?]
        at net.minecraft.class_156.method_43499(class_156.java:938) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
        ... 4 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method onKickPlayer(Lnet/minecraft/class_2168;Ljava/util/Collection;Lnet/minecraft/class_2561;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V in plan.mixins.json:KickCommandMixin from mod plan failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap plan-fabric-refmap.json
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.6.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at net.minecraft.class_2170.<init>(class_2170.java:192) ~[server-intermediary.jar:?]
        at net.minecraft.class_5350.<init>(class_5350.java:43) ~[server-intermediary.jar:?]
        at net.minecraft.class_5350.method_29466(class_5350.java:73) ~[server-intermediary.jar:?]
        at net.minecraft.class_7237.method_42098(class_7237.java:50) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.method_43612(Main.java:162) ~[server-intermediary.jar:?]
        at net.minecraft.class_156.method_43498(class_156.java:944) ~[server-intermediary.jar:?]
        at net.minecraft.class_156.method_43499(class_156.java:938) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
        ... 4 more
```

### Plugin versions
Newest (PlanFabric-5.6-dev-build-2731.jar)

### Additional information
fabric server 1.20.1 - fabric api fabric-api-0.91.0+1.20.1.jar

**Comment by AuroraLS3** [comment]
Dev release is for 1.12.4

Use Last 5.5 release for 1.12.1
