### ISSUE TITLE
MySQL database fails to connect

### ISSUE THREAD

**Issue by OmegaWulf** [plan-player-analytics/Plan#3713]
### Describe the issue
Cannot connect to mysql database. Same issue persists on all servers across network. 

### Exceptions & Other Logs

Console error:
```
[18:07:41] [Plan MySQLDB-transaction-thread-1/ERROR]: [Plan] Database failed to open, com.djrapitops.plan.storage.database.transactions.init.CreateTablesTransaction failed to be executed.
[18:07:41] [Plan MySQLDB-transaction-thread-1/ERROR]: [Plan] Error msg: com.djrapitops.plan.storage.database.transactions.init.CreateTablesTransaction failed to execute and database could not be opened: SQL Failure: Failed to add the foreign key constraint. Missing index for constraint 'plan_tps_ibfk_1' in the referenced table 'plan_servers'
[18:07:41] [Plan MySQLDB-transaction-thread-1/ERROR]: [Plan] Ran into CompletionException - logged to plugins/Plan/logs/CompletionException-afa85171e6.txt
[18:07:41] [Plan MySQLDB-transaction-thread-1/ERROR]: [Plan] (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[18:07:41] [Plan MySQLDB-transaction-thread-1/ERROR]: [Plan] Error msg: "com.djrapitops.plan.exceptions.database.FatalDBException: com.djrapitops.plan.storage.database.transactions.init.CreateTablesTransaction failed to execute and database could not be opened: SQL Failure: Failed to add the foreign key constraint. Missing index for constraint 'plan_tps_ibfk_1' in the referenced table 'plan_servers'"
[18:07:41] [Plan MySQLDB-transaction-thread-1/ERROR]: [Plan] CRITICAL error triggered a plugin shutdown.
[18:07:41] [Craft Scheduler Thread - 11 - Plan/WARN]: [Plan] Plugin Plan v5.6 build 2883 generated an exception while executing task 26730
com.djrapitops.plan.exceptions.database.DBOpException: SQL Failure: Table 'plan_analytics.plan_extension_plugins' doesn't exist
	at com.djrapitops.plan.exceptions.database.DBOpException.forCause(DBOpException.java:153) ~[Plan-5.6-build-2883.jar:?]
	at com.djrapitops.plan.storage.database.queries.QueryStatement.executeWithConnection(QueryStatement.java:64) ~[Plan-5.6-build-2883.jar:?]
	at com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:52) ~[Plan-5.6-build-2883.jar:?]
	at com.djrapitops.plan.storage.database.SQLDB.lambda$query$2(SQLDB.java:339) ~[Plan-5.6-build-2883.jar:?]
	at com.djrapitops.plan.storage.database.DBAccessLock.performDatabaseOperation(DBAccessLock.java:102) ~[Plan-5.6-build-2883.jar:?]
	at com.djrapitops.plan.storage.database.DBAccessLock.performDatabaseOperation(DBAccessLock.java:87) ~[Plan-5.6-build-2883.jar:?]
	at com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:339) ~[Plan-5.6-build-2883.jar:?]
	at com.djrapitops.plan.storage.upkeep.ExtensionDisableOnGameServerTask.checkAndDisableProxyExtension(ExtensionDisableOnGameServerTask.java:71) ~[Plan-5.6-build-2883.jar:?]
	at com.djrapitops.plan.storage.upkeep.ExtensionDisableOnGameServerTask.lambda$checkAndDisableProxyExtensions$0(ExtensionDisableOnGameServerTask.java:64) ~[Plan-5.6-build-2883.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at com.djrapitops.plan.storage.upkeep.ExtensionDisableOnGameServerTask.checkAndDisableProxyExtensions(ExtensionDisableOnGameServerTask.java:64) ~[Plan-5.6-build-2883.jar:?]
	at com.djrapitops.plan.storage.upkeep.ExtensionDisableOnGameServerTask.run(ExtensionDisableOnGameServerTask.java:56) ~[Plan-5.6-build-2883.jar:?]
	at net.playeranalytics.plugin.scheduling.UnscheduledBukkitTask.run(UnscheduledBukkitTask.java:22) ~[Plan-5.6-build-2883.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2166]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.4.jar:git-Purpur-2166]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.sql.SQLSyntaxErrorException: Table 'plan_analytics.plan_extension_plugins' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121) ~[mysql-connector-j-8.2.0.jar:8.2.0]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-j-8.2.0.jar:8.2.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:912) ~[mysql-connector-j-8.2.0.jar:8.2.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:968) ~[mysql-connector-j-8.2.0.jar:8.2.0]
	at plan.com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[Plan-5.6-build-2883.jar:?]
	at plan.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[Plan-5.6-build-2883.jar:?]
	at com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:72) ~[Plan-5.6-build-2883.jar:?]
	at com.djrapitops.plan.storage.database.queries.QueryStatement.executeWithConnection(QueryStatement.java:62) ~[Plan-5.6-build-2883.jar:?]
	... 25 more
[18:07:41] [Plan MySQLDB-transaction-thread-1/INFO]: [Plan] Processing complete.
[18:07:41] [Plan MySQLDB-transaction-thread-1/INFO]: [Plan] Waiting for unfinished transactions to avoid data loss..
[18:07:41] [Plan Non critical-pool-4/ERROR]: [Plan] Failed to read plugins/Plan/logs/DBOpException-c8bff004d2.txt deleting file
[18:07:41] [Plan Non critical-pool-4/WARN]: [Plan] Ran into DBOpException - logged to plugins/Plan/logs/DBOpException-c8bff004d2.txt
[18:07:41] [Plan Non critical-pool-4/WARN]: [Plan] (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[18:07:41] [Plan Non critical-pool-4/WARN]: [Plan] What to do: Report this, there is an SQL grammar error.
[18:08:01] [Plan MySQLDB-transaction-thread-1/INFO]: [Plan] Player Analytics Disabled.
```

Plan logs: 
1. CompletionException
```
afa85171e6 - Last occurred: 2024-07-25 Occurrences: 1
---- Context 1 ----
Plan v5.6 build 2883
Purpur git-Purpur-2166 (MC: 1.20.4)
Server v1.20.4-R0.1-SNAPSHOT

Transaction: class com.djrapitops.plan.storage.database.transactions.init.CreateTablesTransaction
DB State: CLOSED - fatal: true
Error code: 1822
CREATE TABLE IF NOT EXISTS plan_tps (id integer NOT NULL AUTO_INCREMENT,server_id integer NOT NULL,date bigint NOT NULL,tps double NOT NULL,players_online integer NOT NULL,cpu_usage double NOT NULL,ram_usage bigint NOT NULL,entities integer NOT NULL,chunks_loaded integer NOT NULL,free_disk_space bigint NOT NULL,PRIMARY KEY (id),FOREIGN KEY(server_id) REFERENCES plan_servers(id))
Unknown SQL Error code

---- Stacktrace ----
java.util.concurrent.CompletionException: com.djrapitops.plan.exceptions.database.FatalDBException: com.djrapitops.plan.storage.database.transactions.init.CreateTablesTransaction failed to execute and database could not be opened: SQL Failure: Failed to add the foreign key constraint. Missing index for constraint 'plan_tps_ibfk_1' in the referenced table 'plan_servers'
   java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
   java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
   java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
   java.base/java.lang.Thread.run(Thread.java:1583)
Caused by:
com.djrapitops.plan.exceptions.database.FatalDBException: com.djrapitops.plan.storage.database.transactions.init.CreateTablesTransaction failed to execute and database could not be opened: SQL Failure: Failed to add the foreign key constraint. Missing index for constraint 'plan_tps_ibfk_1' in the referenced table 'plan_servers'
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.transactions.init.OperationCriticalTransaction.executeTransaction(OperationCriticalTransaction.java:41)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$4(SQLDB.java:373)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.DBAccessLock.performDatabaseOperation(DBAccessLock.java:61)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.DBAccessLock.performDatabaseOperation(DBAccessLock.java:56)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$5(SQLDB.java:372)
   java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
   java.base/java.lang.Thread.run(Thread.java:1583)
Caused by:
java.sql.SQLException: Failed to add the foreign key constraint. Missing index for constraint 'plan_tps_ibfk_1' in the referenced table 'plan_servers'
   com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
   com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
   com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:912)
   com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:354)
   Plan-5.6-build-2883.jar//plan.com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
   Plan-5.6-build-2883.jar//plan.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.transactions.ExecStatement.callExecute(ExecStatement.java:72)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:64)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:55)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.transactions.Transaction.execute(Transaction.java:223)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.transactions.Transaction.execute(Transaction.java:231)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.transactions.init.CreateTablesTransaction.performOperations(CreateTablesTransaction.java:48)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.transactions.Transaction.executeTransaction(Transaction.java:89)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.transactions.init.OperationCriticalTransaction.executeTransaction(OperationCriticalTransaction.java:36)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$4(SQLDB.java:373)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.DBAccessLock.performDatabaseOperation(DBAccessLock.java:61)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.DBAccessLock.performDatabaseOperation(DBAccessLock.java:56)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$5(SQLDB.java:372)
   java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
   java.base/java.lang.Thread.run(Thread.java:1583)
   java.base/java.lang.Thread.getStackTrace(Thread.java:2450)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.SQLDB.executeTransaction(SQLDB.java:359)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.SQLDB.setupDatabase(SQLDB.java:262)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.SQLDB.init(SQLDB.java:162)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.DBSystem.enable(DBSystem.java:103)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.BukkitDBSystem.enable(BukkitDBSystem.java:54)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.PlanSystem.enableSystems(PlanSystem.java:181)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.PlanSystem.enableOtherThanCommands(PlanSystem.java:138)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.PlanSystem.enable(PlanSystem.java:176)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.Plan.onEnable(Plan.java:94)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.commands.subcommands.PluginStatusCommands.lambda$onReload$0(PluginStatusCommands.java:76)
   java.base/java.lang.Thread.run(Thread.java:1583)

```

2. DBOpException
```
c8bff004d2 - Last occurred: 2024-07-25 Occurrences: 1
---- Context 1 ----
Plan v5.6 build 2883
Purpur git-Purpur-2166 (MC: 1.20.4)
Server v1.20.4-R0.1-SNAPSHOT

Report this, there is an SQL grammar error.
Error code: 1146
SELECT username FROM plan_security
SQL Grammar error

---- Stacktrace ----
com.djrapitops.plan.exceptions.database.DBOpException: SQL Failure: Table 'plan_analytics.plan_security' doesn't exist
   Plan-5.6-build-2883.jar//com.djrapitops.plan.exceptions.database.DBOpException.forCause(DBOpException.java:153)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.queries.QueryStatement.executeWithConnection(QueryStatement.java:64)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:52)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.SQLDB.lambda$query$2(SQLDB.java:339)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.DBAccessLock.performDatabaseOperation(DBAccessLock.java:102)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.DBAccessLock.performDatabaseOperation(DBAccessLock.java:87)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:339)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.Database.queryCollection(Database.java:83)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.Database.queryList(Database.java:75)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.queries.objects.WebUserQueries.lambda$fetchAllUsernames$19(WebUserQueries.java:202)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.SQLDB.lambda$query$2(SQLDB.java:339)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.DBAccessLock.performDatabaseOperation(DBAccessLock.java:102)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.DBAccessLock.performDatabaseOperation(DBAccessLock.java:87)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:339)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.commands.TabCompleteCache.refreshUserIdentifiers(TabCompleteCache.java:103)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.commands.TabCompleteCache.lambda$enable$0(TabCompleteCache.java:79)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:85)
   java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
   java.base/java.lang.Thread.run(Thread.java:1583)
Caused by:
java.sql.SQLSyntaxErrorException: Table 'plan_analytics.plan_security' doesn't exist
   com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
   com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
   com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:912)
   com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:968)
   Plan-5.6-build-2883.jar//plan.com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
   Plan-5.6-build-2883.jar//plan.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:72)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.queries.QueryStatement.executeWithConnection(QueryStatement.java:62)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:52)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.SQLDB.lambda$query$2(SQLDB.java:339)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.DBAccessLock.performDatabaseOperation(DBAccessLock.java:102)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.DBAccessLock.performDatabaseOperation(DBAccessLock.java:87)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:339)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.Database.queryCollection(Database.java:83)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.Database.queryList(Database.java:75)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.queries.objects.WebUserQueries.lambda$fetchAllUsernames$19(WebUserQueries.java:202)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.SQLDB.lambda$query$2(SQLDB.java:339)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.DBAccessLock.performDatabaseOperation(DBAccessLock.java:102)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.DBAccessLock.performDatabaseOperation(DBAccessLock.java:87)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:339)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.commands.TabCompleteCache.refreshUserIdentifiers(TabCompleteCache.java:103)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.commands.TabCompleteCache.lambda$enable$0(TabCompleteCache.java:79)
   Plan-5.6-build-2883.jar//com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:85)
   java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
   java.base/java.lang.Thread.run(Thread.java:1583)

```

### Plugin versions
Plan v5.6 build 2883
Purpur 1.20.4

**Comment by AuroraLS3** [comment]
Mysql user doesn't have some required privilege, either the foreign key creation one or the create index one - see the installation tutorial mysql step for the required privileges and grant them to the user for this specific database.

**Comment by OmegaWulf** [comment]
> Mysql user doesn't have some required privilege, either the foreign key creation one or the create index one - see the installation tutorial mysql step for the required privileges and grant them to the user for this specific database.

I've granted all permissions to `plan_analytics` user for the `plan_analytics` db. The user has no global privileges although I don't think this would cause issues.

**Comment by AuroraLS3** [comment]
You may need to delete plan_servers and plan_tps tables if they exist, to have it recreated, the error says some index is missing for plan_tps to refer to plan_servers

**Comment by AuroraLS3** [comment]
These indexes are usually created automatically, so if your database configuration has somehow disabled the automatic creation it may need to be changed back
