### ISSUE TITLE
尝试在 Velocity 中加载 Plan ，但是没有成功

### ISSUE THREAD

**Issue by Minecraft0122** [plan-player-analytics/Plan#3800]
描述一下问题。

在 Velocity 中加载 Plan，服务器反复报出以下错误：
Cannot invoke "plan.com.zaxxer.hikari.HikariDataSource.getConnection()" because "this.dataSource" is null

### 异常与日志

```
6c5663d042 - Last occurred: 2024-09-27 Occurrences: 2
---- Context 2 ----
Plan v5.6 build 2883
Velocity 3.3.0-SNAPSHOT (git-2016d148-b436)
Server v3.3.0-SNAPSHOT (git-2016d148-b436)

Allow Plan to check for updates from Github/versions.txt or disable update check.
Version information could not be loaded from Github/versions.txt

---- Context 1 ----
Plan v5.6 build 2883
Velocity 3.3.0-SNAPSHOT (git-2016d148-b436)
Server v3.3.0-SNAPSHOT (git-2016d148-b436)

Allow Plan to check for updates from Github/versions.txt or disable update check.
Version information could not be loaded from Github/versions.txt

---- Stacktrace ----
java.net.ConnectException: Connection timed out
   java.base/sun.nio.ch.Net.connect0(Native Method)
   java.base/sun.nio.ch.Net.connect(Net.java:589)
   java.base/sun.nio.ch.Net.connect(Net.java:578)
   java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583)
   java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
   java.base/java.net.Socket.connect(Socket.java:751)
   java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
   java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:181)
   java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
   java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
   java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
   java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
   java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:377)
   java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
   java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1237)
   java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1123)
   java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
   java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1675)
   java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
   java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
   java.base/java.net.URL.openStream(URL.java:1325)
   com.djrapitops.plan.version.VersionInfoLoader.load(VersionInfoLoader.java:51)
   com.djrapitops.plan.version.VersionChecker.loadVersionInfo(VersionChecker.java:77)
   com.djrapitops.plan.version.VersionChecker.checkForUpdates(VersionChecker.java:88)
   com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:285)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
   java.base/java.lang.Thread.run(Thread.java:1583)
```

### 插件版本

Plan：5.6-build-2883
Geyser-Velocity：最新版

### 附加信息

[ConnectException-6c5663d042.txt](https://github.com/user-attachments/files/17164218/ConnectException-6c5663d042.txt)

**Comment by AuroraLS3** [comment]
It sounds like Plan has not enabled. What does the enable log say?

**Comment by Minecraft0122** [comment]
> 听起来 Plan 尚未启用。启用日志是怎么说的？

````
[INFO] 正在启动...
[INFO] 仿真终端模式已生效，您可以直接在终端内直接输入内容并使用 Ctrl，Tab 等功能键
[20:28:51 INFO]: Booting up Velocity 3.3.0-SNAPSHOT (git-2016d148-b436)...
[20:28:51 INFO]: Loading localizations...
[20:28:51 INFO]: Connections will use epoll channels, libdeflate (Linux x86_64) compression, OpenSSL 3.x.x (Linux x86_64) ciphers
[20:28:51 INFO]: Loading plugins...
[20:28:52 INFO]: Loaded plugin geyser 2.4.3-b680 (git-master-84dac08) by GeyserMC
[20:28:52 INFO]: Loaded plugin plan 5.6 build 2883 by AuroraLS3
[20:28:52 INFO]: Loaded 3 plugins
[20:28:53 INFO] [geyser]: Loading extensions...
[20:28:53 INFO] [geyser]: Loaded 0 extension(s)
[20:28:53 INFO] [plan]: §2
[20:28:53 INFO] [plan]: §2           ██▌
[20:28:53 INFO] [plan]: §2     ██▌   ██▌
[20:28:53 INFO] [plan]: §2  ██▌██▌██▌██▌  §2Player Analytics
[20:28:53 INFO] [plan]: §2  ██▌██▌██▌██▌  §fv5.6 build 2883
[20:28:53 INFO] [plan]: §2
[20:28:53 INFO] [plan]: Locale: 'English' by AuroraLS3
[20:28:53 INFO] [plan]: Downloading MySQL Driver, this may take a while...
[20:29:53 ERROR]: Exception in task com.djrapitops.plan.settings.network.NetworkSettingManager$$Lambda/0x00007fe9545bfd10@4ff89cc4 by plugin Plan
java.lang.NullPointerException: Cannot invoke "plan.com.zaxxer.hikari.HikariDataSource.getConnection()" because "this.dataSource" is null
        at com.djrapitops.plan.storage.database.MySQLDB.getConnection(MySQLDB.java:212) ~[?:?]
        at com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:51) ~[?:?]
        at com.djrapitops.plan.storage.database.SQLDB.lambda$query$2(SQLDB.java:339) ~[?:?]
        at com.djrapitops.plan.storage.database.DBAccessLock.performDatabaseOperation(DBAccessLock.java:102) ~[?:?]
        at com.djrapitops.plan.storage.database.DBAccessLock.performDatabaseOperation(DBAccessLock.java:87) ~[?:?]
        at com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:339) ~[?:?]
        at com.djrapitops.plan.settings.network.NetworkSettingManager.updateConfigFromDBIfUpdated(NetworkSettingManager.java:168) ~[?:?]
        at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:285) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[20:30:53 ERROR]: Exception in task com.djrapitops.plan.settings.network.NetworkSettingManager$$Lambda/0x00007fe9545bfd10@4ff89cc4 by plugin Plan
java.lang.NullPointerException: Cannot invoke "plan.com.zaxxer.hikari.HikariDataSource.getConnection()" because "this.dataSource" is null
        at com.djrapitops.plan.storage.database.MySQLDB.getConnection(MySQLDB.java:212) ~[?:?]
        at com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:51) ~[?:?]
        at com.djrapitops.plan.storage.database.SQLDB.lambda$query$2(SQLDB.java:339) ~[?:?]
        at com.djrapitops.plan.storage.database.DBAccessLock.performDatabaseOperation(DBAccessLock.java:102) ~[?:?]
        at com.djrapitops.plan.storage.database.DBAccessLock.performDatabaseOperation(DBAccessLock.java:87) ~[?:?]
        at com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:339) ~[?:?]
        at com.djrapitops.plan.settings.network.NetworkSettingManager.updateConfigFromDBIfUpdated(NetworkSettingManager.java:168) ~[?:?]
        at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:285) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[20:31:53 ERROR]: Exception in task com.djrapitops.plan.settings.network.NetworkSettingManager$$Lambda/0x00007fe9545bfd10@4ff89cc4 by plugin Plan
java.lang.NullPointerException: Cannot invoke "plan.com.zaxxer.hikari.HikariDataSource.getConnection()" because "this.dataSource" is null
        at com.djrapitops.plan.storage.database.MySQLDB.getConnection(MySQLDB.java:212) ~[?:?]
        at com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:51) ~[?:?]
        at com.djrapitops.plan.storage.database.SQLDB.lambda$query$2(SQLDB.java:339) ~[?:?]
        at com.djrapitops.plan.storage.database.DBAccessLock.performDatabaseOperation(DBAccessLock.java:102) ~[?:?]
        at com.djrapitops.plan.storage.database.DBAccessLock.performDatabaseOperation(DBAccessLock.java:87) ~[?:?]
        at com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:339) ~[?:?]
        at com.djrapitops.plan.settings.network.NetworkSettingManager.updateConfigFromDBIfUpdated(NetworkSettingManager.java:168) ~[?:?]
        at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:285) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[20:32:53 ERROR]: Exception in task com.djrapitops.plan.settings.network.NetworkSettingManager$$Lambda/0x00007fe9545bfd10@4ff89cc4 by plugin Plan
java.lang.NullPointerException: Cannot invoke "plan.com.zaxxer.hikari.HikariDataSource.getConnection()" because "this.dataSource" is null
        at com.djrapitops.plan.storage.database.MySQLDB.getConnection(MySQLDB.java:212) ~[?:?]
        at com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:51) ~[?:?]
        at com.djrapitops.plan.storage.database.SQLDB.lambda$query$2(SQLDB.java:339) ~[?:?]
        at com.djrapitops.plan.storage.database.DBAccessLock.performDatabaseOperation(DBAccessLock.java:102) ~[?:?]
        at com.djrapitops.plan.storage.database.DBAccessLock.performDatabaseOperation(DBAccessLock.java:87) ~[?:?]
        at com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:339) ~[?:?]
        at com.djrapitops.plan.settings.network.NetworkSettingManager.updateConfigFromDBIfUpdated(NetworkSettingManager.java:168) ~[?:?]
        at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:285) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[20:33:14 ERROR]: Sep 27, 2024 8:33:14 PM com.djrapitops.plan.PlanVelocity onEnable
[20:33:14 ERROR]: SEVERE: PlanVelocity-v5.6 build 2883
[20:33:14 ERROR]: java.lang.NullPointerException
[20:33:14 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.andTree(CompletableFuture.java:1520)
[20:33:14 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.allOf(CompletableFuture.java:2451)
[20:33:14 ERROR]:       at plan.dev.vankka.dependencydownload.DependencyManager.downloadAll(DependencyManager.java:191)
[20:33:14 ERROR]:       at com.djrapitops.plan.storage.database.SQLDB.downloadDriver(SQLDB.java:135)
[20:33:14 ERROR]:       at com.djrapitops.plan.storage.database.MySQLDB.setupDataSource(MySQLDB.java:99)
[20:33:14 ERROR]:       at com.djrapitops.plan.storage.database.SQLDB.init(SQLDB.java:161)
[20:33:14 ERROR]:       at com.djrapitops.plan.storage.database.DBSystem.enable(DBSystem.java:103)
[20:33:14 ERROR]:       at com.djrapitops.plan.PlanSystem.enableSystems(PlanSystem.java:181)
[20:33:14 ERROR]:       at com.djrapitops.plan.PlanSystem.enableOtherThanCommands(PlanSystem.java:138)
[20:33:14 ERROR]:       at com.djrapitops.plan.PlanSystem.enable(PlanSystem.java:176)
[20:33:14 ERROR]:       at com.djrapitops.plan.PlanVelocity.onEnable(PlanVelocity.java:112)
[20:33:14 ERROR]:       at com.djrapitops.plan.PlanVelocity.onProxyStart(PlanVelocity.java:94)
[20:33:14 ERROR]:       at com.djrapitops.plan.Lmbda$5.execute(Unknown Source)
[20:33:14 ERROR]:       at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56)
[20:33:14 ERROR]:       at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:676)
[20:33:14 ERROR]:       at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:541)
[20:33:14 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[20:33:14 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[20:33:14 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)
[20:33:14 ERROR]: 
[20:33:14 ERROR] [plan]: Plugin Failed to Initialize Correctly. If this issue is caused by config settings you can use /planvelocity reload
[20:33:14 ERROR] [plan]: This error should be reported at https://github.com/plan-player-analytics/Plan/issues
[20:33:14 INFO] [plan]: Processing complete.
[20:33:14 INFO] [plan]: Waiting for unfinished transactions to avoid data loss..
[20:33:14 INFO] [plan]: Transaction queue closed.
[20:33:14 INFO] [plan]: Player Analytics Disabled.
````

**Comment by AuroraLS3** [comment]
Your firewall is blocking mysql driver download

**Comment by Minecraft0122** [comment]
> 您的防火墙阻止了 mysql 驱动程序下载

感谢，我发现我的服务器不允许我访问非中国大陆的地址，我已在我本地下载完驱动并上传至服务器
