### ISSUE TITLE
Folia - ConcurrentModification Exception

### ISSUE THREAD

**Issue by Euphillya** [plan-player-analytics/Plan#3844]
### Describe the issue
```
[18:47:31 WARN]: [Plan] Global task for Plan v5.6 build 2883 generated an exception
java.util.ConcurrentModificationException: null
        at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1605) ~[?:?]
        at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1638) ~[?:?]
        at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1636) ~[?:?]
        at Plan-5.6-build-2883.jar/com.djrapitops.plan.gathering.timed.BukkitPingCounter.run(BukkitPingCounter.java:155) ~[Plan-5.6-build-2883.jar:?]
        at Plan-5.6-build-2883.jar/net.playeranalytics.plugin.scheduling.UnscheduledFoliaTask.lambda$runTaskTimer$5(UnscheduledFoliaTask.java:69) ~[Plan-5.6-build-2883.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:181) ~[bloomexcalia-1.21.1.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[bloomexcalia-1.21.1.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[bloomexcalia-1.21.1.jar:1.21.1-32-fc47d7b]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[bloomexcalia-1.21.1.jar:1.21.1-32-fc47d7b]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:418) ~[bloomexcalia-1.21.1.jar:1.21.1-32-fc47d7b]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:540) ~[bloomexcalia-1.21.1.jar:1.21.1-32-fc47d7b]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
        ```
```

### Plugin versions
```
[18:49:11 INFO]: Plan version 5.6 build 2883
[18:49:11 INFO]: Author: AuroraLS3
```
### Additional information
My server running on Folia

**Comment by AuroraLS3** [comment]
Looks like since Folia doesn't have single thread ticking these ping tasks can execute in parallel causing this issue.
