### ISSUE TITLE
Transaction Lock wait timeout exceeded; try restarting transaction

### ISSUE THREAD

**Issue by Rsl1122** [plan-player-analytics/Plan#966]
### Describe the bug
Clean transaction can take too long to execute due to executing multiple remove player transactions.

### Server information

MySQL

### Exceptions & Other Logs
```
Caused by: com.djrapitops.plan.api.exceptions.database.DBOpException: PingStoreTransaction failed: SQL Failed: INSERT INTO plan_ping (uuid, server_uuid, date, min_ping, max_ping, avg_ping) VALUES (?, ?, ?, ?, ?, ?); (conn:2070788) Lock wait timeout exceeded; try restarting transaction, Transaction was rolled back.
at com.djrapitops.plan.db.access.transactions.Transaction.manageFailure(Transaction.java:85) ~[Transaction.class:?]
at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:70) ~[Transaction.class:?]
at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:222) ~[SQLDB.class:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_191]
... 3 more
Caused by: com.djrapitops.plan.api.exceptions.database.DBOpException: SQL Failed: INSERT INTO plan_ping (uuid, server_uuid, date, min_ping, max_ping, avg_ping) VALUES (?, ?, ?, ?, ?, ?); (conn:2070788) Lock wait timeout exceeded; try restarting transaction
at com.djrapitops.plan.api.exceptions.database.DBOpException.forCause(DBOpException.java:37) ~[DBOpException.class:?]
at com.djrapitops.plan.db.access.ExecStatement.execute(ExecStatement.java:45) ~[ExecStatement.class:?]
at com.djrapitops.plan.db.access.transactions.Transaction.execute(Transaction.java:119) ~[Transaction.class:?]
at com.djrapitops.plan.db.access.transactions.events.PingStoreTransaction.performOperations(PingStoreTransaction.java:59) ~[PingStoreTransaction.class:?]
at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:66) ~[Transaction.class:?]
at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:222) ~[SQLDB.class:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_191]
... 3 more
Caused by: java.sql.SQLException: (conn:2070788) Lock wait timeout exceeded; try restarting transaction
at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:179) ~[ExceptionMapper.class:1.12.2-2768-7.1.6-RC3626]
at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118) ~[ExceptionMapper.class:1.12.2-2768-7.1.6-RC3626]
at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:245) ~[MariaDbStatement.class:1.12.2-2768-7.1.6-RC3626]
at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:218) ~[MariaDbPreparedStatementClient.class:1.12.2-2768-7.1.6-RC3626]
at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:153) ~[MariaDbPreparedStatementClient.class:1.12.2-2768-7.1.6-RC3626]
at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeUpdate(MariaDbPreparedStatementClient.java:186) ~[MariaDbPreparedStatementClient.class:1.12.2-2768-7.1.6-RC3626]
at plan.com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[ProxyPreparedStatement.class:?]
at plan.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariProxyPreparedStatement.class:?]
at com.djrapitops.plan.db.access.ExecStatement.callExecute(ExecStatement.java:60) ~[ExecStatement.class:?]
at com.djrapitops.plan.db.access.ExecStatement.execute(ExecStatement.java:52) ~[ExecStatement.class:?]
at com.djrapitops.plan.db.access.ExecStatement.execute(ExecStatement.java:42) ~[ExecStatement.class:?]
at com.djrapitops.plan.db.access.transactions.Transaction.execute(Transaction.java:119) ~[Transaction.class:?]
at com.djrapitops.plan.db.access.transactions.events.PingStoreTransaction.performOperations(PingStoreTransaction.java:59) ~[PingStoreTransaction.class:?]
at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:66) ~[Transaction.class:?]
at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:222) ~[SQLDB.class:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_191]
... 3 more
Caused by: java.sql.SQLException: Lock wait timeout exceeded; try restarting transaction
Query is: INSERT INTO plan_ping (uuid, server_uuid, date, min_ping, max_ping, avg_ping) VALUES (?, ?, ?, ?, ?, ?), parameters ['a7cd0748-724e-4dc7-9d71-37e40f7466af','e1dfea3e-3f1d-3735-a5a1-aba6fcee08e1',1552489228558,87,173,118.0]
at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:146) ~[LogQueryTool.class:1.12.2-2768-7.1.6-RC3626]
at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:223) ~[AbstractQueryProtocol.class:1.12.2-2768-7.1.6-RC3626]
at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:212) ~[MariaDbPreparedStatementClient.class:1.12.2-2768-7.1.6-RC3626]
at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:153) ~[MariaDbPreparedStatementClient.class:1.12.2-2768-7.1.6-RC3626]
at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeUpdate(MariaDbPreparedStatementClient.java:186) ~[MariaDbPreparedStatementClient.class:1.12.2-2768-7.1.6-RC3626]
at plan.com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[ProxyPreparedStatement.class:?]
at plan.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariProxyPreparedStatement.class:?]
at com.djrapitops.plan.db.access.ExecStatement.callExecute(ExecStatement.java:60) ~[ExecStatement.class:?]
at com.djrapitops.plan.db.access.ExecStatement.execute(ExecStatement.java:52) ~[ExecStatement.class:?]
at com.djrapitops.plan.db.access.ExecStatement.execute(ExecStatement.java:42) ~[ExecStatement.class:?]
at com.djrapitops.plan.db.access.transactions.Transaction.execute(Transaction.java:119) ~[Transaction.class:?]
at com.djrapitops.plan.db.access.transactions.events.PingStoreTransaction.performOperations(PingStoreTransaction.java:59) ~[PingStoreTransaction.class:?]
at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:66) ~[Transaction.class:?]
at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:222) ~[SQLDB.class:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_191]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_191]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_191]
at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_191]
at com.djrapitops.plan.db.SQLDB.executeTransaction(SQLDB.java:218) ~[SQLDB.class:?]
at com.djrapitops.plan.system.tasks.sponge.PingCountTimerSponge.run(PingCountTimerSponge.java:94) ~[PingCountTimerSponge.class:?]
at com.djrapitops.plugin.task.sponge.SpongeRunnableFactory$1.run(SpongeRunnableFactory.java:57) ~[SpongeRunnableFactory$1.class:?]
at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2768-7.1.6-RC3626]
at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:192) ~[SchedulerBase.class:1.12.2-2768-7.1.6-RC3626]
at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:74) ~[SyncScheduler.class:1.12.2-2768-7.1.6-RC3626]
at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:183) ~[SchedulerBase.class:1.12.2-2768-7.1.6-RC3626]
at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:169) ~[SchedulerBase.class:1.12.2-2768-7.1.6-RC3626]
at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) ~[?:1.8.0_191]
at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:112) ~[SchedulerBase.class:1.12.2-2768-7.1.6-RC3626]
at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:47) ~[SyncScheduler.class:1.12.2-2768-7.1.6-RC3626]
at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:189) ~[SpongeScheduler.class:1.12.2-2768-7.1.6-RC3626]
at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:404) ~[SpongeMod.class:1.12.2-2768-7.1.6-RC3626]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_378_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:746) ~[EventBus.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:696) ~[EventBus.class:?]
at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279) ~[FMLCommonHandler.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) ~[MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) ~[MinecraftServer.class:?]
... 1 more
```
(The exception occurs on PingInsertTransaction, but it is likely that the previous transaction is still waiting on the previous lock)

In `SHOW ENGINE INNODB STATUS` the deadlock appears to be related to CleanTransaction
```
------------------------
LATEST DETECTED DEADLOCK
------------------------
2019-02-17 18:02:22 0x7fb56c185700
*** (1) TRANSACTION:
TRANSACTION 25417725, ACTIVE 0 sec starting index read
mysql tables in use 2, locked 2
LOCK WAIT 2 lock struct(s), heap size 1136, 1 row lock(s)
MySQL thread id 670602, OS thread handle 140416815015680, query id 14451697 172.18.0.2 u6_N5nzIYIV8p updating
DELETE FROM plan_users WHERE (uuid='79288dd6-5e80-4f42-a818-71db90c4f7e5')
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 55 page no 54 n bits 416 index uuid of table `s6_Plans`.`plan_users` trx id 25417725 lock_mode X locks rec but not gap waiting
Record lock, heap no 332 PHYSICAL RECORD: n_fields 2; compact format; info bits 32
 0: len 30; hex 37393238386464362d356538302d346634322d613831382d373164623930; asc 79288dd6-5e80-4f42-a818-71db90; (total 36 bytes);
 1: len 4; hex 800027f4; asc   ' ;;

*** (2) TRANSACTION:
TRANSACTION 25417726, ACTIVE 0 sec starting index read
mysql tables in use 2, locked 2
3 lock struct(s), heap size 1136, 2 row lock(s)
MySQL thread id 670338, OS thread handle 140417179342592, query id 14451696 172.18.0.4 u6_N5nzIYIV8p updating
DELETE FROM plan_users WHERE (uuid='79288dd6-5e80-4f42-a818-71db90c4f7e5')
*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 55 page no 54 n bits 416 index uuid of table `s6_Plans`.`plan_users` trx id 25417726 lock_mode X locks rec but not gap
Record lock, heap no 332 PHYSICAL RECORD: n_fields 2; compact format; info bits 32
 0: len 30; hex 37393238386464362d356538302d346634322d613831382d373164623930; asc 79288dd6-5e80-4f42-a818-71db90; (total 36 bytes);
 1: len 4; hex 800027f4; asc   ' ;;

*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 55 page no 54 n bits 416 index uuid of table `s6_Plans`.`plan_users` trx id 25417726 lock_mode X waiting
Record lock, heap no 332 PHYSICAL RECORD: n_fields 2; compact format; info bits 32
 0: len 30; hex 37393238386464362d356538302d346634322d613831382d373164623930; asc 79288dd6-5e80-4f42-a818-71db90; (total 36 bytes);
 1: len 4; hex 800027f4; asc   ' ;;

*** WE ROLL BACK TRANSACTION (1)
```

**Comment by Rsl1122** [comment]
Fixed in commit 52841f37241a1de526c958c5c68412f2bbaafc28
