### ISSUE TITLE
Won't Start on Thermos Servers

### ISSUE THREAD

**Issue by io-craft** [plan-player-analytics/Plan#984]
### Describe the bug
Won't start.

### Server information
Thermos-1614, Plan-4.7.2

### Exceptions & Other Logs
java.lang.NoClassDefFoundError: plan/dagger/internal/Preconditions

### Additional information
```
[01:42:59] [Server thread/ERROR]: Error occurred while enabling Plan v4.7.2 (Is it up to date?)
java.lang.NoClassDefFoundError: plan/dagger/internal/Preconditions
        at com.djrapitops.plan.DaggerPlanBukkitComponent$Builder.plan(DaggerPlanBukkitComponent.java:1640) ~[?:?]
        at com.djrapitops.plan.DaggerPlanBukkitComponent$Builder.plan(DaggerPlanBukkitComponent.java:1625) ~[?:?]
        at com.djrapitops.plan.Plan.onEnable(Plan.java:47) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.58]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.58]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.58]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438) [CraftServer.class:1.7.10-1614.58]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372) [CraftServer.class:1.7.10-1614.58]
        at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.ClassNotFoundException: Failed to remap class plan.dagger.internal.Preconditions
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:534) ~[PluginClassLoader.class:1.7.10-1614.58]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:455) ~[PluginClassLoader.class:1.7.10-1614.58]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1614.58]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_191]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191]
        ... 14 more
Caused by: java.lang.RuntimeException
        at org.objectweb.asm.MethodVisitor.visitParameter(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
        at org.objectweb.asm.ClassReader.b(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
        at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
        at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
        at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:246) ~[JarRemapper.class:?]
        at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:232) ~[JarRemapper.class:?]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:499) ~[PluginClassLoader.class:1.7.10-1614.58]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:455) ~[PluginClassLoader.class:1.7.10-1614.58]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1614.58]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_191]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191]
        ... 14 more
```

**Comment by io-craft** [comment]
Had to revert back to 2.X version of the plugin, which totally sucks.

**Comment by Rsl1122** [comment]
Use the fix for KCauldron described in the additional set up  section of bukkit set up
https://github.com/plan-player-analytics/Plan/wiki/Bukkit-Set-Up#kcauldron

**Comment by io-craft** [comment]
Oh cool, I actually had to nab that for DiscordSRV, so I should already be patched. Will try and then close this ticket. Thank you!

**Comment by Rsl1122** [comment]
I'll assume this fixed.
