### ISSUE TITLE
Plan MySQLDB-transaction-thread-0/ERROR

### ISSUE THREAD

**Issue by KingdomsMineMC** [plan-player-analytics/Plan#985]
```
[Plan MySQLDB-transaction-thread-0/ERROR]: [Plan] Error was caught by com.djrapitops.plan.db.MySQLDB
java.util.concurrent.CompletionException: com.djrapitops.plan.api.exceptions.database.DBOpException: StoreHackViolationKickTransaction failed: SQL Failed: INSERT INTO plan_aac_hack_table (uuid, date, hack_type, violation_level) VALUES (?, ?, ?, ?); Unknown column 'date' in 'field list', Transaction was rolled back.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_201]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) [?:1.8.0_201]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: com.djrapitops.plan.api.exceptions.database.DBOpException: StoreHackViolationKickTransaction failed: SQL Failed: INSERT INTO plan_aac_hack_table (uuid, date, hack_type, violation_level) VALUES (?, ?, ?, ?); Unknown column 'date' in 'field list', Transaction was rolled back.
	at com.djrapitops.plan.db.access.transactions.Transaction.manageFailure(Transaction.java:85) ~[Plan-4.7.2.jar:?]
	at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:70) ~[Plan-4.7.2.jar:?]
	at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:222) ~[Plan-4.7.2.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_201]
	... 3 more
Caused by: com.djrapitops.plan.api.exceptions.database.DBOpException: SQL Failed: INSERT INTO plan_aac_hack_table (uuid, date, hack_type, violation_level) VALUES (?, ?, ?, ?); Unknown column 'date' in 'field list'
	at com.djrapitops.plan.api.exceptions.database.DBOpException.forCause(DBOpException.java:37) ~[Plan-4.7.2.jar:?]
	at com.djrapitops.plan.db.access.ExecStatement.execute(ExecStatement.java:45) ~[Plan-4.7.2.jar:?]
	at com.djrapitops.plan.db.access.transactions.Transaction.execute(Transaction.java:119) ~[Plan-4.7.2.jar:?]
	at com.djrapitops.pluginbridge.plan.aac.StoreHackViolationKickTransaction.performOperations(StoreHackViolationKickTransaction.java:43) ~[Plan-4.7.2.jar:?]
	at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:66) ~[Plan-4.7.2.jar:?]
	at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:222) ~[Plan-4.7.2.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_201]
	... 3 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'date' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_201]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_201]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at plan.com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[Plan-4.7.2.jar:?]
	at plan.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[Plan-4.7.2.jar:?]
	at com.djrapitops.plan.db.access.ExecStatement.callExecute(ExecStatement.java:60) ~[Plan-4.7.2.jar:?]
	at com.djrapitops.plan.db.access.ExecStatement.execute(ExecStatement.java:52) ~[Plan-4.7.2.jar:?]
	at com.djrapitops.plan.db.access.ExecStatement.execute(ExecStatement.java:42) ~[Plan-4.7.2.jar:?]
	at com.djrapitops.plan.db.access.transactions.Transaction.execute(Transaction.java:119) ~[Plan-4.7.2.jar:?]
	at com.djrapitops.pluginbridge.plan.aac.StoreHackViolationKickTransaction.performOperations(StoreHackViolationKickTransaction.java:43) ~[Plan-4.7.2.jar:?]
	at com.djrapitops.plan.db.access.transactions.Transaction.executeTransaction(Transaction.java:66) ~[Plan-4.7.2.jar:?]
	at com.djrapitops.plan.db.SQLDB.lambda$executeTransaction$1(SQLDB.java:222) ~[Plan-4.7.2.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_201]
	at com.djrapitops.plan.db.SQLDB.executeTransaction(SQLDB.java:218) ~[Plan-4.7.2.jar:?]
	at com.djrapitops.pluginbridge.plan.aac.PlayerHackKickListener.onKick(PlayerHackKickListener.java:58) ~[Plan-4.7.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at me.konsolas.aac.bS.a(bS.java:7) ~[AAC.jar:3.5.0]
	at me.konsolas.aac.b4.run(b4.java:6) ~[AAC.jar:3.5.0]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	... 1 more
```

**Comment by Rsl1122** [comment]
Steps that you can take to try to fix this issue:

- Update Plan to latest version if not already
- Drop `plan_aac_hack_table` from the database
- Disable AAC integration in the Plan Config.

**Comment by Rsl1122** [comment]
I'll assume this fixed.
